### ISSUE TITLE
Add FakeStore with possibility for switching to real Play Store

### ISSUE THREAD

**Issue by nift4** [nift4/microg_installer_revived#10]
- [x] Add FakeStore with Play Store priv-app permissions
- [x] Test installing Play Store over FakeStore
- [x] Fix installing Play Store somehow (maybe by creating special edition of the module or creating an addon)

**Comment by nift4** [comment]
It was tested and it did not work...

**Comment by Fs00** [comment]
Original Play Store can't work as-is with microG. Luckily, Nanolx created a script to patch Play Store APKs to make them work with microG: https://gitlab.com/Nanolx/microg-phonesky-iap-support/.
It would be awesome if you made a version of this module with patched Play Store!

**Comment by nift4** [comment]
I know that but thanks anyway. I added instructions in the README until I find an proper solution.

**Comment by Fs00** [comment]
My fault, didn't read the Readme well enough :sweat_smile: 
Thanks

**Comment by nift4** [comment]
Fixed with 1.7.0-0, more Infos in README

**Comment by Fs00** [comment]
Great! There's only a small problem with your approach: real Phonesky needs [some files under /etc](https://gitlab.com/Nanolx/microg-phonesky-iap-support/-/tree/master/etc) to work properly.

If you could add a way to add automatically these files when needed it would be perfect!

**Comment by nift4** [comment]
They are already present (default permissions is left out for privacy reasons)

**Comment by nift4** [comment]
I have it working here perfectly fine

**Comment by Fs00** [comment]
You're right, I didn't realize that there is a file containing all the privapp-permissions for Play Store and microG.
I agree with you on default-permissions, it shouldn't be needed for correct functionality. Many thanks!
