### ISSUE TITLE
false keep crashing

### ISSUE THREAD

**Issue by moolight-seashell** [nift4/microg_installer_revived#100]
iv made a real play store install with lineage os magisk lsposed and fakegapps

my play store is named false for some reason and cannot open

![Screenshot_20231108-211444_cropped.png](https://github.com/nift4/microg_installer_revived/assets/49676861/c9e91547-d379-4684-bc39-09a1f1e410fc)

**Comment by nift4** [comment]
i recommend to clean install

you can try to delete all subfolders (but not package_cache itself) of /data/system/package_cache/ but it might cause bootloop, you have been warned

**Comment by moolight-seashell** [comment]
i have a folder with random char and a list of file inside, should i delete the random char named folder ?

you talk about clean istall , does i need to uninstall every microg related before and reinstall after ?

**Comment by nift4** [comment]
yes delete the random char folder

if you decide to cleaninstall, yes need to uninstall, format data and reinstall

**Comment by moolight-seashell** [comment]
hi hello there, no boot llop and it works now ! thanks
