### ISSUE TITLE
Installer keep installing old and deleted version of real Play Store

### ISSUE THREAD

**Issue by MarcoDjallo** [nift4/microg_installer_revived#102]
Hello! Long time user here, so long that apparently this is causing some issues!

I started using the installer when the readme was still advising to use a patched play store version (if I remember well).

This worked good, until I started having some issues of Play Store crashing.

So, I tried to update the play store putting a new, vanilla version in /data/adb/ (full path is /sdcard/data/adb right? because I cannot create an adb folder in the /data folder that is present in the root of my phone, even if of course I'm rooted), but it was still installing the old version.

So, I uninstalled everything: the module, and manually I uninstalled the play store. Reinstalled again, but it was still getting the old version somewhere and installing that one!

In the end, I had to switch to minmicrog, which installs correctly. However, I would prefer to use your module because is more updated and I find it cleaner.

My device is Poco F2, Android 14 Crdroid (but I had the same issues also on android 12 and 13).

Thanks!

**Comment by nift4** [comment]
no it's not in /sdcard - /data/adb is created for you by Android and used by Magisk, you should not need to create it. Last time you probably put the play store in the correct path and hence it installed said old version again

**Comment by nift4** [comment]
install log?

**Comment by nift4** [comment]
the messages during install

**Comment by nift4** [comment]
@foxjaw please go to Settings > Apps > All apps... > microG companion (or Fake Store if you last used older module version) > three dots in upper right corner > Uninstall updated

**Comment by nift4** [comment]
disable denylist for play store, if still crashing please logs

**Comment by nift4** [comment]
Settings > Developer options > Bug report > (select interactive) then email it to me nift4@protonmail.com

**Comment by nift4** [comment]
you can filter log files to your preferences with https://developer.android.com/tools/logcat

**Comment by nift4** [comment]
Yes, logcat is complicated, hence I recommended the built-in bug report feature.
You should be able to write to /sdcard/log.txt though.

**Comment by MarcoDjallo** [comment]
> no it's not in /sdcard - /data/adb is created for you by Android and used by Magisk, you should not need to create it. Last time you probably put the play store in the correct path and hence it installed said old version again

Ok so my problem comes already from this: I don't have an adb folder in my data folder. How's that possible?

**Comment by nift4** [comment]
> > no it's not in /sdcard - /data/adb is created for you by Android and used by Magisk, you should not need to create it. Last time you probably put the play store in the correct path and hence it installed said old version again
> 
> Ok so my problem comes already from this: I don't have an adb folder in my data folder. How's that possible?

You do have it. Otherwise, Magisk would not work at all. I am pretty sure it is a setup issue that you can't see it. If in doubt, try "su" (enter) "ls /data/adb" in termux

**Comment by nift4** [comment]
were you able to solve this?
