### ISSUE TITLE
Official Play Store is unable to install any apps

### ISSUE THREAD

**Issue by AnonVendetta** [nift4/microg_installer_revived#103]
Device: Tab S7 Plus, SM-T976N
Rooted with Magisk Delta, and TWRP installed
ROM: AOSP Android 14 gsi, by phhusson (Build date is 11-17-2023). It has native signature spoofing, and no GApps are bundled. Just plain, barebones vanilla AOSP
Using latest MIR zip
Official Play Store version is 38.4.22, obtained from APKMirror
Mount namespace is set to global in Magisk
Zygisk disabled
"Unmount modules" disabled in Magisk Delta
No processes/apps are selected for "configure unmount" in Magisk Delta

I flashed the zip in Magisk, along with Phonesky.apk in the specified adb directory. No errors reported during flashing. then rebooted. Afterwards I configured MicroG settings, another reboot. Then I launched Play Store, logged in, all appeared fine. Until I tried to install a free app, LTE Discovery, which is compatible with my device. At first I get a generic crash message "Play Store has stopped". So I tried to download it again and again, but always same message, " can't download this app". My exact wording may be off, since I'm recalling from memory, but these tests were very recent (within the past 15 mins). I also tried manually granting all perms, including notification perm. On my of my tries, I didn't get an error, but a neverending downloading notification appeared, saying that the app was downloading. But it never actually completed, after several mins. Force stopping the store then relaunching just brings the notification back, so Play Store must be "remembering" what it was last trying to get.

I also tried with several other free apps, like Total Commander and Call of Duty Mobile, behavior is the same.

I never had these issues with MIR on Android 13, so I think it's a case of needed perms not being granted. My internet isn't the issue, I have fiber at home, everything else that uses internet works.

If someone will tell me what logs are needed, I'll try to get them.

**Comment by AnonVendetta** [comment]
So i decided to uninstall MIR and try MinMicroG, to test. It seems that the Play Store in MinMicroG works nearly 100%. I just had to install a newer APK on top of what was bundled in the zip (same APK I used with MIR). No problems downloading/installing apps. So far the only issues I'm having with that are that the "add credit/debit card" and "add PayPal" options cause Play Store to silently crash (no error, it just insta-drops me back into my launcher). No big deal, I can use those options in a webpage as a workaround. But it does make me curious why I can't install any apps while using Play Store with MIR, whereas with MinMicroG there is no issue. The version of Play Store is the same for both, both using the same APK, once updated manually. The only difference is the MicroG installer used.

I still like your installer more, until today I'd never heard of MinMicroG. MIR is all I ever used with Android 12/13, and it always worked as expected. I'll still provide any logs requested. I also like that MIR includes a location overlay APK, which no other MicroG installer seems to have included. To be fair, that overlay could probably work with any installer.

**Comment by nift4** [comment]
Hi, thank you for the high-quality bug report. Can you please give me a log of the PlayStore crash?

**Comment by AnonVendetta** [comment]
> Hi, thank you for the high-quality bug report. Can you please give me a log of the PlayStore crash?

Should I use logcat to get the logs? Or Android's internal bug report feature in dev options? Any other needed logs (Magisk log)?

Before I do so, I will format my data partition and set the ROM up again. Maybe MinMicroG will taint the results, even after in installation. It's a Magisk module too, but sometimes modules take a dump in other places and don't clean everything up.

**Comment by nift4** [comment]
Android's bug report is good, as that is the easiest option for everyone

**Comment by AnonVendetta** [comment]
[bugreport-treble_arm64_bvS-UP1A.231105.003-2023-11-22-23-51-43.zip](https://github.com/nift4/microg_installer_revived/files/13447189/bugreport-treble_arm64_bvS-UP1A.231105.003-2023-11-22-23-51-43.zip)

Here is the bug report. I generated it after logging into Play Store, and several tries of downloading a free app, none successful. I do also get the downloading notification again, but it never finishes. Even if I force stop the store, the notification returns and never finishes. I can get rid of it by clearing PS app data, but that doesnt solve the issue.

For now, I'm testing installing MinMicroG in system mode.

**Comment by nift4** [comment]
Hi, does it work after disabling battery optimization for Play Store?

**Comment by AnonVendetta** [comment]
> Hi, does it work after disabling battery optimization for Play Store?

I doubt that will resolve anything, will have to test. Battery optimization was already disabled by MicroG, not sure about Play Store.

Were you able to get any useful info from the logs?

**Comment by AnonVendetta** [comment]
I was wrong...battery optimization appears to be the issue. I kept all variables as much the same as possible. I de-optimized it and Play Store now downloads normally, same as my results with MinMicroG. I thought BO only applied to apps running as background processes, not foreground.

After de-optimization, I tested foreground and background downloading. LTE Discovery, with Play Store in foreground, installs fine. And Garena Free Fire Max, a less than 1GB mobile shooter, in the background. It displayed a notification and after a bit, the app icon appeared in the launcher.

Later versions of Android also has something called "phantom process killer", which I disabled with root access via terminal commands. Besides optimization, I figured that maybe PPK might be playing a role (unlikely), and disabled it anyway. I use Termux, and PPK actively interferes with it, so disabling it is one of the first things i do.

On your end, maybe you can test with my gsi/steps and see if you get the same results. You can install the gsi ROM via DSU Sideloader. It supports root, adb or Shizuku install methods. DSU makes it possible to keep your current ROM as primary, while testing a gsi as secondary ROM.

You could also add something into the config files that auto disables optimization for Play Store/FakeStore. That would solve it for everyone. I get that de-optimizing Play Store may be undesirable for some users, they may not want to give Google any more than is necessary. But for users that are running PS instead of FakeStore, optimization may be a required step for it to be able to operate normally.

Or you could not add it to the config files, instead adding a note to the readme stating that users need to manually disable optimization for PS.

I find just it weird that i never needed to manually disable optimization for PS on Android 13, yet it wont run normally on Android 14 gsi if it's optimized.

Before I conclude this issue, I still have 2 more tests to try, I want to confirm some things. When I'm sure, I do additional tests anyway.

**Comment by AnonVendetta** [comment]
2nd test:
So I was curious to see if I could evoke the same bad behavior, but with MinMicroG instead of MIR. And to see if battery optimization was really the issue on Android 14.

I used this zip:
MinMicroG-MinimalIAP-2.12.0-20230729205917.zip

I unpacked it, then edited the /system/etc/sysconfig/nogoolag.xml. Then removed the line "<allow-in-power-save-except-idle package="com.android.vending" />", saved the file, repacked new zip. I needed to mimic the scenario of Play Store being optimized. Then I flashed the modded zip in Magisk.

Next steps:
Update MicroG GmsCore and MicroG GSF Proxy to the latest versions on microg.org (0.3.0 and 0.1.0, respectively). I also updated Play Store with the same APK that I used with MIR. Then I configured MicroG, rebooted, logged into Play Store, and tried the same downloads of LTE Discovery and Garena Free Fire Max. Both failed, with the same results that I initially reported here. Then I disabled optimization for PS, rebooted again, and tried the same 2 downloads in foreground/background. They succeeded. So optimization really is the issue on Android 14, and it's not just happening with MIR only.

**Comment by AnonVendetta** [comment]
OK, so the final test is finished. I wanted to try MIR on an Android 13 gsi, one I've used in the past. Just to see, once again, if battery optimization had any effect. And to confirm what I've already said, that I never deoptimized Play Store on 13/12/10, but never had downloads fail.

I used this gsi:
https://github.com/TrebleDroid/treble_experimentations/releases/tag/ci-20230905

It is also AOSP by phhusson, the most recent Android 13 build. I tried to keep the conditions the same as in my previous tests here. Which were, to flash MIR in Magisk, update the MicroG GmsCore/GsfProxy/Play Store APKs, followed by configuring MicroG, then logging into Play Store. On this run, I checked the battery optimization status for PS, and it was indeed being optimized by Android. I opted to leave it as is, to simulate my statement that i havent touched battery optimization settings on older Android versions. And, downloading/installing is fine, even with optimization in effect for PS.

So it would seem that what I've reported here only affects Android 14, but not older Android versions. Hence why it always worked in the past, but not on 14 without manually disabling optimization.

**Comment by nift4** [comment]
Hi, yes, Android 14 introduced foreground service restrictions and the download kept failing because Play Store did not meet any of the requirements to start a service, which caused download service to crash (according to your log). One way to meet these requirements is disabling battery optimization, hence I recommended it. I will look into auto-disabling optimization with the installer for the next release.

**Comment by AnonVendetta** [comment]
> Hi, yes, Android 14 introduced foreground service restrictions and the download kept failing because Play Store did not meet any of the requirements to start a service, which caused download service to crash (according to your log). One way to meet these requirements is disabling battery optimization, hence I recommended it. I will look into auto-disabling optimization with the installer for the next release.

Thanks for the info. Perhaps you can create an additional config file for 14 only, have your installer detect if the ROM is 14, then substitute this file in place of the main one for older Android versions. Then optimization would only be disabled for Play Store when necessary. If you dont need any more info, this issue can be closed. For now manually deoptimizing is a solution.

**Comment by AnonVendetta** [comment]
No responses in a few days, so I'm assuming no more info is needed. Closing.
