### ISSUE TITLE
GmsCore conflict in ColorOS/OxygenOS

### ISSUE THREAD

**Issue by Xynonners** [nift4/microg_installer_revived#104]
Hi,

I came across a rather interesting OEM-specific bug where due to GmsCore being installed (and supposedly discovered) by ColorOS in my_bigball and not system, putting microG in /system/priv-app/GmsCore and removing /my_bigball/priv-app/GmsCore seems to be ignored (no google services installed, either gapps or microg).

The OS seems to have some sort of hardcoded limitation to look for GmsCore in my_bigball.

MinMicroG installs GmsCore to MicroGGMSCore, which bypasses this (though due to it's lack of overlay or smth ColorOS really likes updating it back to stock gapps), and renaming the folder & apk seems to bypass this limitation.

**Comment by nift4** [comment]
> The OS seems to have some sort of hardcoded limitation to look for com.google.android.gms in my_bigball.

Is it about package name or folder name?

**Comment by Xynonners** [comment]
@nift4 seems to be the folder/file name of the apk, pretty sure folder.

**Comment by Xynonners** [comment]
> @Xynonners, Which device are you experiencing this issue with and how did you De-Google (Remove GMS) on your device? In my experience, using MicroG Installer Revived with this patch causes MicroG to crash upon opening on my OxygenOS 14 Device (OnePlus 11 5G CPH2451). I have removed GApps using [SystemlessDebloater](https://github.com/zgfg/SystemlessDebloater) and removed the following packages (I separated each package name with a space): `Velvet YouTube Gmail2 HotwordEnrollmentOKGoogleHEXAGON HotwordEnrollmentXGoogleHEXAGON Google_AssistantShell CalendarGoogle Chrome Photos Phonesky GoogleOneTimeInitializer GoogleServicesFramework GmsCore GoogleRestore GooglePartnerSetup`

Oppo Find X6 Pro, COS 13.1. 

I debloated via a custom module I made called Directory Systemless Debloater (modified systemless debloater that mounts over the entire directory rather than just the apk), 
(part of this guide https://xdaforums.com/t/guide-find-x6-pro-comprehensive-globalization-guide.4652669/)

mounted directories were:
```
/my_bigball/non_overlay/GoogleServicesFramework
/my_bigball/priv-app/GmsCore
/my_bigball/priv-app/GooglePlayServicesUpdater
/my_bigball/app/WebviewGoogleCN
```

**Comment by Xynonners** [comment]
I find this issue quite odd actually since my S8U tablet (also A13) has a renamed MicroGGmsCore and it also seems to work fine.
