### ISSUE TITLE
Unable to update gms core on LineageOS. 

### ISSUE THREAD

**Issue by kaizerking** [nift4/microg_installer_revived#106]
On LineageOS gms core apk downloaded using browser from microg website tried to install update but unable update 
message  'app not installed as package appears to be invalid
How ever, downloaded gsf apk  updated without any problem.
GalaxyTab GT-N8000, LineageOS 20 
'

**Comment by nift4** [comment]
can you use `adb install` and copy paste the exact error message

**Comment by kaizerking** [comment]
I did not try to update gms and gsf now
Earlier tried twice with fresh installations, problem remains same. Thought no point in trying again. 
waiting to get a fix on this

**Comment by nift4** [comment]
i can't fix it unless you tell me the adb error message because it works for me

**Comment by kaizerking** [comment]
I understand. I am currently using this Samsung Galaxy GT-N 8000 as car display unit. It is working in this condition. When I get free time I will try and ge adb install and give you the report. I am keeping this opened.

**Comment by nift4** [comment]
stale, will reopen when report is ready
