### ISSUE TITLE
Last update failed?

### ISSUE THREAD

**Issue by UnlimitedCookies** [nift4/microg_installer_revived#108]
I think during the last update through magisk, magisk crashed. Now I get this error:  https://paste.crdroid.net/BdLKcd

**Comment by nift4** [comment]
do you have huawei device?

**Comment by UnlimitedCookies** [comment]
Nope

**Comment by nift4** [comment]
do you have real play store or custom fake store version (like -hw/-lh variant)?

**Comment by UnlimitedCookies** [comment]
I use the microg fakestore.

**Comment by nift4** [comment]
can you try to press "uninstall updates" in App-Info of microG Companion?

**Comment by UnlimitedCookies** [comment]
Well, since the last boot, the issue does not appear in the logs anymore. I will report back, once it returns; thanks for you efforts.
Also, there is no "uninstall updates" in the App Info section of the system settings and also not on the specific app detail view.
