### ISSUE TITLE
Microg compagnion keeps crashing

### ISSUE THREAD

**Issue by Incomptus** [nift4/microg_installer_revived#109]
Hello,

On redmi note 8t , i have installed microg revived, and it microg compagnion keeps craching often.
For example ifi open vinted app, it crashes

Other microg functions are working good.

I tried to reinstall microg magisk module but no succes.

**Comment by nift4** [comment]
can you please send a logcat

**Comment by Incomptus** [comment]
> can you please send a logcat

https://drive.google.com/file/d/1-4mlvg3lE8W0hWfYlH10CJ_Zln5StvxM/view?usp=drivesdk

I hope it is working like that

Thanks

**Comment by Wojtaz0w** [comment]
> > can you please send a logcat
> 
> https://drive.google.com/file/d/1-4mlvg3lE8W0hWfYlH10CJ_Zln5StvxM/view?usp=drivesdk
> 
> I hope it is working like that
> 
> Thanks

I can't view the file. Please make it public or better yet upload to privatebin / pastebin

**Comment by Incomptus** [comment]
Hello normaly the access is given

**Comment by RossComputerGuy** [comment]
I'm experiencing the same problem.

**Comment by RossComputerGuy** [comment]
I uninstalled microG which I had installed over ADB and then tried applying it in Magisk, didn't crash.

**Comment by Incomptus** [comment]
> I uninstalled microG which I had installed over ADB and then tried applying it in Magisk, didn't crash.

Ok i ll give it a try after my rom update. But in my case i always installed microg revived through magisk.

**Comment by Incomptus** [comment]
> I uninstalled microG which I had installed over ADB and then tried applying it in Magisk, didn't crash.

Hello, i am about to uninstall microg to reinstall it. But i just thought about something. Reinstalling microg might change my android ID? 
And maybe it is more effective to install real playstore with the phonesky.apk technique?

**Comment by Incomptus** [comment]
Maybe i should just wait microg companion stable update as the 0.3 is a preview release

**Comment by nift4** [comment]
Hi, the log file sadly does not contain relevant information. Can you please create bug report ZIP using (Android) Settings > Developer options > Create bug report > Interactive and email it to me nift4@protonmail.com, thanks

**Comment by Incomptus** [comment]
> Hi, the log file sadly does not contain relevant information. Can you please create bug report ZIP using (Android) Settings > Developer options > Create bug report > Interactive and email it to me nift4@protonmail.com, thanks

Hi! It s done bro! Thank you

**Comment by nift4** [comment]
hi @Incomptus please try to disable magisk hide / deny list for microg companion, it should not be hidden

**Comment by Incomptus** [comment]
> hi @Incomptus please try to disable magisk hide / deny list for microg companion, it should not be hidden

Wow that was it, thanks bro!!!, i dont even remember why it s in the denny list.

Thanks

**Comment by Wojtaz0w** [comment]
> hi @Incomptus please try to disable magisk hide / deny list for microg companion, it should not be hidden

I believe you could add this to README or some FAQ. Or just pin this issue, to prevent duplicate bug reports from appearing.
Cheers

**Comment by nift4** [comment]
> > hi @Incomptus please try to disable magisk hide / deny list for microg companion, it should not be hidden
> 
> I believe you could add this to README or some FAQ. Or just pin this issue, to prevent duplicate bug reports from appearing. Cheers

done
