### ISSUE TITLE
MicroG Services keeps stopping

### ISSUE THREAD

**Issue by B4rabbas** [nift4/microg_installer_revived#111]
I followed the step of installation, and there is nothing in magisk's denylist.
FakeGapps is activated in Lsposed too.

"download & install APK as update"
What do you mean, where I have to download na apk ? From fdroid in the microG repo I can't update.
I have download microG apks and install them manually, MicroG companion don't crash anymore but it don't fix the microG Service.

**Comment by nift4** [comment]
you have some kind of play integrity fix or safetynet fix or shamiko or other root hide?

**Comment by cagedbird043** [comment]
> you have some kind of play integrity fix or safetynet fix or shamiko or other root hide?

If I want to use Shamiko and microg at the same time, can I install microg first and then shamiko?

**Comment by nift4** [comment]
I never used Shamiko

**Comment by cagedbird043** [comment]
> I never used Shamiko

Well, I just tried it, and shamiko and this microg cannot be used together at all.

**Comment by africabloe** [comment]
> From fdroid in the microG repo I can't update. I have download microG apks and install them manually, MicroG companion don't crash anymore but it don't fix the microG Service.

Xiaomi Redmi Note 4x (mido)
Android 14
crDroid 10.1
Magisk Delta Canary - R65A24840-kitsune 26404

I had the same problem. microG services was crashing on opening.
I followed the instructions and updated [microG Services com.google.android.gms v0.3.0.233515](https://microg.org/fdroid/repo/com.google.android.gms-233515000.apk) and all services immediately worked normally. I hope the same happens in your case.
Big thanks to developer @nift4 for all his work.

**Comment by bitblocks-dev** [comment]
I am also running into this issue with the latest version and Shamiko. Whenever I add MicroG to the Magisk denylist in order for SafetyNet to work, it crashes. Is this perhaps related to Issue #75? I also noticed that MicroG appears to be installed as a systemless app... Correct me if I am wrong, but wouldn't adding a systemless app to the Magisk denylist make it impossible to run?

**Comment by nift4** [comment]
While the package manager has no problem with systemless apps that are hidden from themselves, the apps do crash because they can't access their own APK. To solve this, customize.sh automatically installs the APK we install systemless to /data as well, which does seem to work for almost every user. Everyone else has to manually install the APK if they want to use Denylist.

**Comment by nift4** [comment]
If OP still has an issue, please comment and I will reopen it.

**Comment by yuzamei2854** [comment]
> you have some kind of play integrity fix or safetynet fix or shamiko or other root hide?

Hi, I'm sorry if I'm intruding on this issue, but since you mentioned these modules, if I try to use any of them would it cause any problems?

Is there a better way to pass Play Integrity or SafetyNet when using your MicroG module?

**Comment by nift4** [comment]
If you have set it up and it works, don't worry about it. 

Sorry for reopening, that was a misclick.
