### ISSUE TITLE
Can the "shell" Play Store be installed even if you use LOS+MicroG ROMs?

### ISSUE THREAD

**Issue by BurhanBudak** [nift4/microg_installer_revived#112]
Hi.

So I already have MicroG bundled, but I need the "shell" Play Store to replace MicroG Companion. I used to use FakeStore2PlayStore module but its been discontinued by the dev who now uses GrapheneOS. So can I install the module and only pick the nodded PlayStore?

**Comment by nift4** [comment]
"shell" Play Store? You meant the real Play Store or?

**Comment by BurhanBudak** [comment]
> "shell" Play Store? You meant the real Play Store or?

Wow that was fast. Sure, but I worry that there will be a issue.
I used to use this module for a shell PlagStore:

https://github.com/sn-00-x/fakestore2playstore

The dev does warn that it didn't work that well on 18.1 so I'll not sure if you patched the bug. But is your module for people with bare LOS or with LOS using preinstalled microG?

**Comment by nift4** [comment]
My module is intended for bare LOS and ships microG with it

**Comment by nift4** [comment]
stale
