### ISSUE TITLE
microG Services keep stopping

### ISSUE THREAD

**Issue by helmutrocco13** [nift4/microg_installer_revived#113]

**Comment by nift4** [comment]
Please go to (Your phone's) Settings > Developer options > Create bug report > Interactive, wait for it to complete (ie do not cancel it) and then email it to me: nift4@protonmail.com
Thank you

**Comment by nift4** [comment]
Download and install https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk to fix the crashing issue.

For further root cause debugging, please submit module installation log.

**Comment by helmutrocco13** [comment]
Thank you, it works now. However when i try to sign in, it tells me that i don't have a network connection, even though i have one.

**Comment by nift4** [comment]
Go to App Info of microG, then Network & internet and make sure Enable network access is enabled.

**Comment by nift4** [comment]
Stale.

**Comment by MagicRB** [comment]
I'm hitting this too, installing the apk as suggested fixes it. Can we reopen or do I create a new issue (I'll submit all the logs that are needed.)

**Comment by nift4** [comment]
The root cause is well understood, it just can't be fixed - https://nift4.org/2024/04/02/why-magisk-apk-bad/

**Comment by MagicRB** [comment]
Ah, sad that it's an issue, but thanks for you work anyway! it works great once I install manually.

P.S. the tldr should have been "it crashes" :)
