### ISSUE TITLE
Update GmsCore

### ISSUE THREAD

**Issue by pflanzenandi** [nift4/microg_installer_revived#12]
New version with android 11 compatibility. 

After this release every user should update microG - GmsCore via Fdroid independently. 
But an initial version with android 11 compatibility is required.

https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.13.203915

**Comment by nift4** [comment]
uhm, I did not use microG for long. what is the vtm version?

**Comment by nift4** [comment]
[microG_Installer_Revived.zip](https://github.com/nift4/microg_installer_revived/files/5416035/microG_Installer_Revived.zip)
normal, non-vtm version. if bootlooping, send /data/system/dropbox

**Comment by pflanzenandi** [comment]
Worked for me. No bootloop.
