### ISSUE TITLE
Com.android.vending stopped working

### ISSUE THREAD

**Issue by Turhvjbufv** [nift4/microg_installer_revived#122]
Installed the real play store but then I didn't want it anymore so I tried to uninstall it by flashing again the moudle, it's uninstalled, but it's always crashing, not in deny list
And it shows me this in application settings ![Screenshot_20240215-141546_Settings_1.png](https://github.com/nift4/microg_installer_revived/assets/91851160/5bfa2b58-4009-4adf-acc8-161cae76983b)

**Comment by nift4** [comment]
press uninstall updates button in three dots in app info

**Comment by nift4** [comment]
forgive me for saying this but your theme is terribly ugly lol

in that case go to storage, clear app data and reboot your phone

**Comment by nift4** [comment]
I use the default theme, font, icons, etc

**Comment by nift4** [comment]
There's real Play Store stuck somewhere on your phone, but I don't understand where... These symptoms all look like it's in DenyList (maybe you have Play Integrity Fix or something? It forces Play Store into DenyList)

**Comment by nift4** [comment]
try to disable it for now and see what happens

**Comment by nift4** [comment]
so after removing play integrity fix you still see play store like in the OP?

**Comment by nift4** [comment]
what other modules do you have?

**Comment by nift4** [comment]
can you open play store now?

**Comment by nift4** [comment]
Disable Shamiko, Magisk Hide, make sure Play Store still is not in denylist, then reboot.

**Comment by nift4** [comment]
stay with that one

**Comment by nift4** [comment]
i guess that setup is just ruined beyond measure... i recommend you to clean flash

**Comment by nift4** [comment]
Everything, whole ROM, and format data

**Comment by nift4** [comment]
Deleting all data

**Comment by RobertoWa** [comment]
u r using twrp? tried to delete whole content of vending + phonesky folders (app + data) before booting? clean dalvik cache?

**Comment by powellnorma** [comment]
Was able to remove the real play-store via:

```
cd /data/app
find . -name "*com.android.vending*"
rm -rf <whatever-above-command-found>
```
