### ISSUE TITLE
real play store error df-dferh-01 

### ISSUE THREAD

**Issue by Paradox98** [nift4/microg_installer_revived#124]
Hello, first of all thank you for your efforts, very good project, it saves me a lot of time.
I carefully looked through most of the issues and found no similar problems.

>mi 8 
lineageos 21  android 14
magisk 27 
lsposed 1.9.2 with FakeGapps 5.0 Check system framework
com.android.vending_39.6.25-31_0_PR_604467617-83962530_minAPI31(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk 
move to /data/adb/Phonesky.apk
flash microG Installer Revived 3.4.2-0
Normally it shows install real store.
Check all in the microg self-check.

After restarting, the Google play store was successfully displayed normally, and I successfully logged in to my account. Just when I thought everything was going well, Google Play could not obtain the application and reported an error `df-dferh-01`.

I also searched for the meaning of this error. It seems that gms is not working properly. Did I make a mistake somewhere?

**Comment by Paradox98** [comment]
[com.android.vending_2024-02-20T20_14_37.165.log](https://github.com/nift4/microg_installer_revived/files/14344153/com.android.vending_2024-02-20T20_14_37.165.log)

**Comment by nift4** [comment]
Have you tried removing all traces from Play Store and then using some older version?

**Comment by Paradox98** [comment]
I think so. I tried on crdroid and had the same problem. Tried multiple versions of google play. They all report error df-dferh-01. The above log may be caused by accident or misoperation. But df-dferh-01 is an ongoing problem.

> Have you tried removing all traces from Play Store and then using some older version?您是否尝试过从 Play 商店中删除所有痕迹，然后使用一些旧版本？

**Comment by nift4** [comment]
Can you enable "Allow Internet access" in App info > Internet & mobile data (wording may be different), is it already enabled, or do you not have the toggle at all?

**Comment by nift4** [comment]
Stale.

**Comment by Paradox98** [comment]
I tried to do it all over again. Still the same problem. I'm sure the network is open.

> Can you enable "Allow Internet access" in App info > Internet & mobile data (wording may be different), is it already enabled, or do you not have the toggle at all?

**Comment by nift4** [comment]
Do you have these toggles?

**Comment by Paradox98** [comment]
> Do you have these toggles?你有这些开关吗？


There are these switches, but they are all on.

**Comment by Paradox98** [comment]
![8c4aacae9861f950a4a0b3a41c6c914](https://github.com/nift4/microg_installer_revived/assets/61773822/d589095f-d391-401c-98cc-5545a43bea45)
![4014af43da36205440002b7af6c3c56](https://github.com/nift4/microg_installer_revived/assets/61773822/bce650fc-f377-44ca-86c2-52a827a7c4ab)

There is a problem with my local network and I need to enable VPN to access Google. I have enabled vpn.

**Comment by nift4** [comment]
does it work with vpn?

**Comment by Paradox98** [comment]
After I enable the VPN, the browser can access Google normally.

**Comment by Paradox98** [comment]
If you install gapps and use vpn, it can be used normally.

**Comment by nift4** [comment]
does microg itself work fine with vpn?

**Comment by Paradox98** [comment]
I think it's OK because I logged in successfully with my Google account.

**Comment by nift4** [comment]
Were you able to figure this out?

**Comment by Weissnix4711** [comment]
For anyone reading this in the future, the solution for me was to reinstall play/microg services from microg.org, make sure all microg permissions were granted (and showed in self check), then make sure devices registration was enabled after it had somehow disabled itself.

Still ain't got safetynet or PI to work, but that's another issue..

**Comment by 923132714** [comment]
I couldn't solve the problem in the end, so I installed google play services.
