### ISSUE TITLE
Companion keeps stopping

### ISSUE THREAD

**Issue by ppebb** [nift4/microg_installer_revived#125]
As far as I am aware I do not have any kind of denylist enabled. I had Universal SafetyNet Fix, but even when I disable it and reboot Microg companion still crashes.

Other modules include F-Droid Privileged Extension, Systemless Hosts, and Zygisk - LSPosed, and I am on Lineage OS 21.

**Comment by nift4** [comment]
Can you create a log file?

**Comment by ppebb** [comment]
Seemingly stopped crashing, and I have no clue why. Didn't make any changes or anything, but if the issue pops back up then I'll reopen with logs.
