### ISSUE TITLE
Installing with Kitsune Mask hangs the system

### ISSUE THREAD

**Issue by parasiteoflife** [nift4/microg_installer_revived#126]
Using either latest stable or pre-release of Kitsune if we install this module after rebooting, the system hangs. Either:

1. Phone loads and we can unlock the phone but that's about it, homescreen stays empty or even becomes black, accessing configuration works but then nothing else does as the system becomes more and more unresponsive
2. Phone hangs at the ROM logo and doesn't go past that

With stable point 2 happens, with pre-release point 1 happens.  
If then we flash official Magisk on top of Kitsune everything works again.

I'm using LOS 21, Android 14, Mi A3

**Comment by nift4** [comment]
Are you using SuList?

**Comment by nift4** [comment]
Can you try to reproduce the issue with SuList disabled first?

**Comment by nift4** [comment]
combining this with (now reopened) issue #90
