### ISSUE TITLE
Bag of problems [update broke GPS, can't go back previous version]

### ISSUE THREAD

**Issue by GutHib** [nift4/microg_installer_revived#127]
First of all - thanks for all the hard work you're putting into this project.

Unfortunately, I'm at the end of the second day of an update nightmare, and I can't see an end to it. I'm currently traveling, and after GPS got stuck in a place 100km from where I am for several days, I discovered that the recent update of MicroG installer broke GPS, because from verision 0.2.8 the way locations are handled were changed.

Last two days I've been wrestling to roll back the current version of MicroG installer to a previous version, but just can't get it done. The basic issue is with FakeStore, as during installation, FakeStore is only placed into priv-apps when I install the most recent version - when I install previous versions, it's not installed as a system app and so a lot of apps refuse to recognize it.

On the first day, my problem was that I would end up with version 0.3 of FakeStore even if I installed much older versions of MicroG installer. After trying about a dozen different version, now my system insists on version 0.1 of FakeStore no matter which version I install. That means that FakeStore doesn't crash anymore, but version 0.1 is also not recognized by many apps. I guess the root cause is that FakeStore isn't properly uninstalled in most cases, so when you uninstall and install a different version, you still end up with the FakeStore from the previous install (even though it *appears* to be uninstalled). Not sure if this is an issue with your module or with Magisk.

Installing the newest version still works, so I guess my choices are pretty much between broken GPS and broken FakeStore.

Inbetween I've tried all kind of other things, including installing MicroG manually and uninstalling FakeStore via adb. In the end, however, none of this led to a properly working install of MicroG 0.2.7 as I hadbefore the update.

Needless to say I'm utterly frustrated at this point. Mentally I should have given up hours ago, except that broken GPS can virtually get you killed in some situations, and I know that, if I simply ignore the problem now, it will come back to haunt me in the most unfortunate moment.

**Comment by nift4** [comment]
Hi,
can you try the following?
1. delete /data/adb/Phonesky.apk if present
2. uninstall module
3. reboot
4. delete microG and Companion or FakeStore if present
5. reboot
6. install old module

If you have multiple user profiles or work profiles, exercise special caution to uninstall microG and Companion or FakeStore from all of them.

**Comment by GutHib** [comment]
Hi,

Thanks for the quick response. YOur instructions are kinda unclear to me, though. What I tried:

#1 Nothing in /data/adb. Found Phonesky.apk in /data/adb/modules/microg_installer/system/priv-app/Phonesky/ and deleted it.

#2 For uninstall, it is unclear if I should push the deactivation switch or just hit uninstall (probably doesn't matter but who knows). In this case, I did both.

#3 do you mean delete or uninstall? Microg was still present after uninstalling the module, so I uninstalled. /data/adb/modules/ was completely empty.

#4 At the end, everything as "usual": Ended up with Fakestore 0.1 after installing Revived 3.3.1-0. What's weird is that Microg also shows as "updated" even though I uninstalled it above.

#5 BONUS round: Uninstalled the update first (it was Version 0.2.27 on top of version 0.2.27). Went through the whole process again (this time only "delete module" without deactivation switch). Same result (Microg showing as updated even though it didn't appear to be installed, and I'm still stuck with Fakestore 0.1.0. For what it's worth, on various occasions yesterday, Microg didn't show as updated, but Fakestore 0.1.0 remained).

Last night I also tried what was recommended in another issue ticket and uninstalled all other Magisk modules, but that didn't help. I also tried to install an older version (1.x) of the module once more, hoping that the uninstall would catch Fakestore 0.1 which I just can't seem to get rid of. Didn't work either, though.

Btw. microG spf (I never checked this before) is version 0.1.0 as well.

Btw. all of this is happening on a Samsung S5 Lineage 18.1 (without any Google apps, obviously).

**Comment by nift4** [comment]
3.3.1-0 installs microG 0.2.27 and FakeStore 0.1.0, while 3.3.2-0 installs microG 0.2.28 and FakeStore 0.2.0 - if you need FakeStore 0.2.0 you can install it as APK update manually by just installing the APK. Does that solve your issue?

**Comment by GutHib** [comment]
I don't "need" Fakestore 0.2.0 - I just need a Fakestore installation that actually works.

When I had 3.3.1 installed originally, everything worked fine. Now, with the combo of microG 0.2.27 and Fakestore 0.1.0, Fakestore isn't recognized by most apps, and reinstalling the apps doesn't help, either.

When I install 3.3.2 (or upgrade to 3.4.2 for the matter) I end up with Fakestore 0.1.0 anyway - that's why I'm starting to get confused which Fakestore is supposedly coming with which module version, as it seems irrelevant anyway.

Manual update to Companion 0.2.1 doesn't resolve the problem - a bunch of apps still complaining about Playstore missing.

**Comment by nift4** [comment]
All microG self test checks are passing? Is it complaining about Google Services in general or Play Store.

**Comment by nift4** [comment]
Android does not really support downgrades well. How is your signature spoofing set up if you are using LineageOS? The extremely recent ROM-side spoofing, or Xposed?

**Comment by GutHib** [comment]
Lsposed via Magisk module.

**Comment by nift4** [comment]
which xposed module exactly? thermatk or whew-inc FakeGapps?

**Comment by GutHib** [comment]
Zygisk

**Comment by nift4** [comment]
Uninstalling was a bit rash, I suppose. Is your Lineage build new enough for built in signature spoofing?

**Comment by GutHib** [comment]
Now this is weird - but weird in a very good way. After restoring the backup, I took a beeline to the downgrade: Uninstalled 3.4.2, rebooted, installed 3.3.2, rebooted. Nothing else, started no other apps, installed or deleted nothing else. Works like a charm now.

Have microG 0.2.7 now claiming it was upgraded, and Fakestore 0.1.0. Works like a charm (EDIT: I think I said that already).

I guess I must have taken a wrong bend somewhere fairly early in the process - something that changed some permission or screwed up something else in a way that it wasn't recoverable anymore.

So yes, the downgrade IS possible. Just make sure to follow the straight line, don't pick any berries on the way and for God's sake, don't stop to look at the flowers.

**Comment by nift4** [comment]
Great.
