### ISSUE TITLE
Issue on Android 14 

### ISSUE THREAD

**Issue by kod96** [nift4/microg_installer_revived#130]
Issue on android 14 following any method of update: app can't open, only seeing crash notification!

**Comment by nift4** [comment]
Please try the README suggestion in Common issues for this:
microG itself keeps crashing: [download](https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk) & install APK as update

Make sure to not uninstall or disable anything.

**Comment by nift4** [comment]
Interesting, no idea why that happens - glad it works though
