### ISSUE TITLE
androidx.multidex.MultiDexApplication keeps stopping

### ISSUE THREAD

**Issue by Master0ne** [nift4/microg_installer_revived#131]
After the upgrade to microG Installer Revived 3.4.3-0 the error message "androidx.multidex.MultiDexApplication keeps stopping" is shown after reboot and the microG app can not be accessed anymore (and it is not shown with its usual name in the app drawer, but as org.microg).

This is on crDroid 9.10 (Android 13).

**Comment by nift4** [comment]
Please try the README suggestion in Common issues for this:
microG itself keeps crashing: [download](https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk) & install APK as update

Make sure to not uninstall or disable anything.

**Comment by Master0ne** [comment]
> Please try the README suggestion in Common issues for this: microG itself keeps crashing: [download](https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk) & install APK as update

Yes, that solved the issue! Thanks for the fast response! :1st_place_medal:
