### ISSUE TITLE
False keeps crashing

### ISSUE THREAD

**Issue by Incomptus** [nift4/microg_installer_revived#132]
Hello!

Since i updated to 3.4.3 version i have regularly an message about "false keeps crashing".

The package is com.android.vending
I tried to uninstall then reinstall the module but the error still reappear...

On arrowos redmi note 8T

Thanks for your help

**Comment by nift4** [comment]
are you using real play store

**Comment by Incomptus** [comment]
> are you using real play store

No I don't use the real playstore

**Comment by nift4** [comment]
Can you try to download & install this APK (as update, don't uninstall anything) https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/Phonesky/Phonesky.apk

**Comment by Incomptus** [comment]
Hello, i tried but it says it can't be updated because it is conflicting with an existing package.

**Comment by rullydotcom** [comment]
i got this error right after the installation:

https://paste.crdroid.net/Ry9vvv

**Comment by nift4** [comment]
@rullydotcom have you tried this? https://github.com/nift4/microg_installer_revived/issues/131

**Comment by Incomptus** [comment]
> @rullydotcom have you tried this? https://github.com/nift4/microg_installer_revived/issues/131

Hi , so i udated the microg apk, now "false keeps crashing" issue seems to be solved but i will see with some times of using the phone if it reappears or not.

Thanks for your help bro

**Comment by nift4** [comment]
can you try to install Phonesky.apk using `adb install`? that should give detailed error message

**Comment by nift4** [comment]
any update?

**Comment by Incomptus** [comment]
> any update?

Hi, sorry my computer is currently dead lol but it will be back shortly, i hope tomorrow or after tomorrow 

Thanks bro

**Comment by nift4** [comment]
Let's reopen it when you have logs
