### ISSUE TITLE
Fake Play Store not being installed

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [nift4/microg_installer_revived#133]
On a Nuu A1+ (MT6580, Android 6.0 stock ROM, rooted with Magisk 27.0, original gms and play store uninstalled with UAD-NG), the "Play Store (Phonesky) installed" is not checked in the microG Self-Check after installing microG with this module.

**Comment by Lost-Entrepreneur439** [comment]
> https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/ad9297dca05053490860f1995d9c14b1828aa54b/src/core/sync.rs#L199
> 
> `pm` commands are not sufficient to debloat system apps if you plan to install another one with the same package name. I recommend you to use a systemful (not Magisk) and non-ADB debloater to delete the .apk files from the /system partition.

I tried finding a non-ADB debloater, but couldn't.

**Comment by nift4** [comment]
One simple example would be TWRP file manager, where you can delete the relevant APK files, but I'm sure there's more automated tools that do essentially the same thing.

**Comment by Lost-Entrepreneur439** [comment]
> One simple example would be TWRP file manager, where you can delete the relevant APK files, but I'm sure there's more automated tools that do essentially the same thing.

I don't know what the play store is in TWRP, and nothing in the file manager was called "play store" or "vending"

**Comment by nift4** [comment]
Phonesky maybe?
