### ISSUE TITLE
Cannot install companion

### ISSUE THREAD

**Issue by kkflto** [nift4/microg_installer_revived#134]
Magisk log:

- Copying zip to temp directory
- Installing microG_Installer_Revived.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
**************************
 microG Installer Revived 
 by nift4 
**************************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: CHANGELOG
  inflating: LICENSE
  inflating: README.md
  inflating: androidacy-config.json
  inflating: customize.sh
  inflating: module.prop
   creating: system/
   creating: system/app/
   creating: system/app/VollaNlpRRO/
  inflating: system/app/VollaNlpRRO/.replace
   creating: system/framework/
  inflating: system/framework/com.google.android.maps.jar
   creating: system/priv-app/
   creating: system/priv-app/GsfProxy/
  inflating: system/priv-app/GsfProxy/GsfProxy.apk
   creating: system/priv-app/Phonesky/
  inflating: system/priv-app/Phonesky/Phonesky.apk
   creating: system/priv-app/microG/
  inflating: system/priv-app/microG/microG.apk
   creating: system/priv-app/GmsCore/
  inflating: system/priv-app/GmsCore/.replace
   creating: system/etc/
   creating: system/etc/permissions/
  inflating: system/etc/permissions/privapp-permissions-org.microG.xml
  inflating: system/etc/permissions/com.google.android.maps.xml
   creating: system/etc/default-permissions/
  inflating: system/etc/default-permissions/permissions-com.google.android.gms.xml
   creating: system/etc/sysconfig/
  inflating: system/etc/sysconfig/org.microG.xml
   creating: system/product/
   creating: system/product/app/
   creating: system/product/app/VollaNlp/
  inflating: system/product/app/VollaNlp/.replace
   creating: system/product/app/VollaGSMNlp/
  inflating: system/product/app/VollaGSMNlp/.replace
   creating: system/product/overlay/
   creating: system/product/overlay/microGOverlay/
  inflating: system/product/overlay/microGOverlay/microGOverlay.apk
  inflating: uninstall.sh
- Real Play Store not found, installing Companion
Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 84022602 is older than current 84032830]
- Installing microG GmsCore
Error: Unable to open file: /data/adb/modules_update/microg_installer/system/priv-app/GmsCore/GmsCore.apk
Consider using a file under /data/local/tmp/
Error: Can't open file: /data/adb/modules_update/microg_installer/system/priv-app/GmsCore/GmsCore.apk

Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Error: Can't open file: /data/adb/modules_update/microg_installer/system/priv-app/GmsCore/GmsCore.apk
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:688)
	at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1557)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1523)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:236)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6462)
	at android.os.Binder.shellCommand(Binder.java:1097)
	at android.os.Binder.onTransact(Binder.java:914)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4403)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6446)
	at android.os.Binder.execTransactInternal(Binder.java:1363)
	at android.os.Binder.execTransact(Binder.java:1304)
- Done

**Comment by kkflto** [comment]
nevermind this issue, forgot to degoogle some apks, now It works.

**Comment by LeVraiRoiDHyrule** [comment]
> nevermind this issue, forgot to degoogle some apks, now It works.

Hi, can you tell which packages you forgot to remove ? I am having the exact same issue and can't find what package I forgot to remove. I searched everything called google or gms.

**Comment by kkflto** [comment]
Honestly, I don't remember which ones but search in  {system,system_ext}/priv-apps or /product/priv-apps.
