### ISSUE TITLE
Flashed while I had default play services installed.

### ISSUE THREAD

**Issue by Thetruejay20** [nift4/microg_installer_revived#135]
Accidentally flashed while I had default play services installed, and now Google Play store keeps crashing. How can I fix this issue?

**Comment by nift4** [comment]
I don't know. You will likely have to clean flash.

**Comment by Thetruejay20** [comment]
Yeah I was worried about that 😞.  I never read before flashing lol.

**Comment by Thetruejay20** [comment]
**Solved**
Uninstalled all magisk modules pertaining to this, used de-bloater app to uninstall play services, and play store, reboot, reboot again to recovery, and reflashed Gaaps. Everything works as it should. Now just using MicroG services app to deal with Revanced apps.
