### ISSUE TITLE
MicroG Services crash as KernelSU module

### ISSUE THREAD

**Issue by Optogram** [nift4/microg_installer_revived#137]
Hardware: Oneplus 7 Pro
Android version: 14
ROM : CrDroid 10.4
Are you in a special context or did you perform some particular tweaking ? : The ROM is now using KernelSU instead of Magisk

Description of my issue :

Hello, I'm not sure if it's the right place to discuss this issue since the module isn't officially supported by KernelSU. 

I can load the MicroG Revived module on KernelSU, but the last two releases (3.4.3 and 3.4.2) crashes and won't work. The MicroG Services app can't be load either and the icon in the app drawer isn't showing correctly.

The 3.4.1 release is working but the app won't register to the Google Cloud Messaging platform, so notifications won't appear.

What can I provide to help ?

Thanks for your work :)

**Comment by nift4** [comment]
Disable "Unmount modules" for microG app in new version

**Comment by Optogram** [comment]
Thanks for your answer :)

It seemed to work, at least one of the app is registered, I updated to the la test update through KernelSU and it doesn't crash now, but the app still doesn't have an icon in the app drawer and MicroG services doesn't exist in the system app list.

I dont know if it's solved, would you like me to close the issue ?

**Comment by nift4** [comment]
What is the la test update?

**Comment by Optogram** [comment]
* the latest update

Sorry, my foreign autocorrect does his job.

**Comment by nift4** [comment]
Can you uninstall microG or is there just a disable button?

**Comment by Optogram** [comment]
Hello,

I can uninstall. Since yesterday, I used it a few times and tried different ways.

* Installed an old version, then rooted microG app and updated to the last version with KernelSU
* Installed the last version directly then rooted microG app from KernelSU

On each case, the results are the same, the microG app works, but no icon in the app drawer and no app would register to Cloud Messaging. It's weird, because yesterday, one app only managed to register, but not since I tried the above steps.

**Comment by nift4** [comment]
I'm confused - why do you think it works if there is no app icon?

**Comment by Optogram** [comment]
Well, I can click on it and open MicroG settings.

![Screenshot_20240418-130800_androidx multidex MultiDexApplication_1](https://github.com/nift4/microg_installer_revived/assets/78688254/8e816297-7f56-49ec-8aaa-9bfbbf8807bf)

![Screenshot_20240418-130741_crDroid Home_1](https://github.com/nift4/microg_installer_revived/assets/78688254/0045db9f-fa09-45dd-93ea-cb2335b63e50)

**Comment by nift4** [comment]
Does the app have an icon in the settings menu?

**Comment by Optogram** [comment]
Hello,

Yes, it has.
I updated KernelSU today, to 0.9.3, and now my apps registered correctly and I receive notifications.
So it works, I will close the issue 👍
