### ISSUE TITLE
Microg not accepting permissions 

### ISSUE THREAD

**Issue by auvio323** [nift4/microg_installer_revived#138]
This is a duplicate of #119 , however,  I cannot reopen it and I also had not gotten a response fron my comment, so Ill post here.
Same exact issue. On android 14 and when using microg, I can only grant everything until Background Permission and SMS Permission. I do not have this issue on Microg Installer Revived v. 3.4.1 and lower, only v. 3.4.2 and higher. Im using FakeGapps Lsposed module. This issue has happened on all 3 of my devices using AOSP based roms (Xiaomi mi 9t pro, oneplus 9 pro, oneplus 11)

**Comment by nift4** [comment]
Did you check the common issue README entry for this: https://github.com/nift4/microg_installer_revived?tab=readme-ov-file#common-issues

can't grant background location and SMS permission: [download](https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk) & install APK as update

**Comment by auvio323** [comment]
Yes sorry, i had forgot to mention that when attempting that solution, my package installer crashes

**Comment by nift4** [comment]
Can you try to install it using `adb install` from a PC? That should give an detailed error message

**Comment by auvio323** [comment]
Performing adb install lets me grant "Permission to recieve text messages (SMS)", however, it does not let me grant "Permission to access location in the background". Installing MicroG installer Revived v3.4.1, rebooting, verifying all the permissions are set (Which they are), then updating / installing to MicroG installer revived v3.4.3 and not uninstalling MicroG installer revived v3.4.1 transfers all the granted permissions from v3.4.1 to v3.4.3 so I get all the granted permissions on it. However, while I do now have it working on the latest version, this behavior does not seem like it is supposed to happen.
I can replicate this on all of my Android devices that I own,
- Install A14 AOSP based rom (Not sure if this causes it but I've only tried it on devices using AOSP based rom)
- Root with Magisk
- Uninstall GMS if it is already installed on the device
- Install LSPosed, FakeGApps, enable FakeGApps
- Install MicroG Installer Revived v3.4.3 and find it has the issue described
- Uninstall MicroG Installer Revived v3.4.3, reboot, then install v.3.4.1, reboot, and find it grants all the permissions.

**Comment by nift4** [comment]
Are you sure you can grant SMS but not background location? Is this reproducible?

**Comment by auvio323** [comment]
Hello,
Upon some further testing, I was able to get the APK install method to work by installing the MicroG APK and allowing all permissions **before** installing the Magisk module. I would recommend adding this to the README
However, I am not sure if this needs to be an issue in the first place as upon reverting commit [68c1bd1](https://github.com/nift4/microg_installer_revived/commit/68c1bd1a16a997bcf896eee769ac5f33bda78add) and rezipping it seems to fix the issue for me. It is described as a workaround for ColorOS, and on my OxygenOS(ColorOS) device, including this commit makes the microG settings app crash immediately upon launching it, which is a worse issue than what happens on AOSP (not being able to grant permissions). It is Fixable by either reverting the commit or installing the APK before installing the Magisk Module, same as before. Also, the upgrading method that I described previously does not work on my OxyenOS device, and it continues to crash on launch when attempting that fix.

I also read #104 where it was said how GmsCore.apk was installed in /my_bigball, however on my device it was not installed there, and GmsCore.apk was found in both /my_heytap/priv-app and /product/priv-app, which I removed using Systemless Debloater. I also never experienced the issue of MicroG not being discovered by the OS like described.  

Regarding reproducibility, this same issue happens accross all of my Android Devices (OnePlus 9 Pro 5G running crDroid A13 and A14, Xiaomi Mi 9t Pro running Evolution X A13 with GApps removed systemful, HTC One m8 running LineageOS 19.1, OnePlus 11 running Nameless AOSP with GApps removed systemful and crDroid, and OnePlus 11 running OxygenOS 14 with GApps removed systemlessly, with most of the same issues described which happened in AOSP, with the additional crashing issue and the upgrading method not working which I have described)

I am not sure if [68c1bd1](https://github.com/nift4/microg_installer_revived/commit/68c1bd1a16a997bcf896eee769ac5f33bda78add) needs to be reverted or not since it supposedly fixed the issue for the person who opened the issue. Perhaps there are differences between our devices or the GApps were removed differently.

I am not sure how anyone else hasn't said much about this issue since it happens with every rooted Android device I own. Does this occur on your device?

While I could leave it at this and the method of installing MicroG apk before installing the Magisk Module could be added to the README, I am concerned since under my testing I haven't experienced anything beneficial resulting from that commit. If you have free time, you could test reproducing the issue.

Also, lastly I appreciate your development in this and I find this project very useful. I know this is a lot to read lol, I wanted to get my points across with all of my testing- and I really appreciate your time in this.

**Comment by nift4** [comment]
The HTC and OP9 Pro 5G did not have any gapps built into the ROM, right?

**Comment by auvio323** [comment]
Yes, correct.

**Comment by HXLH50K** [comment]
> Yes sorry, i had forgot to mention that when attempting that solution, my package installer crashes

I faced the same problem, and I use Lucky Patcher to install the apk, it works.

**Comment by nift4** [comment]
@auvio323 can you try to ungrant location and then re-grant it with background allowed?

**Comment by nift4** [comment]
I just happened to reproduce that exact bug - I had to press on location, it gave me a warning dialog about how microG is a location provider, I pressed on the button that takes you to location settings, then I just went back to microG self test and was able to grant it ¯\_(ツ)_/¯

**Comment by CircuitSerialKiller** [comment]
For anyone else running into this issue with background location permissions, please see here for an alternate solution that worked for me by editing the runtime permissions xml file:
https://github.com/microg/GmsCore/issues/1440#issuecomment-902846916
