### ISSUE TITLE
Apps somehow detect Play Store is not "authentic"

### ISSUE THREAD

**Issue by powellnorma** [nift4/microg_installer_revived#141]
I installed the "real Playstore", extracted "Phonesky.apk" from [NikGapps-T](https://sourceforge.net/projects/nikgapps/files/Releases/NikGapps-T/20-Apr-2024/). Now [YASNAC](https://github.com/RikkaW/YASNAC) says "The version of the Google Play services installed on this device is not authentic." - Before it passed. Any ideas? Thank you.

**Comment by nift4** [comment]
Does microG self test pass?

**Comment by powellnorma** [comment]
Yes, everything is checked, including:

```
Play Services (GmsCore) installed: Yes
Play Services (GmsCore) has correct signature: Yes
Play Store (Phonesky) installed: Yes
Play Store (Phonesky) has correct signature: Yes
Services Framework (GSF) installed: Yes
```

**Comment by powellnorma** [comment]
Fixed it by re-installing YASNAC from Play Store - see https://github.com/RikkaW/YASNAC/issues/24
