### ISSUE TITLE
Play integrity API error -17

### ISSUE THREAD

**Issue by pedroborraz** [nift4/microg_installer_revived#143]
I don't know if it's an installer bug or a microg bug, but I can't get past the Google API check.
By default the rom is already certified using a Gapps package.
I still tried with the zygisk next and PIF modules, but apparently the test breaks.
_My banking app for some reason also doesn't validate with microg_
**Real PlayStore from Nikgapps-U**
**Microg version: 0.3.1.24**  
**OS: Crdroid A14**
**Device: Redmi Note 12 4G (tapas)**
**KernelSU**
<img src="https://github.com/nift4/microg_installer_revived/assets/83194874/5cb46dc5-f9d4-47a0-94fd-90c40f9ef41a" width="248">
<img src="https://github.com/nift4/microg_installer_revived/assets/83194874/ab1c3ff0-daaa-4909-b9b3-748ffbb1f96c" width="248">

**Comment by nift4** [comment]
microG doesn't support Play Integrity atm, afaik
