### ISSUE TITLE
Install works as Magisk module but upon reboot the microg app says "not registered" and cannot be opened

### ISSUE THREAD

**Issue by BirdChair** [nift4/microg_installer_revived#146]
This was working fine for a while then I decided to update everything and now its fucked, ill nuke my phone and restart but wanted to see if anyone else has had this problem or has a solution first.

**Comment by BirdChair** [comment]
Also, just opened fakegapps and com.google.android.gms is named:

"No messaged received so far"

**Comment by nift4** [comment]
Did you update your phone's OS?

**Comment by shvchk** [comment]
Same problem after upgrading to [3.4.4-0](https://github.com/nift4/microg_installer_revived/releases/tag/v3.4.4-0). LOS 21, May 28. [3.4.3-0](https://github.com/nift4/microg_installer_revived/releases/tag/v3.4.3-0) worked fine.

**Comment by nift4** [comment]
try to [download](https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk) & install APK as update, which will clear resource cache (unrelated to normal cache) for microg

**Comment by shvchk** [comment]
That worked, thanks @nift4 🎉

The only problem now is that I can't grant permissions to access location in the background and receive SMS for microG in Work profile (app in the regular profile works fine).

**Comment by nift4** [comment]
you can install the same apk in work profile as well and that'll be fixed as well, ironically it fixes 90% of issues

**Comment by BirdChair** [comment]
Ok first of all sorry for the lazy issue report. Second, installing the .apk worked. Thanks a lot.

**Comment by shvchk** [comment]
@nift4 thanks! I assumed installation in regular profile would also install it and clear resource cache in the work profile as well. App in the work profile does get updated, but it seems that resource cache is not cleared.

For anyone wondering how to manually install app in the work profile, see [Install APK in Work Profile via ADB in Android](https://stackoverflow.com/questions/56951666/install-apk-in-work-profile-via-adb-in-android)
