### ISSUE TITLE
Login function goes wrong after upgrading module

### ISSUE THREAD

**Issue by 769812215** [nift4/microg_installer_revived#147]
I upgraded magisk module from 3.2.0 to 3.4.0(latest), but google apps become unable to login, including google photos, google voice and play store, is that my own problem or a bug? And i tried downgrade the module only to find it impossible, thanks.

**Comment by 769812215** [comment]
Sorry, that's version  3.4.4

**Comment by nift4** [comment]
does the self check still have all boxes ticked?

**Comment by 769812215** [comment]
> does the self check still have all boxes ticked?

yes sir, now I managed to login but after a few days, google apps(photos, play store as i have tested) will crash after half a second

**Comment by 769812215** [comment]
> does the self check still have all boxes ticked?

Now i install microG apk again(with out uninstalling previous, same verion) and everything works well temporarily, but i guess after some days it will goes wrong again

**Comment by nift4** [comment]
let me know if it breaks
