### ISSUE TITLE
Has to manually install Phonesky.apk to get the self-check option checked; and possible location/SMS permission issues.

### ISSUE THREAD

**Issue by wezfaas** [nift4/microg_installer_revived#148]
Magisk 27.0, latest LSPosed & FakeGapps
SELinux is permissive
Android 13 (API 33)

I'm not sure if manually install Phonesky.apk is intended because it's not mentioned in readme.  What are the major impacts if the phonesky self-check options is not enabled in microG?

When checking location permission on microG through App Info, Location permission is allowed, but it falls into "Allowed only while in use", whereas 'Find device' is in the "Allowed all the time" category.  I wonder if that's the reason why I cannot enable the location self-checks.  I wonder if I can do the adb to grant the all-time permission?

Also SMS permission does not register to Allowed.
Logcat (while granting the permission in GUI):
`06-07 15:17:27.880  3881  4578 D TelephonyProvider: Using old permission behavior for telephony provider compat
06-07 15:18:16.656  2665  3021 D MIUIInput: [MotionEvent] publisher action=0x0, 1909401, channel '8cffa09 com.android.permissioncontroller/com.android.permissioncontroller.permission.ui.ManagePermissionsActivity (server)'
06-07 15:18:16.668  2665  3021 D MIUIInput: [MotionEvent] publisher action=0x1, 1909416, channel '8cffa09 com.android.permissioncontroller/com.android.permissioncontroller.permission.ui.ManagePermissionsActivity (server)'
06-07 15:18:16.780 17592 17592 V AppPermissionViewModel: AppPermission fragment viewed with sessionId=8068112128971033754 uid=10222 packageName=com.google.android.gmspermGroupName=android.permission-group.SMS
06-07 15:18:18.549  2665  3021 D MIUIInput: [MotionEvent] publisher action=0x0, 1911297, channel '8cffa09 com.android.permissioncontroller/com.android.permissioncontroller.permission.ui.ManagePermissionsActivity (server)'
06-07 15:18:18.644  2665  3021 D MIUIInput: [MotionEvent] publisher action=0x1, 1911393, channel '8cffa09 com.android.permissioncontroller/com.android.permissioncontroller.permission.ui.ManagePermissionsActivity (server)'
06-07 15:18:20.633  2665  3021 D MIUIInput: [KeyEvent] publisher action:0x0,  keyCode:4 , 1913369,channel '8cffa09 com.android.permissioncontroller/com.android.permissioncontroller.permission.ui.ManagePermissionsActivity (server)'
06-07 15:18:20.637 17592 17592 D MIUIInput: [KeyEvent] ViewRootImpl windowName 'com.android.permissioncontroller/com.android.permissioncontroller.permission.ui.ManagePermissionsActivity', KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=1913369000000, downTime=1913369000000, deviceId=-1, source=0x101, displayId=0 }, phoneEventTime=15:18:20.620
06-07 15:18:20.734  2665  3021 D MIUIInput: [KeyEvent] publisher action:0x1,  keyCode:4 , 1913474,channel '8cffa09 com.android.permissioncontroller/com.android.permissioncontroller.permission.ui.ManagePermissionsActivity (server)'
06-07 15:18:20.738 17592 17592 D MIUIInput: [KeyEvent] ViewRootImpl windowName 'com.android.permissioncontroller/com.android.permissioncontroller.permission.ui.ManagePermissionsActivity', KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=1913474000000, downTime=1913369000000, deviceId=-1, source=0x101, displayId=0 }, phoneEventTime=15:18:20.725
06-07 15:18:22.530  2665  6101 D PerfShielderService: com.android.permissioncontroller|com.android.permissioncontroller/com.android.permissioncontroller.permission.ui.ManagePermissionsActivity|562|1914104459268|200|3|19`

**Comment by wezfaas** [comment]
Wondering if the background permission is missing here (badging from microG.apk):
` uses-feature: name='android.hardware.location'
  uses-implied-feature: name='android.hardware.location' reason='requested android.permission.ACCESS_COARSE_LOCATION permission, requested android.permission.ACCESS_FINE_LOCATION permission, and requested android.permission.INSTALL_LOCATION_PROVIDER permission'`

**Comment by nift4** [comment]
Did you see these entries of "common issues":
- can't grant background location and SMS permission: [download](https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk) & install APK as update
- can grant SMS permission but can't grant background location: go to App Info > Permissions > Location > (press "Location access" in the warning dialog), then go back to self test and try to grant background location again - it should now work

**Comment by wezfaas** [comment]
Yes, I have already tried, actually before my post.  Sorry I didn't mention that I'm also facing [Unable to install microg over itself as a user update - App gets removed after reboot #123](https://github.com/nift4/microg_installer_revived/issues/123) .

Both solutions don't work in my case.

I have used this [post](https://xdaforums.com/t/app-microg-gmscore-lightweight-free-software-clone-of-google-play-services.3217616/post-83151045) as a reference for the fix.  Unfortunately after I get all permissions on, I still can't get google map to work, I want to use that map as a test.  @nift4 , could you give me some pointer for that?

**Comment by nift4** [comment]
What's wrong with google maps?

**Comment by nift4** [comment]
closing because stale, comment again if u need more help
