### ISSUE TITLE
Installed microG module doesn't work since Magisk 21.2

### ISSUE THREAD

**Issue by McGerbick** [nift4/microg_installer_revived#15]
### Environment
- Device: Motorola Moto G4 (athene)
- OS: LineageOS 14.1 (by eric_lev)
- Magisk 21.2, 21.3, or 21.4
- Magisk Manager 8.0.4 or 8.0.7
- microG Installer Revived 1.9.0-0 or 1.10.0-0

### Problem
Since Magisk version 21.2, the microG environment installed by "microG Installer Revived" cannot be used anymore. There's no microG icon in the apps overview and the microG services don't seem to be running, although Magisk Manager displays the module as being installed.

### Workaround
Downgrade to Magisk 21.1 by installing it via Recovery (here: TWRP). Then everything seems to be fine.

**Comment by nift4** [comment]
Does App Info display the app as installed?

**Comment by McGerbick** [comment]
Just tested it again with Magisk 21.4: No, the Apps section of the android settings does not show the "microG Services Core" entry either.

After being on Magisk 21.4 and returning to 21.1 it is like microG has been freshly installed, since all settings are gone (need to go through the settings in the self-check).

I've attached the log coming from Magisk 21.4. Maybe this can give an additional hint.
[magisk_log_2021-02-14T171337Z.log](https://github.com/nift4/microg_installer_revived/files/5978120/magisk_log_2021-02-14T171337Z.log)

**Comment by nift4** [comment]
Nothing helpful in there. Can you use Root to check if /system/priv-app contains GmsCore, Phonesky or other microG apps?

**Comment by McGerbick** [comment]
When comparing the priv-app directory listings using Magisk 21.1 and 21.4, the following directories are actually missing with 21.4:
```
DroidGuard
GmsCore
GsfProxy
Phonesky
```

Could there be a general problem with Magisk 21.2 to 21.4 in my environment (not really related to the microG module)? However, I could not see anything relevant on a quick browse through [the current issues list of Magisk](https://github.com/topjohnwu/Magisk/issues?q=is:issue+is:open).

**Comment by nift4** [comment]
Well, even the hardcoded (never copied around, modified or similar) /system/priv-app/DroidGuard app isn't present. This looks like an Magisk bug.

**Comment by v1993** [comment]
Can confirm this issue happening on Magisk 22: apps are not present in priv-app either. I think Magisk devs would be happy to accept issue if you've managed to create a minimal reproducible example showing this problem.

**Comment by nift4** [comment]
I see, I will try to create something to reproduce this.

**Comment by nift4** [comment]
Can please anyone create an Magisk bug report? I am too busy to investigate

**Comment by akaessens** [comment]
## [v23.0](https://topjohnwu.github.io/Magisk/changes.html#v230) 
    [App] Fix a bug in the stub app that causes APK installation to fail

Looks like it is solved now

**Comment by McGerbick** [comment]
Thanks for the hint, @akaessens.

I can confirm that v23.0 of Magisk is running the microG module correctly now.
