### ISSUE TITLE
Installing real play store other apps do not recognise play store

### ISSUE THREAD

**Issue by Weissnix4711** [nift4/microg_installer_revived#150]
I installed the real play store, as per the instructions. It clearly worked, and I can open the real play store just fine. Testing safetynet from withing the microg companion app works too, but other safetynet/play integrity apps do not recognise play store is even installed.

Play store is not in denylist. I have tried with and without play integrity fix in magisk, neither works.

Any ideas?

**Comment by Weissnix4711** [comment]
After removing every trace of Phonesky/microg and reinstalling (using the magisk microg revived installer), I now get the same error as #124 when opening the play store. Again, microg reports everything's fine, but no other apps can use safetynet or PI.

**Comment by nift4** [comment]
Can you enable "Allow Internet access" in App info > Internet & mobile data (wording may be different), is it already enabled, or do you not have the toggle at all?

**Comment by Weissnix4711** [comment]
Cheers for the reply. There is "allow network access", which is enabled for both play store and play (microg) services. Unrestricted data usage was disabled for play store, just enabled it and it made no difference.

**Comment by watisdit21** [comment]
> Can you enable "Allow Internet access" in App info > Internet & mobile data (wording may be different), is it already enabled, or do you not have the toggle at all?




Hello, same issue here. Latest lineage QPQR3. I have latest play store installed but I can't test play integrity. I've attached screenshot. 
![jy1sc9w6lq9p8hk58b07bAsfd74m3szqmAm5b1wwrzwtx56zpt5y7Av0lm9n12zAvfcAsnx7pqnyckp9m0xch7c2q1qc081b01zpp4pdh1kAq2c7g2d1pzjfgwk50rb70nnhv9m2mjrs7h2l80365t8wkrlAzdjy0c6l7jk40sc2s9zhqrt1](https://github.com/nift4/microg_installer_revived/assets/151390242/fcd4c2fb-7eac-473f-bfc3-5a249596c889)

**Comment by nift4** [comment]
are you both using play integrity checker to test that? because microg afaik doesn't support play integrity atm

**Comment by Weissnix4711** [comment]
Yes. Well, I have tried multiple of these Safetynet / PI checkers. Note that safetynet (which is for certain supported) doesn't work either on any of these apps (but _does_ from within microg companion).

From what little I know about google's shenanigans, I think play integrity is somehow handled by the play store, not by play services / microg, so microg + real play store should at least allow the PI api to be usable by apps (even if it doesn't pass). [This](https://github.com/microg/GmsCore/issues/1771#issuecomment-1672982750) seems to support that

**Comment by nift4** [comment]
is self check all ticked?

**Comment by Weissnix4711** [comment]
yup

**Comment by Weissnix4711** [comment]
Just ran a factory reset, and in this order:

- Installed magisk canary apk (then changed to debug). I already had the patched boot image flashed, as factory reset wouldn't change that.
- Copied Play store 41.5.29-29 to /data/adb/Phonesky.apk https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-41-5-29-release/google-play-store-41-5-29-29-0-pr-644500286-3-android-apk-download
- This module, latest version v3.4.4-0 installed via magisk. It did say installing real play store.
- Reboot
- Verify play store was in fact installed.
- Go to microg self test, hit everything to give it permissions. Weirdly background location and SMS wasn't popping up the dialog so those remain unselected.
- Install neo store, from neo store install aurora store, from aurora store install various PI checkers (Integrity Check, YASNAC, Simple Play Integrity Checker)
- Give play store all permissions in settings
- Reboot again
- Try all the PI/safetynet checkers, none of them work. They all say play store app not found.

**Comment by Weissnix4711** [comment]
Got it to work, finally. The safetynet / PI checker apps must be installed via google play (or at least think they were). If using aurora store, you cannot use the session based installer. Root works. I guess other methods might also work, but session for sure doesn't, as app info shows "Installed from Aurora Store".
