### ISSUE TITLE
Problems with the grant of permissions and data reset

### ISSUE THREAD

**Issue by eXellenz** [nift4/microg_installer_revived#151]
i try install _microG Installer Revived 3.4.4-0_ on Xperia 1 IV with Magisk. Android 14.
after reboot i cant grant RECEIVE_SMS and ACCESS_BACKGROUND_LOCATION permissions. all other functionality is working.
if i try install com.google.android.gms.apk like user app,  then RECEIVE_SMS and ACCESS_BACKGROUND_LOCATION permissions is granted, location recieve working fine in apps, but after reboot my phone got one more reboot and all microg data (like account, permissions, etc...) reseting (like #123).
if i try using _npem_ (from nanodroid) in termux all permissions is granted, but after reboot microg data reseting like writing upper.

**Comment by eXellenz** [comment]
attach npem (add txt extension)
[npem.txt](https://github.com/user-attachments/files/16191151/npem.txt)

**Comment by nift4** [comment]
your stock rom has gapps, right?

**Comment by eXellenz** [comment]
gapps uninstalled with _adb uninstall_
and gapps cache remove with _sd made 2_

**Comment by nift4** [comment]
well thats why, adb uninstall is not a proper way to remove it. get rid of the apk files in the system or product folders

**Comment by eXellenz** [comment]
gapps is removed. plz reopen issue.
![image](https://github.com/user-attachments/assets/7f2614cf-217a-44de-a5eb-9190e1f10a89)
![image](https://github.com/user-attachments/assets/669766a3-2bd9-4eea-b734-be741bf93e9b)
![image](https://github.com/user-attachments/assets/10c30e10-7d33-4850-80a3-afd35fe7576a)
![image](https://github.com/user-attachments/assets/5b3213e2-0ff4-49ca-ae58-c674fe52e8c3)
![image](https://github.com/user-attachments/assets/78aa8a0c-ca2a-4591-a639-d8e2e1b3fe57)
![image](https://github.com/user-attachments/assets/85627ff5-348e-463d-b0cc-d20843228afe)

**Comment by eXellenz** [comment]
i remember. the gapps (GMS and GSF) were removed earlier with SD Made 2, they were restored when I tried to reinstall the microg magisk module. therefore, yes, the problem is as relevant as it was at the time of opening the issue.

**Comment by ahmetmaruferdogan** [comment]
I don't know why it does that but I found a workaround and it worked for me.
It suggests kinda same thing as what you did but when I followed one by one then it worked like a charm. Here is the comment:
https://github.com/microg/GmsCore/issues/1280#issuecomment-817019067

**Comment by nift4** [comment]
closing this because its the same issue as #123
