### ISSUE TITLE
microg service keeping stop

### ISSUE THREAD

**Issue by aw59** [nift4/microg_installer_revived#152]
system：lineage20 android 13 userdebug

if i use installer 3.4.1, which contains the microg 0.3.0,  the service won't keeping stop, but when i wanna login, it shows that i havent connect network, although all of the permissions were given.

i updated to installer 3.4.4, and after i reboot, the microg service keeping stop. i have read other closed issues, and i didn't use shamiko or something similar.

(sry for my poor English)

**Comment by nift4** [comment]
have you tried enabling network access in internet setting in app info?

**Comment by aw59** [comment]
> have you tried enabling network access in internet setting in app info?

yes, all of the permissions are given

**Comment by aw59** [comment]
it seems caused by my system. I changed my system to cherish, android 14, problems disappeared.

I gonna close this issue.
