### ISSUE TITLE
Your device isn't certified to run Google apps or use Google services. Contact the device manufacturer or retailer and ask for a certified device. Learn more

### ISSUE THREAD

**Issue by bphd** [nift4/microg_installer_revived#156]

**Comment by nift4** [comment]
insufficient description, sorry. i need more details if you still have this issue

**Comment by bphd** [comment]
@nift4 That's literally all is being written, otherwise no run

**Comment by bphd** [comment]
Installed that and tried to launch YouTube and theres that. Samsung. A14. Custom. Rooted. Yeah ReVanced. There were other issues but I forgot meanwhile, probably not solved, only workarounded by doing differently. Worked before MGIV, still not working

**Comment by nift4** [comment]
How are you installing ReVanced, rootless or rooted? which custom ROM? which device?

**Comment by bphd** [comment]
Rooted, Matrixx

**Comment by nift4** [comment]
You can try to:
1. Change "Device Profile" in microG settings, turn switch for registration off and then on again
2. Install some device fingerprint changing tool
3. https://www.xda-developers.com/how-to-fix-device-not-certified-by-google-error/

**Comment by bphd** [comment]
Unmounting ReVanced patches makes the application behave normally (and it does so with or without MGIR), so I'm a bit lost at what MGIR gives more. But anyway that's not the solution as an application without ReVanced isn't much use. This issue should be pursued in reVancedTeam/reVanced
