### ISSUE TITLE
Unable to grant permissions for "access location in the background" and "receive text messages (SMS)"

### ISSUE THREAD

**Issue by Master0ne** [nift4/microg_installer_revived#16]
With latest ArrowOS 11 with Magisk Canary on a POCO X3 NFC and microG Installer Revived, I am unable to grant these two required permissions in microG Self-Check:

- Permission to access location in the background
- Permission to receive text messages (SMS)

When clicking on these two, nothing happens.

When trying to set permissions in app settings:

- for the Location permission it does not even show the "Allow all the time" option
- for the SMS permission changing it from "Deny" to "Allow" does not stick (I can click "Allow", but if I go back, microG Services Core is still under "Denied" and if clicking on microG Services Core again the SMS permission is on "Deny" again).

These problems do not occur when installing the microG components from the microG repo in F-Droid.

**Comment by nift4** [comment]
Can you give logs? Did you try the workaround mentioned at the microG issues?

**Comment by nift4** [comment]
https://github.com/microg/GmsCore/issues/1099#issuecomment-666566285 and below

**Comment by Master0ne** [comment]
@nift4 Sorry, no logs, already moved on to installing the required microG components through F-Droid using the F-Droid Privileged Extension Magisk Module.

I did play around with `runtime-permission.xml` and it made the "Allow all the time" option appear for the Location permission, but it nevertheless didn't work and I gave up on it prematurely.

I'm going to close this issue because I can not help analyze it any further, so nothing more to do unless someone else should stumble over the same issue.

**Comment by Izaic** [comment]
This is an issue again on the latest installer, however the previous one from February does not have this issue.

**Comment by nift4** [comment]
oof, i'll try to push a fix in the next update

**Comment by Izaic** [comment]
https://github.com/rumplestilzken/unihertz_titan_lineageos20

https://github.com/rumplestilzken/unihertz_titan_lineageos20/releases/download/v1.1/lineage-20.0-20230419-UNOFFICIAL-gargoyle_slim_bvN.img.tar.gz
