### ISSUE TITLE
4.0.1 fails to install on Moto Edge 2024.

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [nift4/microg_installer_revived#161]
3.4.4 works fine, but starting with the new release, it fails to install. I've attached a photo of the error.

I uninstalled GApps with a root terminal, and I have the FakeGApps module for LSPosed. ![Screenshot_20240906-140229_Magisk.png](https://github.com/user-attachments/assets/8da2e869-91d6-452e-a1e4-9716f4fe22c7)

**Comment by nift4** [comment]
Is that upgrade or fresh install?

**Comment by nift4** [comment]
Have you followed the install instructions, https://github.com/nift4/microg_installer_revived?tab=readme-ov-file#installation

Especially the "Install microG 0.3.2 and Companion (or real Play Store) as normal user app" ?

**Comment by Jabraco** [comment]
yes. both microg and companion are (were, in case of upgrade) installed as normal user app

**Comment by nift4** [comment]
can you please run `adb shell pm dump-package com.google.android.gms ">" /sdcard/log.txt` and upload log.txt here? thanks alot :)

**Comment by artield** [comment]
I am having the same problem with exactly the same answer. I have tried everything.

**Comment by nift4** [comment]
@artield can you please also run `adb shell pm dump-package com.google.android.gms ">" /sdcard/log.txt` and upload log.txt from phone internal storage here? it'll help me fix the issue

**Comment by Jabraco** [comment]
> can you please run `adb shell pm dump-package com.google.android.gms ">" /sdcard/log.txt` and upload log.txt from phone internal storage here? thanks alot :)

``cmd: Failure calling service package: Failed transaction (2147483646)``

that's it. that's all it says

**Comment by nift4** [comment]
can you try just using: adb shell pm dump-package com.google.android.gms > log.txt
that'll create the log on your host

**Comment by Jabraco** [comment]
log.txt:

``Unknown command: dump-package``

**Comment by nift4** [comment]
what android version are you on?

**Comment by nift4** [comment]
Sorry about that, released a hotfix. https://github.com/nift4/microg_installer_revived/releases/tag/v4.0.2-0
just let me know if there are any more issues

**Comment by Lost-Entrepreneur439** [comment]
> Sorry about that, released a hotfix. https://github.com/nift4/microg_installer_revived/releases/tag/v4.0.2-0 just let me know if there are any more issues

i'm sorry, but this new approach with pre-installing it as a user app then converting it isn't the right way to approach the deleting bug. some roms (including the stock rom on my moto) have a bug that when you try to install microG Gmscore, even after Play Services has been completely uninstalled, it'll still say it conflicts with another package and refuse to install, the only way to get  around this is installing 3.4.4, then reinstall microG as a user app, but then even after installing 4.x, it still deletes on reboot.

**Comment by nift4** [comment]
> some roms (including the stock rom on my moto) have a bug that when you try to install microG Gmscore, even after Play Services has been completely uninstalled, it'll still say it conflicts with another package and refuse to install

That's the thing: this isn't a bug and causing many of the issues people have reported in the issue tracker!

It just means the original Google Play Services were not removed properly (common debloater tools using ADB do it wrong for the purposes of replacing them with something else).

**Comment by Lost-Entrepreneur439** [comment]
> > some roms (including the stock rom on my moto) have a bug that when you try to install microG Gmscore, even after Play Services has been completely uninstalled, it'll still say it conflicts with another package and refuse to install
> 
> That's the thing: this isn't a bug and causing many of the issues people have reported in the issue tracker!
> 
> It just means the original Google Play Services were not removed properly (common debloater tools using ADB do it wrong for the purposes of replacing them with something else).

here's the thing -- it was done properly, full uninstall via a root ADB shell (pm uninstall com.google.android.gms), not a user-based uninstall like UAD-ng does, it is a bug in the ROM, the package is completely gone. As far as I know, pm uninstall in a root terminal is how to properly fully uninstall a system app.

**Comment by nift4** [comment]
Nope it's not!! it just hides it from the system, but the only proper way to do it is to delete the .apk file from the privilegied partitions

**Comment by Jabraco** [comment]
i've located the system gmscore.apk at

product/priv-app/GmsCore

i'm unable to delete the "GmsCore" folder from the product partition however. using twrp

**Comment by nift4** [comment]
> i'm unable to delete the "GmsCore" folder from the product partition however

> As far as I know, it can't be removed from the file system, later Android versions don't let you mount /system as rw iirc

That is indeed a problem, and the solution is Magisk. I'm not sure if there is any Magisk-based debloater modules as I don't use any, but for the sake of proving my point (:P) here's a simple one I made just now (does not support KernelSU, only Magisk):
[gms_delete.zip](https://github.com/user-attachments/files/16912134/gms_delete.zip)

To use:
1. Remove any microG related stuff including my installer
2. Install gms_delete.zip
3. Reboot
4. Make sure to uninstall GMS user app using `pm uninstall`
5. Now `pm dump com.google.android.gms` should say that package doesn't exist
6. Install microG as user APK
7. Install my installer
8. Reboot

That should work. Although untested, the module itself is very, very simple, so I don't see why it would not work.

**Comment by Lost-Entrepreneur439** [comment]
> > i'm unable to delete the "GmsCore" folder from the product partition however
> 
> > As far as I know, it can't be removed from the file system, later Android versions don't let you mount /system as rw iirc
> 
> That is indeed a problem, and the solution is Magisk. I'm not sure if there is any Magisk-based debloater modules as I don't use any, but for the sake of proving my point (:P) here's a simple one I made just now (does not support KernelSU, only Magisk):
> [gms_delete.zip](https://github.com/user-attachments/files/16912134/gms_delete.zip)
> 
> To use:
> 1. Remove any microG related stuff including my installer
> 2. Install gms_delete.zip
> 3. Reboot
> 4. Make sure to uninstall GMS user app using `pm uninstall`
> 5. Now `pm dump com.google.android.gms` should say that package doesn't exist
> 6. Install microG as user APK
> 7. Install my installer
> 8. Reboot
> 
> That should work. Although untested, the module itself is very, very simple, so I don't see why it would not work.

Nope, still the same "conflicts with existing package" error.

**Comment by nift4** [comment]
please give me `adb install microg.apk` output and also check with `ls /product/priv-app/GmsCore/ /product/priv-app/Phonesky/` if apk files are present

**Comment by Lost-Entrepreneur439** [comment]
i'm not going to continue, this is my main phone and i just need something that works, maybe youll find someone else to help with this, for now i'm staying with the version that actually works (3.4.4)

**Comment by Jabraco** [comment]
```XQ-DQ54:/ $ ls /product/priv-app/GmsCore/ /product/priv-app/Phonesky/
/product/priv-app/GmsCore:

/product/priv-app/Phonesky:
```

```
adb install microg.apk 
Performing Streamed Install
adb: failed to install microg.apk: Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.google.android.gms attempting to redeclare permission com.google.android.googleapps.permission.GOOGLE_AUTH.writely already owned by com.google.android.gsf]
```

@nift4

**Comment by nift4** [comment]
@Jabraco try this instead
[gms_delete.zip](https://github.com/user-attachments/files/16912362/gms_delete.zip)

> edit: passing thought: if your gms_delete script works, why not include it in base installer?

Let m explain:
I need the microG APKs to be on the privilegied partitions, the GMS apks not being there, and microG being installed as user app. If I install microG as user app before or after putting the APKs in place doesn't actually matter. 3.x series used to first install it during Magisk module install, that however closes Magisk Manager (for kind of complicated reasons, but it can't be avoided). Magisk Manager just being force stopped during install is kind of bad UX and caused a LOT of confusion. That adb install also usually didn't work if there were any traces of GMS left. The next option I opted for was installing microG after the module. That however caused major confusion regarding unintuitive crashes and microG uninstalling itself, which was traced back to this module even though it actually is just because there are traces of GMS. There were so many users affected I decided to go for the third option, making sure the state is okay before installing the module. That has the disadvantage that I of course can't remove the traces as part of the module because I need it to be done during install but I can't remove them during install due to the Magisk Manager "crash"/closing bug.

**Comment by Jabraco** [comment]
- installed new gms_delete.zip

- installed newest microg apk via adb:

```
~ % adb install microg.apk                  
Performing Streamed Install
Success
```

(probably would work via ui, too)

- rebooted

- microg settings still there after reboot!
 - no "androidx.multidex.MultiDexApplication keeps stopping"
 - no google GMS reinstalled
 - ``product/priv-app/GmsCore`` empty
 
i think this fixes the issue

**Comment by nift4** [comment]
@Jabraco the "self-deleting" is rather interesting for me, microg stays before installing microg_installer_revived but after installing it, it disappears after each reboot and you need to reinstall it?

can you send me `adb shell pm dump com.google.android.gms > log.txt` logs
1. after having just flashed the magisk module and rebooted
2. after it was uninstalled and you installing microg apk

thanks a lot

**Comment by Jabraco** [comment]
> @Jabraco the "self-deleting" is rather interesting for me, microg stays before installing microg_installer_revived but after installing it, it disappears after each reboot and you need to reinstall it?

yes. before installing this module = fine, stays on reboot. afterwards, microg.apk gets uninstalled.

> can you send me adb shell pm dump com.google.android.gms > log.txt logs

do you have an email i can send this too. the logs contain personal info i'd rather not on the open web

**Comment by nift4** [comment]
sure: nift4@protonmail.com

**Comment by Jabraco** [comment]
sent

**Comment by nift4** [comment]
@Lost-Entrepreneur439 https://github.com/nift4/microg_installer_revived/releases/tag/v4.1.0-0

**Comment by Lost-Entrepreneur439** [comment]
> @Lost-Entrepreneur439 https://github.com/nift4/microg_installer_revived/releases/tag/v4.1.0-0

nope, with that one i can at least install microG and the module, but after installing the module, microG vanishes and I keep getting the message "co.g.App keeps stopping".

**Comment by nift4** [comment]
did you perhaps delete the gms uninstaller again? or did you keep it installed (which I recommend)?

can you please send a log of the crash (eg using `adb logcat -dbcrash`)?

**Comment by Lost-Entrepreneur439** [comment]
> did you perhaps delete the gms uninstaller again? or did you keep it installed (which I recommend)?
> 
> can you please send a log of the crash (eg using `adb logcat -dbcrash`)?

I did keep it installed. I never got a log and I can't be bothered to reinstall it again, although just like with 3.x, it only seemed to happen when PIF was installed.

**Comment by nift4** [comment]
well, if you (or someone else in this thread) still has issues and is willing to debug, you know where to find me ;)

**Comment by Uosx09** [comment]
> well, if you (or someone else in this thread) still has issues and is willing to debug, you know where to find me ;)

Not sure if i should make a new issue for this, since im using a different device (sm-g900f) and im facing issues with the play store installation mainly (and lil weird issue with microg services app that is now fixed which ill mention too), these issues were with the old 3.4.4 version however im 100% sure its mainly android version related for some reason because on older versions (tested with android 7 or older) those issues are gone (even with the latest 45.2.xx of the Playstore from a week ago).

Sorry if i sound stupid here but by debugging you mean sending logs files and testing use cases? if that is the case i got you (tho gonna need some instructions if specific stuff are required), have a good one!

**Comment by Uosx09** [comment]
@nift4 Everything is on the new issue i just opened cheers!

**Comment by offbeat-stuff** [comment]
was able to install the new version by adding
```bash
$> cat customize.sh 
REPLACE="
/system/product/priv-app/GmsCore
/system/product/priv-app/Phonesky
/system_ext/priv-app/GoogleServicesFramework
"
```
to gms_delete.zip

**Comment by nift4** [comment]
@offbeat-stuff did you use ksu instead of magisk

**Comment by offbeat-stuff** [comment]
yes
