### ISSUE TITLE
Upgrade from v3.4.4.-0 to v4.0.2-0 fails

### ISSUE THREAD

**Issue by Master0ne** [nift4/microg_installer_revived#163]
![microG](https://github.com/user-attachments/assets/734c199c-c919-4874-8b23-6ad321dd0866)

**Comment by nift4** [comment]
To fix it, the only thing you need to do is to install microG Companion / Play Store APK like you would install any app.

**Comment by Master0ne** [comment]
> To fix it, the only thing you need to do is to install microG Companion / Play Store APK like you would install any app.

Excellent, I have added the microG repo to F-Droid, upgraded microG Companion to the latest version, and then the Magisk module upgrade was successful.

**Comment by ronidee** [comment]
For me, this isn't possible. When trying to install tha newer version of the companion app, it fails due to different signing keys.
![Screenshot_20240912-172258_Droid-ify](https://github.com/user-attachments/assets/7e9a5267-0bc2-4169-9203-13410a926b50)

By "play store apk", are you referring to the original one or to fake store?

Thanks in advance:)

**Comment by nift4** [comment]
Hi, this probably means you improperly debloated APKs before installing this module

**Comment by ronidee** [comment]
How would I have done that? I only remember installing apks directly from the original Github Repo or installing your Magisk module.
And, perhaps more importantly, how can I fix it? Do I have to completely uninstall microG? Or only companion app or Magisk module?
Thanks in advance!

**Comment by nift4** [comment]
@ronidee I meant that you had original Google services installed and did not delete all of them. If you were using gms_delete.zip, please redownload and try the new version (I silently swapped out the link :P)

**Comment by ronidee** [comment]
No, I can assure you with 100% certainty, that I have never installed the original, proprietary GSF from Google on my device 😁.
I installed LineageOS 21 (Android 14) on my device, without flashing GApps. I haven't used gms_delete.zip either.

Any other ideas on how to get around the issue or what could be causing it?

**Comment by nift4** [comment]
Hi, can you try to run `pm uninstall com.google.android.gms` in that case? It should fix that issue
