### ISSUE TITLE
Can't retrieve Integrity status verdict when MGIR is activated 

### ISSUE THREAD

**Issue by bphd** [nift4/microg_installer_revived#165]
But when deactivated I can retrieve it

**Comment by nift4** [comment]
As I said before, I can't support Play Integrity because I never used or investigated Play Integrity.

**Comment by bphd** [comment]
So your module is deemed incompatible with Play Integrity?

**Comment by nift4** [comment]
it might be possible to get working, I just don't know how

**Comment by bphd** [comment]
I'm really lost. All I get is error -12, can't get token. Can't get nonce before even getting it verified for authenticity

**Comment by nift4** [comment]
Closing this because #157 is about the same issue
