### ISSUE TITLE
Microg is not installed (Android 10)

### ISSUE THREAD

**Issue by Jennifer2005x** [nift4/microg_installer_revived#168]
I put the gms_delete module and apparently it was erased, but microg did not install, rebooted and did not work

before this I tried to delete gms with this app: https://github.com/sunilpaulmathew/De-Bloater

and if it works, but the module (microg installer revived) does not put microg or play store as a system app

**Comment by Uosx09** [comment]
Looks like you got the same issue i had, already mentioned it in #167 along side a few other PS issues, gotta wait for more instructions from nift, feel free to check the issue details cheers!

**Comment by Jennifer2005x** [comment]
> > I put the gms_delete module and apparently it was erased, but microg did not install
> 
> You
> 
> 1. installed gms_delete.zip
> 2. rebooted
> 3. install microg + companion(or play store) apk
> 4. install this module
> 5. reboot again
>    ?

I did, but microg can't be installed

**Comment by Jennifer2005x** [comment]
> so you had issue in step 3 or where exactly?

Yeah, step 3

**Comment by nift4** [comment]
can you try installing the APK using `adb install` and copy the exact error here?

**Comment by Jennifer2005x** [comment]
> can you try installing the APK using `adb install` and copy the exact error here?

adb: failed to install /home/jenny/Documents/com.google.android.gms-240913004.apk: Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.google.android.gms attempting to redeclare permission com.google.android.googleapps.permission.GOOGLE_AUTH.writely already owned by com.google.android.gsf]

**Comment by Uosx009** [comment]
if you do have xposed or lsposed installed, download core patch (if you are using android 9+) from fdroid or droid-ify, activate it then reboot, installing the apk should work regardless then

if it doesnt work or you dont have xposed in your system ya might wanna

remove gms_delete.zip from magisk directly
remove the microg magisk module from magisk directly too
reboot
uninstall microg services app (it should still be there as a user app) and look in your app manager in settings for com.android.vending (if its still exist with ttry to uninstall it, use adb shell commands or something like titanium backup or system app remove (root) NOT the debloater app, same thing for gms app if its still there)
reboot again
install microg services apk then fake store or play store (whichever you prefer)
install microg zip with magisk
reboot again
i dont think you should face any issues if youve done it this way (except the staying as user apps bug i mentioned in the issue i opened yesterday, in which case you should just stick to the v3.4.4 for a stable microg until all issues with the v4.x+ are fixed

**Comment by nift4** [comment]
@Jennifer2005x can you please email me (nift4@protonmail.com) the output of `pm dump com.google.android.gsf` in the error state where you can't install the gms apk?

**Comment by Jennifer2005x** [comment]
Fixed, only the framework folder had to be added with phonesky and gmscore
![overview_image_178472625_0_1](https://github.com/user-attachments/assets/30f86ff0-01ea-43cf-be03-c5c3db953eb8)

**Comment by nift4** [comment]
[gms_delete.zip](https://github.com/user-attachments/files/16999114/gms_delete.zip)
Will add this to the download page instead
