### ISSUE TITLE
List of nonworking apps

### ISSUE THREAD

**Issue by bphd** [nift4/microg_installer_revived#169]
/e/OS MicroG has a known list of things that their implementation is unable to communicate with right. https://community.e.foundation/t/list-apps-that-work-or-do-not-work-with-microg/21151

Does your implementation have such list?

**Comment by nift4** [comment]
> Does your implementation have such list?

No, and I don't plan to make one. Supporting people here on GitHub is already very time intensive, I don't have time nor motivation for such extras.

**Comment by bphd** [comment]
> > Does your implementation have such list?
> 
> No, and I don't plan to make one. Supporting people here on GitHub is already very time intensive, I don't have time nor motivation for such extras.

Do you know at least how much differ your implementation from others? Because if it's the same, maybe the list would be the same wihtout seraching for

**Comment by Uosx09** [comment]
> > > > dont think there is any official list mentioned anywhere, this is pretty much a test and find out implementation as far as i know, however it should be similar to that list above or might support even more stuff then it, if you do have specific apps in mind i can try to download and run them and let ya know the results cheers!
> > > 
> > > 
> > > Thanks! For now my concern is upon WhatsApp, if you can tell
> > 
> > 
> > its fully supported as long as you install microg properly (stick to v3.4.4 for now), with the google drive backup function too (i have prolly reinstalled my whatsapp like 70 times+ with no issues related to microg whatsoever again as long as its properly installed)
> > im about to post an update post in my own issue #167 feel free to follow it
> 
> I'm on 4100. I don't really know if it's installed right but I can't get integrity (-12 error) and I'm flagged on WhatsApp so it won't let me as long as everything is not in order, and I guess that integrity is among the criterias
> 
> I'm not sure but I think WhatsApp let pass pretty much everything until you're flagged, and that's here where the real test begin, to know if MicroG is acutally compatible

the play integrity fix if you are using the magisk module v17.4 uninstall it and microg app should work again however if you want the module the v17.3 is still working well with v3.4.4 microg

as for Whatsapp idk what do you mean by flagged exactly but the closest thing i had to that was a in-app notification telling me i shouldnt use custom roms which i safely ignored and restored my account like usual and my device is not certified either as i had whatsapp fully working with both safety net and play integrity passed/working and not

**Comment by bphd** [comment]
> > Do you know at least how much differ your implementation from others?
> 
> Well, it's pretty simple really. The only significant difference is that Magisk could trip root detection that /e/OS without root would not trip.

So it's not the microG implementation that is different, and considering I'm using KSU, I can expect it to be identical experience as /e/OS
