### ISSUE TITLE
Welp, the issue vanished

### ISSUE THREAD

**Issue by bphd** [nift4/microg_installer_revived#170]
https://github.com/nift4/microg_installer_revived/issues/167

**Comment by nift4** [comment]
The OP of that issue triggered some rate limit and got banned from GitHub for spam. Wasn't me who did that.

Rip OP.

**Comment by bphd** [comment]
> The OP of that issue triggered some rate limit and got banned from GitHub for spam. Wasn't me who did that.
> 
> Rip OP.

How did he even achieved that fr, GitHub is the last place where such bot trigger happens lol. Not only him, even the issue got wiped, gosh

**Comment by Uosx009** [comment]
@bphd back again will be in #173
