### ISSUE TITLE
Repost - Play Store (android 10+) & Microg Issues 

### ISSUE THREAD

**Issue by Uosx009** [nift4/microg_installer_revived#173]
### Context

First let me provide some context on how my microg installation look like, i basically used a mixture of the [guide here](https://xdaforums.com/t/how-to-install-microg-on-unsupported-roms.4540957/) for the magisk/lsposed/xposed steps and the [old read.me](https://github.com/nift4/microg_installer_revived?tab=readme-ov-file#how-do-i-get-the-real-play-store) on the github page (when 3.4.4 was still the latest version) for info about troubleshooting and the PS installation.

1. This my very first time sharing my input directly to a developer, apologies in advance if i say something stupid or offending.

2. The reason i mentioned these issues happen on android 10+ is because i had all of them while i was trying out different custom roms for my current daily driver (which is sm-g900f), i started with android 14 till android 10 which i settled with, even though its the same device but i assume these issues exists for other ones because i had them on all the android versions mentioned earlier. 

3. The microg services app itself works flawlessly in every install/use case (will talk about the weird interaction i had later on).

4. The PS apk versions i used were 42.2.28, 42.3.28, 42.4.22, 42.4.25, 42.5.16, and 42.6.22 and as mentioned in the your read.me post they are [unbundled apks from apkmirror](https://www.apkmirror.com/apk/google-inc/google-play-store/variant-%7B%22minapi_slug%22%3A%22minapi-29%22%7D/) when installing the real store (by placing them in /data/adb before flashing), and i faced the issues described with every single one of them since i was moving to the newest one on each update.

5. I currently have Microg installed and working with no issues on the following devices: SM-G310HN (android 4.4.2), SM-G900F (android 10), SM-G935F (android 14), SM-T210 (android 4.4.2), and SM-P3110 (android 7), each of them are running their respective most stable custom roms with the [cleanest install possible](https://xdaforums.com/t/rom-official-lineageos-16-x-all-variants.3850840/page-41#post-78635977) (The process worked for the other devices too).

6. I have the latest available magisk (stable v27 and v21.4) & [lsposed](https://github.com/mywalkb/LSPosed_mod/releases) & [xposed-magisk](https://xdaforums.com/t/2019-5-1-magisk-systemless-xposed-v89-3-v90-2-beta3-sdk-21-27.3388268/) properly installed and fully working.

7. The fake gapps apk was installed and activated properly as instructed before installing the microg module.

8. On my current device i installed [this kernel](https://xdaforums.com/t/tuned-kernel-for-n-o-p-q-20201021-full-charging-no-flickering-correct-ma-values.3893954/), i flashed it before magisk to avoid any issues.

### Microg 3.4.4

With all that being said lets dive into the PS issues, ill first explain the installation/post installation ones by describing each case in detail:

1. Fake store only: Without adding any PS apk in /data/adb, then install the magisk module which installs the companion app by default, then reboot then try to install the play store apk and it crash (Google Play Store stopped working) when i try to open it (gave it all permissions before opening, and also clearing data and cache of both the companion app before installing the play store and after installing it with no results).

2. With real store (PS installed but still crashes): I add a PS apk in /data/adb, then install the magisk module which installs the PS this time as a system app (from what i can tell at least), then reboot, the play store app crashes (Google Play Store stopped working) when trying to open it (in this case too i gave it all permissions before opening, as well as clearing it data and cache but no luck).

Wordaround/Fix (for the 2nd case only which is my current one): Open the app info of the play store then uninstall updates (from the 3 dots on the top right corner) > Force Close the app > Go to permissions and give it Storage permission only > Open the PS app (should open normally now however you cant install any app it will give you an error) > leave the app > install the same apk you copied to /data/adb (it must be the same version) > reopen the PS app (installing apps should work now without any error).

As for the issues after a reboot, there was only one tbh which is that the PS keeps crashing before even opening it up and afterwards too, to fix it simply uninstall the updates then reinstall the same apk version and it should work again without any issue, this must be repeated after every reboot though which can be lil annoying.

### Microg 4.0.2

Since these versions came out literally like 2 days ago, i didnt have to do much tinkering around with them nor did they let me, on the get go i couldnt even update to them because the playstore was still installed as a system app, and instead of playing around i decided to remove the microg module 3.4.4 itself and reboot before installing the new update (tried directly 4.0.2).

After reading a bit about the new process i grabbed a fresh apk of the latest microg version as well as the fakestore/companion apk (and i already had the PS apks), the installation and post installation results were ironically exactly the same even the workaround/fix was still needed to be done the very same way for the PS to work properly (open and be able to install apps)

As for the process itself here is how i did it: Installed the Microg and Fake Store (Case 1 - fail) / Play Store ( - success with workaround) apps like any normal user app > Flashed the 4.0.2.zip > reboot > did the workaround to fix PS.

Here is where that weird Microg encounter happen, after like 3-4 reboots the Microg Services app itself just kept crashing when i try to open it so i kinda panicked and removed > reboot > reinstalled it but the issue persisted so i removed microg altogether again and went to the issues page and found the recent comments on issue #161 where you shared a gms removal zip, i followed the mini steps post you sent to someone there and it worked again, had like 3-5 more reboots after the issue was long gone thankfully.

### Microg 4.1.0

This should be the latest version released today, and sadly i had an issue with this one too XD, so i tried updating it through magisk directly which went without any issue, however after rebooting, the PS app for whatever reason was no longer a system app (it was converted to a normal app again) and was spam crashing before i even unlock the phone screen.

I think i have an idea of the culprit here this time, its the gms removal zip, while having that module installed, for v3.4.4 (even after removing microg > reboot > reinstall) the PS app ALWAYS stays as a normal app and crashes, and also having the gms removal installed as a module breaks the workaround/fix i mentioned above and it no longer fix the PS app (it cant even open).

I have not tried to reinstall v4.1.0 without the gms removal zip because i wanted to wait till you read about the issues i have above first incase i did something wrong installation wise or messed up on my end somewhere, for now i reverted back to 3.4.4 with the workaround till another notice.

And yes it did come into my mind that all of this might be me approaching PS installation the wrong way by going for the latest versions, for that youll have to excuse me because i had my fair share of old apks hunting when i was testing (downloading & installing) every single version of some other apps (brave, keyboards, dialers and so on) for the other devices that i mentioned above and it was a living hell tbh.

On top of that the 42.5.16 is still working properly on the SM-P3110 so ill respectfully pass on the play store, also these issues might be device specific only or due to me not following installation steps properly in which case please do point it out.

Thank you very much for your work and your time hopefully you find this helpful, let me know if any more info is needed!

**Comment by Uosx009** [comment]
### Status update - Interesting results

### Rom update

Since i know talking about this is quite off topic so this will be the last time ill mention it apologies in advance, although CrDroid (with android 10) is actually be the fastest and smoothest rom for the device but its certainly not the most stable one not even decently stable, the speed kinda covers how unstable the rom is which did trick me too. Microg wise after your suggestion failed i ended up re-clean installing the rom again and it still failed even in it bare bones state, so i decided to try again LineageOS roms (android 10, 11, 12, 13, and 14) and i had no luck in neither of them.

Ill just point this out as im completely certain after all the testing ive done over the past 3 months, the roms themselves are not the issue nor are they bad or unusable, its just the memory management (after adding your personal apps and data on the phone) is just horrible on android 12, 13, and 14, with android 10 being the best and android 11 being 2nd best, but that is to be expected for how old the device is, Microg wise it was working properly on all the roms with no exception (v3.4.4 that is).

As for what im using right now and will be using till i get a better phone is [RR 8.7.3](https://xdaforums.com/t/rom-official-10-resurrection-remix-q-8-7-3-galaxy-s5-lte.4147267/) with the [Adreno Drivers here](https://xdaforums.com/t/rom-official-10-resurrection-remix-q-8-7-3-galaxy-s5-lte.4147267/page-20#post-86120307) to fix rom related glitches, this was the last rom on my list to test/use mainly due to all the criticism i seen on reddit and xda comments from other devices using this Rom series, however for sm-g900f its all lies the memory management is insanely good, not like fastest like CrDroid but very close but its stable AF, you can actually feel how well built of a rom it is. 

### Microg update

Ngl nothing much changed over here, yesterday i decided to retest every case possible, so i grabbed a fresh copy of all the files related to microg (Fake gapps apk, microg services apk, fake store apk, microg zips v3.4.4 & 4.0.2 & 4.1.0), of course this is all after setting up the rom and installing magisk and lsposed properly, apart from the play store which i will talk about below in a separate part, microg worked and was installed a system app and did not disappear or get uninstalled only with v3.4.4 and v.4.0.2.

The v4.1.0 is just a hot mess sorry XD, yesterday i thought that it functionality was still intact even if microg was still a user app but it wasn't the case, apps kept giving me that google play services is required to run notification and i couldn't add my google account at all so yeah pretty sure this is the part where you might need some actual logs so just lmk what should i do if needed.

### Play Store update

This might seem like it no big deal on the surface but its an actual break through for me although i prolly was just dumb not even notice or test it, anyhow i managed to have a properly working play store like post microg zip install though there is a bit of a small process to ensure it wont give any issues, its easier and straight forward with 3.4.4 but with 4.0.2 you need to do the workaround i mentioned in my post above sadly (for working install function only tho, the play store does open with no issues).

Before the process first and most importantly i found out that the issues were because of the apk version but not the way you would think let me explain why, in apkmirror and specifically for the play store app the apk files are split into 3 major versions, one for [android 6+](https://www.apkmirror.com/apk/google-inc/google-play-store/variant-%7B%22minapi_slug%22%3A%22minapi-23%22%7D/), one for [android 10+](https://www.apkmirror.com/apk/google-inc/google-play-store/variant-%7B%22minapi_slug%22%3A%22minapi-29%22%7D/), and one for [android 12+](https://www.apkmirror.com/apk/google-inc/google-play-store/variant-%7B%22minapi_slug%22%3A%22minapi-31%22%7D/), you can prolly see where im going with this.

In all my previous tests i only used either android 10+ or 12+ apks for roms with android 10-14, so yesterday i thought why not just try the android 6+ apk (latest version 42.6.22) and IT FKING WORKED like a charm, i literally re-flashed the rom and microg like 4 times after just to make sure i wasnt tripping so its safe to say that the correct apk part is fixed.

But this also means that if and when the play store apks no longer support android 6+ (in other words gets discontinued), the latest version then would be the last issue free working version with microg, unless something can be done coding wise with the other versions which i do hope there is tbh.

Now lets talk about the installation process of the play store, ill explain it for each microg version that it worked with separately, and keep in mind in both cases the rom was still in bare bones state and i only installed microg

For v3.4.4: renamed the play store apk to Phonesky.apk then placed it in /data/adb > flashed the v3.4.4 zip in magisk > reboot > dont open the app go to app info and give it Storage permission only > if you open it now and check for app updates you will see a something went wrong error to fix it close the app > go to app info and remove storage permission and give it to it again > reopen the app and now it should be working perfectly. The app survived multiple reboots without the workaround with the install function intact.

For v4.0.2: installed microg services apk then play store apk (android 6+ version ofc) > flashed the v4.0.2 zip in magisk > reboot > workaround to fix PS, then it worked until you reboot then youll have to do the followup to the workaround to fix the play store again. This should be repeated after each reboot too (pretty much like the android 10+ and 12+ apks case).

That should be pretty much it, since i already set up the device i can now retest with microg 4.1.0 and provide logs if needed (unless the android 6+ apk somehow works this time XD), also sorry for the very lengthy post time zones are looking like a big issue too in our interactions as i mentioned before so i tried to put everything in one post (as i will do in the future) since i pretty much got to wait almost a whole day before seeing your replies (which i do not mind as long as you dont).

Thank you again for your time ill be waiting for your reply

**Comment by Uosx009** [comment]
@nift4 im here again XD

**Comment by bphd** [comment]
> @nift4 im here again XD
> 
> only reason i can think of was sending that md5 signature as a screenshot from apkmirror, also i legit didnt notice or realize you were talking about me and my issue being gone for almost an hour IMAOOO

Edit rather than multi-posting, we don't want you gone another time

so those MD5?

**Comment by Uosx009** [comment]
> > @nift4 im here again XD
> > only reason i can think of was sending that md5 signature as a screenshot from apkmirror, also i legit didnt notice or realize you were talking about me and my issue being gone for almost an hour IMAOOO
> 
> Edit rather than multi-posting, we don't want you gone another time
> 
> so those MD5?
> 
> screenshot making ban an account, why? And I want the MD5 of the actual APK you have locally, not the latest one the website has

i just reposted the issue itself and the big update post, i aint sending anymore pics or even try to upload anything, anyhow is what youve asked for, its from the PS version i got installed rn (42.6.22 A6+ ver)

md5: cde9f6208d672b54b1dacc0b7029f5eb
SHA1: 38918a453d07199354f8b19af05ec6562ced5788
SHA256: f0fd6c5b410f25cb25c3b53346c8972fae30f8ee7411df910480ad6b2d60db83

**Comment by nift4** [comment]
i'll be getting back to you soon

**Comment by Uosx009** [comment]
> i'll be getting back to you soon

Take your time ill be around

**Comment by bphd** [comment]
> > > @nift4 im here again XD
> > > only reason i can think of was sending that md5 signature as a screenshot from apkmirror, also i legit didnt notice or realize you were talking about me and my issue being gone for almost an hour IMAOOO
> > 
> > 
> > Edit rather than multi-posting, we don't want you gone another time
> > so those MD5?
> > screenshot making ban an account, why? And I want the MD5 of the actual APK you have locally, not the latest one the website has
> 
> i just reposted the issue itself and the big update post, i aint sending anymore pics or even try to upload anything, anyhow is what youve asked for, its from the PS version i got installed rn (42.6.22 A6+ ver)
> 
> md5: cde9f6208d672b54b1dacc0b7029f5eb SHA1: 38918a453d07199354f8b19af05ec6562ced5788 SHA256: f0fd6c5b410f25cb25c3b53346c8972fae30f8ee7411df910480ad6b2d60db83
> 
> even if signatures dont match just download and install the [42.6.22 A6+ unbundled apk](https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-42-6-22-release/google-play-store-42-6-22-23-0-pr-670642294-4-android-apk-download/) from APKMirror, and follow the process of v3.4.4 i wrote on the interesting updates comment and you should be fully set, hopefully it all work out for ya one way or another
> 
> ill be asleep for now so i cant reply to anything on the spot, i should up in like 7-11 hours from now and hopefully catch yall online too, have a good one in advance cheers!

The apk I used that hasn't resolved me anything is

> Google Play Store_42.6.22-23 [0] [PR] 670642294_APKPure.apk
> d749ba87f8f05b5bba4f39fde7bed0d2

The one I get from your link (https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-42-6-22-release/google-play-store-42-6-22-23-0-pr-670642294-4-android-apk-download/download/?key=2ed190832f6e383b1a10d615f7dd00c9a7116f5e&forcebaseapk=true) is

> com.android.vending_42.6.22-23_0_PR_670642294-84262200_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk
> d749ba87f8f05b5bba4f39fde7bed0d2

Literally the same

And the one from your post is 

> cde9f6208d672b54b1dacc0b7029f5eb

But idk how you managed to get it

**Comment by Uosx009** [comment]
> > > > @nift4 im here again XD
> > > > only reason i can think of was sending that md5 signature as a screenshot from apkmirror, also i legit didnt notice or realize you were talking about me and my issue being gone for almost an hour IMAOOO
> > > 
> > > 
> > > Edit rather than multi-posting, we don't want you gone another time
> > > so those MD5?
> > > screenshot making ban an account, why? And I want the MD5 of the actual APK you have locally, not the latest one the website has
> > 
> > 
> > i just reposted the issue itself and the big update post, i aint sending anymore pics or even try to upload anything, anyhow is what youve asked for, its from the PS version i got installed rn (42.6.22 A6+ ver)
> > md5: cde9f6208d672b54b1dacc0b7029f5eb SHA1: 38918a453d07199354f8b19af05ec6562ced5788 SHA256: f0fd6c5b410f25cb25c3b53346c8972fae30f8ee7411df910480ad6b2d60db83
> > even if signatures dont match just download and install the [42.6.22 A6+ unbundled apk](https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-42-6-22-release/google-play-store-42-6-22-23-0-pr-670642294-4-android-apk-download/) from APKMirror, and follow the process of v3.4.4 i wrote on the interesting updates comment and you should be fully set, hopefully it all work out for ya one way or another
> > ill be asleep for now so i cant reply to anything on the spot, i should up in like 7-11 hours from now and hopefully catch yall online too, have a good one in advance cheers!
> 
> The apk I used that hasn't resolved me anything is
> 
> > Google Play Store_42.6.22-23 [0] [PR] 670642294_APKPure.apk
> > d749ba87f8f05b5bba4f39fde7bed0d2
> 
> The one I get from your link (https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-42-6-22-release/google-play-store-42-6-22-23-0-pr-670642294-4-android-apk-download/download/?key=2ed190832f6e383b1a10d615f7dd00c9a7116f5e&forcebaseapk=true) is
> 
> > com.android.vending_42.6.22-23_0_PR_670642294-84262200_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk
> > d749ba87f8f05b5bba4f39fde7bed0d2
> 
> Literally the same
> 
> And the one from your post is
> 
> > cde9f6208d672b54b1dacc0b7029f5eb
> 
> But idk how you managed to get it
> 
> Researches online says that it's a certificate for many google apps, google signing key, rather than a md5sum of the said apk

Idk how useful or relevant this information may be but i forgot to mention it in the updates post, after installing microg v3.4.4 module, yes the play store was working however when i opened it app info i could uninstall updates from the 3 dots on the top corner like something was changed (this is just me assuming things but im pretty sure the app itself was not supposed to change in any way other then becoming a system app, and i had those changes before even opening it the first time)

about the apk i used the one from apkmirror from the very same link i sent so idk why it didnt work for ya, but since im using nova launcher i can save the actual apk from my device (i got a few backup apps that can do the same too) and upload it somewhere if you want to download and try it out just lmk if needed

im not quite sure how i got the different md5sum value, i used an app from droid-ify called Checkey which is an ancient app i found in a brave search that you can check your md5sum, sha1 sha256 values with for your installed apps.

**Comment by bphd** [comment]
WhatApp would be okay with pretty much anything you'll do as long as your number isn't flagged. If it is, then it switch to high security parameter where it only let you if you're clear from root (integrity and few checks). People say that it's mainly about unlocked bootloader and that it's resolved with a lock spoofing, but even doing that, mine is not happy

**Comment by Uosx009** [comment]
> WhatApp would be okay with pretty much anything you'll do as long as your number isn't flagged. If it is, then it switch to high security parameter where it only let you if you're clear from root (integrity and few checks). People say that it's mainly about unlocked bootloader and that it's resolved with a lock spoofing, but even doing that, mine is not happy

Man i feel useless af rn XDD, anyhow this is more looking like root detection like nift mentioned in either my old 163 issue or another opened one (or maybe something altogether like xposed/lsposed too if you have it installed which is kinda required for signature spoofing for Microg to work)

Not sure if a clean install on your end is possible, but here is how i do it on all my devices (idk how else i could be of use until nift is back at least and share his input on this), from the Stock Rom I :
1. Reboot to Download Mode.
2. Flash TWRP recovery with Odin.
3. Reboot to Recovery.
4. Format Data (the option where you type yes) instead of Wiping it.
5. Advanced Wipe.
6. Tick System, Dalvic Cache, Cache, Internal Storage then wipe.
7. Reboot to Recovery.
8. Flash the Custom Rom of your choice.
9. Reboot.
10. Enable developer options then ADB Debugging.
11. Reboot to Recovery.
12. Flash custom kernel (optional).
13. Reboot.
14. Reboot to Recovery.
15. Flash latest Magisk zip.
16. Reboot.
17. Install Magisk Manager (or just enable internet and it will self download).
18. Reinstall Magisk directly then click the back arrow go to Settings and enable Zygisk.
19. Reboot.
20. Flash LSposed in Magisk.
21. Reboot.
22. Install the Fake Gapps apk and any other Xposed module of your choice. Personally i go for AnyWebview (i use Mulch Webview), Core Patch, Enable Screenshot (A12+), Kill Domain Verification (A12+), NoStorageRestrict, and LuckyPatcher. All can be downloaded from Fdroid (or Droid-ify) or directly from the LSPosed Manager except for LuckyPatcher.
23. Open LSposed Manager then enable everything.
24. Reboot.
25. Install Root Explorer (or whichever root file manager you prefer).
26. Copy the play store apk (latest A6+ apk to /data/adb then rename it to Phonesky.apk.
27. Install Microg v3.4.4 in Magisk
28. Reboot
29. Open Microg Services then tick and give it all permissions. In my case SMS and Location refused to be enabled, so i simply installed the microg services apk then force closed the app and reopened it and it worked.
30. In the Microg Services make sure to enable Allow apps to find accounts in Google Accounts section before adding your google account, then simply add the account and enable everything on the other sections (this part depends on the person).
31. As for the Play Store don't open it yet, go to app info and give it Storage permission only. If you open it now and check for app updates you will see a something went wrong error, to fix it close the app then go back to app info and remove storage permission and give it to it again. Now reopen it and it should be working perfectly (and survive reboots and self updates).
32. Now i install Google Play Games (its partially supported and working on quite a few games) and Google Drive (this is just a paranoid step for Whatsapp tbh XD), then open them once so they find my account, then install a handful of apps like Whatsapp and not using the Playstore again until they need updates or install games.
33. Copy the rest of my data over the phone and that is it.

Pretty i took the very long and paranoid way in alot of steps but this is might just be me but doing so reassures me more that i have a more stable and issue-free installation which i can easily retrace what went wrong if i messed up some day, not sure how helpful or relevant this might be, but i was eventually gonna send it as a reference when nift get back to me and we start doing testing for the v4+ Microgs, anyhow have a good one and sorry if im not being helpful enough XDD

**Comment by bphd** [comment]
Yeah it's for sure about root detection. But here I try with MGIR to acquire device integrity to begin with, and then would dig into root detection. If I don't even have integrity it's lost cause

**Comment by Uosx009** [comment]
> Yeah it's for sure about root detection. But here I try with MGIR to acquire device integrity to begin with, and then would dig into root detection. If I don't even have integrity it's lost cause

Play store issues aside, have you tried flashing the v17.3 PIF magisk module while being on Microg v3.4.4, that PIF version does work and doesnt crash microg services, for root detection better to try lsposed modules instead of magisk ones if you ever going to try that route

**Comment by Uosx009** [comment]
> Before updating I think I was on something like PIF 173 MGIR 344 and it wasn't working, so I did a global update of everything possible. Now it's MGIR 410 PIF 174 and other things. And yeah 174 is clearly know to be problematic, many users reported downgrading, I haven't read what @chiteroman was thinking about it, he should know now probably
> 
> About root detection, systemless modules are better than XPoseD ones, it's the xposed ones that triggers a rain of problems. But you need both as multiple methods are available only as one or another. But it would be greatly better if everyone was converting to systemless modules, but I guess it's more difficult
> 
> As of now I use both, many modules that are known to correct problems, yet no results. I don't use everything that exists as some seems useless now

That is quite unfortunate, though you shouldn't be on MGIR 410 right now because it does not convert Microg services nor the play store nor the GSF nor the maps apps to system ones, not sure if its actually working properly in your device but its better to stick to v4.0.2 if you want the latest working one since v3.4.4 didn't work for ya integrity wise, about root detection as i mentioned before its better to wait for nift's instructions as i dont feel qualified enough to suggest reliable fixes even though i think at this point you might have tried everything out there. Apologies for not being useful here XD, have a good one ahead and best of luck!

**Comment by nift4** [comment]
> im here again XD

Welcome back. To reiterate what I said in the now-deleted issue: Can you please try 4.0.2 with:
1. Uninstall module related stuff
2. Reboot
3. Uninstall the apps
4. Now install microG and Play Store A10+ APK
5. Flash module
6. Reboot
and tell me what happens, without doing any workarounds on top of that?

**Comment by Uosx009** [comment]
> > im here again XD
> 
> Welcome back. To reiterate what I said in the now-deleted issue: Can you please try 4.0.2 with:
> 
> 1. Uninstall module related stuff
> 2. Reboot
> 3. Uninstall the apps
> 4. Now install microG and Play Store A10+ APK
> 5. Flash module
> 6. Reboot
>    and tell me what happens, without doing any workarounds on top of that?

Thank you, lemme do it right now

**Comment by Uosx009** [comment]
@nift4 quick question, when you say unistall apps do you mean like the microg services and companion/play store if they are still on the device as user apps or apps like whatsapp which use the functionality of microg ?

**Comment by Uosx009** [comment]
@nift4 Results:
1. After rebooting and unlocking the screen, Nova Launcher keeps crashing along side a few other apps (im using the regular trebuchet rn so will just try to reinstall them later)
2. The play store does open with no issues, however after adding my account (because it asked me to sign in so i test installing apps) im now getting the Error retrieving information from server. DF-DFERH-01 (which i didnt get with the A6+ ver on v3.4.4 however i didnt test it with v4.0.2).
3. Microg is working well and i didnt need to reinstall the apk, managed to tick all the boxes with no issues (even location and sms).

other then this i cant say i notice anything, though now i need you tell me what to do about the play store, im pretty sure it will work if i give it the storage permission but ill wait for your reply first

**Comment by nift4** [comment]
@Uosx009 my bad forgot to mention, yes please grant all permissions to Play Store and microG

**Comment by Uosx009** [comment]
> @Uosx009 my bad forgot to mention, yes please grant all permissions to Play Store and microG

- Granted all permission to the Play Store from it app info but im still getting the Error retrieving information from server. DF-DFERH-01
- Microg already got all permissions granted should i like enable everything in the other sections too (like device registration, safetynet, and so on) ?

**Comment by Uosx009** [comment]
> @Uosx009 my bad forgot to mention, yes please grant all permissions to Play Store and microG

@nift4 
- Granted all permission to the Play Store from it app info but im still getting the Error retrieving information from server. DF-DFERH-01
- Microg already got all permissions granted should i like enable everything in the other sections too (like device registration, safetynet, and so on) ?

**Comment by nift4** [comment]
@Uosx009 great now that this is sorted out, can you repeat exactly what u did so far but with 4.1?

**Comment by Uosx009** [comment]
> @Uosx009 great now that this is sorted out, can you repeat exactly what u did so far but with 4.1?

Well im pretty sure i need to retest it right now since i didnt have a fully successful microg install (v4.0.2) last time, but when i was on v3.4.4 and even when i was on v4.0.2 (with workaround to fix the play store), directly upgrading through magisk or even removing the old microg and reinstalling v4.1.0 the same way you just instructed me with v4.0.2 had the same results, which was the microg and play store and gsf and maps apps all were not converted to system apps which should be why the play store kept crashing when trying to open it, the microg app was opening with no issues but it functionality was lost (because it was just a user app as you told me in the deleted issue).

**Comment by Uosx009** [comment]
> > @Uosx009 great now that this is sorted out, can you repeat exactly what u did so far but with 4.1?
> 
> Well im pretty sure i need to retest it right now since i didnt have a fully successful microg install (v4.0.2) last time, but when i was on v3.4.4 and even when i was on v4.0.2 (with workaround to fix the play store), directly upgrading through magisk or even removing the old microg and reinstalling v4.1.0 the same way you just instructed me with v4.0.2 had the same results, which was the microg and play store and gsf and maps apps all were not converted to system apps which should be why the play store kept crashing when trying to open it, the microg app was opening with no issues but it functionality was lost (because it was just a user app as you told me in the deleted issue).

@nift4 here is what happened then, as i said i definitely need to retest it now on this Rom, i can test it in both cases the first being a direct upgrade from a working v4.0.2 and then one from a fresh install (ill do what you suggested for the v4.0.2 but with v4.1.0 module instead). 

Do let me know what next for now only thing left Play Store wise is trying to wipe Dalvik cache and cache (this is also to see if the crashing apps would work or would i have to reinstall them still) and see if it gonna survive that, and the self update of play store (which judging by the a6+ version it should work on a10+ too hopefully). Thank you very much for your time and assistance, ill be waiting for your reply!

**Comment by nift4** [comment]
I don't understand, did you try or not?

**Comment by Uosx009** [comment]
> I don't understand, did you try or not?

i did not, those results were from my previous tries on the other custom rom

**Comment by Uosx009** [comment]
@nift4 Direct upgrade was a success (from v4.0.2 to v4.1.0 from Magisk), both microg and play store were not converted to user apps and still working properly, play store also survives reboots and installing apps is working too, imma clear dalvik cache later on tonight then wait for self update incase i face any issues related to that, 

But for now everything seems to be working perfectly gonna have to update microg on my other older devices too. Again thank you very much for your time and apologies for wasting it since its clear at least to me that this is most likely was just a rom related issue and it prolly might be the case for others too.

If you need someone to test stuff just let me know thanks again, ill close this issue right now cheers!

**Comment by bphd** [comment]
@Uosx009 Can we discuss over TeleGram?

**Comment by Uosx009** [comment]
> @Uosx009 Can we discuss over TeleGram?

@bphd Sure i dont mind though not sure how exactly i could be of more use since your case might need a bit more technical and deep stuff which im defo not the right guy for, anyhow my username in telegram is @C1L4NCE
