### ISSUE TITLE
Install failed - install path /system/priv_app/phonesky/phonesky.apk

### ISSUE THREAD

**Issue by arconaut-git** [nift4/microg_installer_revived#174]
Install fails with this error (screenshot) but working on 3.4.4-0
On lineage unofficial Android 11 and Galaxy G965F
![Screenshot_20240913-110450_Trebuchet](https://github.com/user-attachments/assets/84ca4197-0f46-48cf-a0b7-176fdf7db4bc)

**Comment by Uosx009** [comment]
Heya, before you do anything if you have some apps that you can cloud backup with google drive (like Whatsapp) and anything else that is related to a google account, when that is done here is what i recommend you do (for little to no errors/issues):

1. Uninstall Microg 3.4.4 from magisk.
2. Reboot.
3. Delete the Phonesky.apk file in /data/adb.
4. Goto Settings > Apps > All Apps (show system) and check if microg services or play store or microg companion (fake store) or com.android.vending apps are installed, if they are there simply uninstall them.
5. Reboot.
6. Grab a fresh copy of the Microg v4.0.2 zip (dont use v4.1.0 it got issues), the Microg apk from either from F-droid (add the Microg repo if you cant find it), or the [Microg website](https://microg.org/download.html) or directly from [Github ](https://github.com/microg/GmsCore/releases/tag/v0.3.2.240913), and the Play Store app (download whatever version that works for you) or the companion (fake store) apk (same sources as the microg apk).
7. Install the Microg and Playstore or Companion apps like you would install any normal app.
8. Now install the Microg v4.0.2 zip (you do not need to copy anything in /data/adb for this version).
9. Reboot.

Microg should be working now though im not sure about the play store, currently opened an issue about play store issues if you are facing some even with v3.4.4 feel free to check out the workaround i posted there (unless its working for you with no issues or you fixed it in your own way). Have a good one hope this helps!

**Comment by arconaut-git** [comment]
@Uosx009 many thanks for walking me through (successfully)
