### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by Incomptus** [nift4/microg_installer_revived#175]
Hello 
I am facing this issue while updating,

Here is the log

- Copying zip to temp directory
- Installing microG_Installer_Revived-Revived_4.1.0-0(40100).zip
- Device is system-as-root
Archive:  /data/user/0/t.mshhxjkpomtl.m/cache/flash/install.zip
  inflating: module.prop
**************************
 microG Installer Revived 
 by nift4 
**************************
Archive:  /data/user/0/t.mshhxjkpomtl.m/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- Extracting module files
Archive:  /data/user/0/t.mshhxjkpomtl.m/cache/flash/install.zip
  inflating: androidacy-config.json
  inflating: CHANGELOG
  inflating: customize.sh
  inflating: LICENSE
  inflating: module.prop
  inflating: README.md
   creating: system/
   creating: system/etc/
   creating: system/etc/permissions/
  inflating: system/etc/permissions/privapp-permissions-org.microG.xml
  inflating: system/etc/permissions/com.google.android.maps.xml
   creating: system/etc/sysconfig/
  inflating: system/etc/sysconfig/org.microG.xml
   creating: system/etc/default-permissions/
  inflating: system/etc/default-permissions/permissions-com.google.android.gms.xml
   creating: system/product/
   creating: system/product/etc/
   creating: system/product/etc/permissions/
  inflating: system/product/etc/permissions/privapp-permissions-org.microG.xml
   creating: system/product/app/
   creating: system/product/app/VollaGSMNlp/
  inflating: system/product/app/VollaGSMNlp/.replace
   creating: system/product/app/VollaNlp/
  inflating: system/product/app/VollaNlp/.replace
   creating: system/product/overlay/
   creating: system/product/overlay/microGOverlay/
  inflating: system/product/overlay/microGOverlay/microGOverlay.apk
   creating: system/framework/
  inflating: system/framework/com.google.android.maps.jar
   creating: system/priv-app/
   creating: system/priv-app/GsfProxy/
  inflating: system/priv-app/GsfProxy/GsfProxy.apk
   creating: system/app/
   creating: system/app/VollaNlpRRO/
  inflating: system/app/VollaNlpRRO/.replace
Collecting information about com.google.android.gms
Checking if com.google.android.gms is installed
Collecting file path of com.google.android.gms
Checking if file path of com.google.android.gms is on /data
Checking if file path of com.google.android.gms exists
Checking if com.google.android.gms is microG
Checking if com.google.android.gms is a supported version
Collecting information about com.android.vending
Checking if com.android.vending is installed
Collecting file path of com.android.vending
Checking if file path of com.android.vending is on /data
- ERROR: expected microG Companion / Play Store install path to be on /data, but it's /system/priv-app/Phonesky/Phonesky.apk
! Installation failed

**Comment by Uosx009** [comment]
@Incomptus Heya someone else had the same issue just follow the steps i put in the closed #174 issue cheers!

**Comment by nift4** [comment]
Have you followed the install instructions, https://github.com/nift4/microg_installer_revived?tab=readme-ov-file#installation

Especially the "Install microG 0.3.2 and Companion (or real Play Store) as normal user app" ?
