### ISSUE TITLE
Failure [DELETE_FAILED_INTERNAL_ERROR]

### ISSUE THREAD

**Issue by bphd** [nift4/microg_installer_revived#176]
sudo pm uninstall com.google.android.gsf

**Comment by Uosx009** [comment]
had that same issue running the adb shell pm uninstall -k --user 0 with a pc when i still had issues installing v4.1.0, pretty sure the gsf package should be removed after uninstalling the microg module and even if it was still in the app manager it should be there just as a user app that you can remove like any normal app. 

Gotta wait for nift to get a more accurate response on what might causing that, btw if the telegram username i sent in my reply isnt working or anything lmk, im more of a signal user and only rarely use telegram for communication so do tell if there was kind of issue or something when you see this cheers!

**Comment by bphd** [comment]
> @bphd had that same issue running the adb shell pm uninstall -k --user 0 with a pc when i still had issues installing v4.1.0, pretty sure the gsf package should be removed after uninstalling the microg module and even if it was still in the app manager it should be there just as a user app that you can remove like any normal app.
> 
> Gotta wait for nift to get a more accurate response on what might causing that, btw if the telegram username i sent in my reply isnt working or anything lmk, im more of a signal user and only rarely use telegram for communication so do tell if there was kind of issue or something when you see this cheers!

You're not active on org.telegram.messenger

So if I get it right you need to remove the system part and user part? Afaik `pm` has a system and user variant. @nift4 should get all relevant command of the case to apply to automatically get rid of the system and user part aswell, so less complain because things done right

**Comment by nift4** [comment]
maybe just clean flash and start over?

**Comment by bphd** [comment]
> maybe just clean flash and start over?

That's part of the default procedure to get rids of those apps beforehand, so it should be greate to integrate needed commands to instructions

**Comment by Uosx009** [comment]
> You're not active on org.telegram.messenger
> 
> So if I get it right you need to remove the system part and user part? Afaik `pm` has a system and user variant. @nift4 should get all relevant command of the case to apply to automatically get rid of the system and user part aswell, so less complain because things done right

replied in telegram just got back home

and yea that's pretty much it but you prolly wouldn't need to go as far as removing them with a command as you can just uninstall them, as nift said try like a full clean install of microg (just check #173 & #174)  and if that still doesn't work you might want to consider re-flashing your rom if possible (I'm almost certain doing that should fix your issues with microg not sure about the root detection/integrity ones though it might help with them as well). I'll be on telegram now have a good one!

**Comment by bphd** [comment]
I already reflashed things a number of times, it's not about that. It's an error of a problem that comes from somewhere that needs to be treated. Sent logs and error needs to be read by authors and pinpoint to where the module acts and what happens upon it

**Comment by bphd** [comment]
I happens probably because it's already uninstalled or not sufficent rights

Make sure to uninstall user and system applications to uninstall everything. Though that will create bootloops, so better immediately reinstall everything behind, or reinstalling wihtout uninstalling in the first place
