### ISSUE TITLE
Bootloop when activating MGIR

### ISSUE THREAD

**Issue by bphd** [nift4/microg_installer_revived#177]
And no bootloop anymore when deactivating 

Bootloop says lot of things but for example it seems to claim to have missing permission state on something like all package for user 10. And it fails to parse many things

**Comment by bphd** [comment]
I reinstalled module and no bootloop anymore but error -9 binding to play store failed

**Comment by bphd** [comment]
I activated device registration and now I can activate attestation but still error -9

**Comment by nift4** [comment]
Great that the bootloop is fixed, for Play Integrity there already is open issue

**Comment by bphd** [comment]
> Great that the bootloop is fixed, for Play Integrity there already is open issue

Which one
