### ISSUE TITLE
Signature spoofing should be enabled before installing the module

### ISSUE THREAD

**Issue by hieu-van** [nift4/microg_installer_revived#18]
To ensure a smooth user experience, I believe that we should tell users to enable signature spoofing before installing the module. Doing vice versa would likely cause problems with apps that depend on GMS.

PS: Many thanks for contributing me in the documentation :eyes:

**Comment by nift4** [comment]
How can we even check that...? It would require installing an APK, doesn't it?

**Comment by hieu-van** [comment]
Signature spoofing is entirely dependent on the users, a single Magisk module wouldn't be able to accomplish it. We only need to update the README so as to instruct them to enable SS before installing the module.

**Comment by nift4** [comment]
microG does that by being installed and getting it's own signature. (Or if you mean the system supports it checkmark, it just checks for the SPOOF_PACKAGE_SIGNATURE permission. It does not work with, for example, FakeGapps.)

**Comment by nift4** [comment]
So checking won't be reliable. However, moving around the instructions, no problem with that.
