### ISSUE TITLE
can uninstall gms module support ksu?

### ISSUE THREAD

**Issue by bigm0re** [nift4/microg_installer_revived#180]
i'm use ksu,can uninstall gms module support ksu?

**Comment by nift4** [comment]
I do not use KernelSU and I do not plan to start using it, so unless someone sends a patch, probably not.

**Comment by bigm0re** [comment]
> I do not use KernelSU and I do not plan to start using it, so unless someone sends a patch, probably not.

thanks for reply,I have done by myself and install microg success，so I close it

**Comment by bphd** [comment]
> > I do not use KernelSU and I do not plan to start using it, so unless someone sends a patch, probably not.
> 
> thanks for reply,I have done by myself and install microg success，so I close it

You should explain what you did before leaving because many users will have that problem as long as nift don't adapt for KSU

**Comment by nift4** [comment]
Hi, the new V4 version might support KSU but I didn't test it: https://github.com/user-attachments/files/17334031/gms_delete.zip
