### ISSUE TITLE
MicroG APKs cannot be installed

### ISSUE THREAD

**Issue by Stelle-5** [nift4/microg_installer_revived#182]
Device : Samsung Galaxy Tab S3
OS : Android 9.0

Installation checklist :
STEP 1 "Install gms_delete.zip v3" : OK
STEP 2 "Reboot" : OK
STEP 3 "Uninstall Google Play Services" : ~~OK~~ EDIT : NOT OK seem my comment
I've tried to disabled it in a first time, after that i've "uninstalled" it with UAD Next-Gen, and i've tried with the adb command "pm uninstall" (not working for the 3 methods).

STEP 4 : "Install microG APK (must succeed) and Companion / Play Store APK" : **NOT OK**

Issue :

MicroG APKs (Services or Companion) can't be installed correctly on the device.
I've tried almost all apks version of MicroG Services (0.2.23 ; 0.2.27 ; 0.3.1.2 ; 0.3.3) and MicroG Compagnion (0.0.1 ; 0.2.1 ; 3.2)
And so we can't execute the MicroG installer ver. 4.1.1-0 (not working on 4.0.2-0 too) and install MicroG.

![Screenshot_20241005-212525_Package installer](https://github.com/user-attachments/assets/dbfc67a6-eda1-406f-bc32-cbd5b272789e)

![Screenshot_20241005-212335](https://github.com/user-attachments/assets/40477600-7994-4025-8e82-8956cae0fd55)

Solution found :
Using MicroG ver. **3.4.4-0** or below works fine to install MicroG.

![Screenshot_20241005-212647](https://github.com/user-attachments/assets/8841f872-a058-4b63-a8e2-5784d5f0c787)

![Screenshot_20241005-212820_microG Services](https://github.com/user-attachments/assets/070b5368-1e7b-4b44-9cb9-b91f4c39d5e3)

**Comment by Stelle-5** [comment]
I've finaly found where the problem was, it seems that disabled, or "uninstall" with adb original play store/services/framework **isn't sufficient**.

You really need to **uninstall it with an app manager with root permission**. 
And you need to verify that it's really uninstalled (i've uninstalled com.google.android.gms twice...)
(I've used this : https://github.com/nicolaserlonghi/UninstallSystemApps)



![Screenshot_20241006-092356](https://github.com/user-attachments/assets/edba2994-3eaf-45f1-a33e-114c951b372c)

**Comment by nift4** [comment]
I'm glad you solved your issue, OP. 
Please note I don't support 3.x versions anymore because it's too easy to shoot yourself in the foot.
