### ISSUE TITLE
Permission to access location in the background (Android 11)

### ISSUE THREAD

**Issue by Azureit** [nift4/microg_installer_revived#19]
Error while trying to give **permission to access location in the background**

"cannot grant android.permission.ACCESS_BACKGROUND_LOCATION as the matching foreground permission is not already granted"

![bug_permission2](https://user-images.githubusercontent.com/1774476/113438573-babf7900-93e0-11eb-9bf4-9dc16797a37f.png)

**Comment by Azureit** [comment]
One workaround is install an old microG Installer Revived 1.10.0-0 that has GmsCore 0.2.17 and after that, use fdroid to update to 0.2.18 and then it will let grant that permission.

**Comment by nift4** [comment]
I'm closing this as it is literally the same as #20

**Comment by duven87** [comment]
Hi,
today I installed the latest Divestos ROM for Pixel 4a, rooted it with Magisk and installed the fakegapps apk with LSposed and then microg_installer_revived.
The first time microg opens there is an error and I close it.
Then when I open it again it works and let me activate everything.
I can activate all permissions except:

- Permission to access location in the background.
- Permission to recevive text messages

I have gone to migrog permissions and I have granted all of them and I still can't activate it.
On the other hand if I install fakegapps from the bitgapps project, they are all active by default.

How is that?

**Comment by nift4** [comment]
download & install microg apk, it will solve your issue

**Comment by duven87** [comment]
com.google.android.gms-233515000.apk solved the problem. 
Thanks!

**Comment by nift4** [comment]
> PS. Wouldn't it be better if you and whew-inc worked together for the same project/module?

I make sure my module works together with his module from time to time, and it worked fine for me, we also recommend each others module in the READMEs and I contributed to his code a while back :)

**Comment by duven87** [comment]
yes yes, I have seen it :) 
but I meant all in one module/zip. 
So one saves installing LSposed and fakeapps apk. 
(like in fakegapps/bitgapps project)

**Comment by nift4** [comment]
some roms do not need fakegapps, they already have signature spoofing. and we are uninvolved with lsposed project, some people like to use another xposed fork instead (which works fine) etc etc...
