### ISSUE TITLE
MicroG DroidGuard Helper keeps crashing

### ISSUE THREAD

**Issue by Pokemetti** [nift4/microg_installer_revived#2]
I just installed this lovely Magisk Module and nearly everything works, but when I try to check the SafetyNet, the system shows a force close message.

**Comment by nift4** [comment]
Log? microG breaks SafetyNet anyway, so no chance to have it passing ;)

**Comment by Pokemetti** [comment]
Sorry, issue solved itself, I updated the microG apps through F-Droid, then the GMS core could finally get the permission to access storage, which before just failed. Now working fine, Chrome doesn't crash anymore, I'm looking on fixing SafetyNet. I would really recommend installing the latest version though.
