### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by marcinbauer85** [nift4/microg_installer_revived#26]
I installed this package via Magisk by accident and since it has messed up my OnePlus6T. How can I revert back to original GMS and Play Store? When I installed an APK of Google Play Store I couldn't hit "Sign in", and all other apps notified that I need to login to GPS.

Please help.

**Comment by nift4** [comment]
You need to factory reset.

**Comment by ShubhamPatilsd** [comment]
Couldn't you just remove the module from Magisk and `pm uninstall` the apps that were installed into `/system/priv-app`? 

https://www.maketecheasier.com/uninstall-system-apps-without-root-android/

**Comment by nift4** [comment]
Yes, but if you want working Gapps, you would have to reinstall all dependant apps

**Comment by marcinbauer85** [comment]
Yes I had to reflash the whole phone :( Too bad there's no instructions how to get back.

**Comment by nift4** [comment]
> Too bad there's no instructions how to get back.

It's not about instructions or this module, it's about apps' state expectations breaking
