### ISSUE TITLE
Get apks from fdroid

### ISSUE THREAD

**Issue by Dev0110** [nift4/microg_installer_revived#28]
Hello !
It is possible to get the microg apks from fdroid to update directly from fdroid and avoid signature mismatch ?
Else tanks for your amazing work !

**Comment by nift4** [comment]
The sha256 hash of our GmsCore apk matches the hash of the apk in F-Droid. Not sure what's the problem here. Or are you talking about other microG apks?

**Comment by nift4** [comment]
I just checked all the others: all match the version of microG's F-droid repo.

**Comment by Dev0110** [comment]
Strange...
Here's a screenshot from my fdroid :
![Screenshot_20210817-095155_F-Droid](https://user-images.githubusercontent.com/23175256/129686358-39943c15-725c-4eeb-bd89-44d0c37e42a3.png)

**Comment by nift4** [comment]
You added the microG fdroid repository, right?

**Comment by Dev0110** [comment]
Yeah !

**Comment by nift4** [comment]
just checked on my device: fdroid shows all versions back to 0.2.15 and says 0.2.21 is installed. try to "uninstall updates" for microg

**Comment by Dev0110** [comment]
I don't have such option...

**Comment by Dev0110** [comment]
![Screenshot_20210817-135954_F-Droid](https://user-images.githubusercontent.com/23175256/129721888-1189d371-ff28-46dc-8529-d1fda7c90485.png)

**Comment by nift4** [comment]
In "App Info"

**Comment by Dev0110** [comment]
Again, it seems that there's no installed updates...
![Screenshot_20210817-140929_Settings](https://user-images.githubusercontent.com/23175256/129723201-50f651e1-de01-4977-a19a-99e4a610b590.png)

**Comment by nift4** [comment]
Three dots afaik

**Comment by Dev0110** [comment]
OK so i did it and then i installed updates from fdroid.
Problem solved
Thanks for your help
