### ISSUE TITLE
Can't update microg, signature mismatch

### ISSUE THREAD

**Issue by diggit** [nift4/microg_installer_revived#3]
As title says, F-droid does not let me update microG package due to mismatching signature. I am using official microG repo https://microg.org/fdroid.html . Running Android 10 GSI (LineageOS 17, unofficial) on A40.

**Comment by nift4** [comment]
Okay, I look into updating APKs.

**Comment by nift4** [comment]
Try with 1.1.0 again, please

**Comment by nift4** [comment]
@diggit

**Comment by diggit** [comment]
Updated module an installed apk as written in readme. Fdroid does not complain anymore. So I'd consider this issue solved.

**Comment by nift4** [comment]
I think you missunderstood a bit (or I misunderstood a bit 😂): Simply update the module and then install the apk

**Comment by diggit** [comment]
Yeah, that's exactly what i did.
