### ISSUE TITLE
Option to choose whether to install Droidguard Helper

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [nift4/microg_installer_revived#33]
Some people (like me) don't want to install this proprietary piece of software so is it possible to make such an option available?

**Comment by nift4** [comment]
As far as I am aware, it does not contain DroidGuard, that gets downloaded while checking SafetyNet the first time. So leaving SafetyNet disabled in microG settings should leave you safe.

**Comment by 1-minute-to-midnight** [comment]
Will test out and get back to you

**Comment by 1-minute-to-midnight** [comment]
Hey this is what it says in the f-droid repo and under the package name microG DroidGuard Helper: "Contains and downloads proprietary Google code to your device"

**Comment by nift4** [comment]
Hmm, I see. I'll do it when I have time and post an test zip here.

**Comment by 1-minute-to-midnight** [comment]
Hey I found a module that exactly fits my needs: https://github.com/FriendlyNeighborhoodShane/MinMicroG/

**Comment by nift4** [comment]
> Hey this is what it says in the f-droid repo and under the package name microG DroidGuard Helper: "Contains and downloads proprietary Google code to your device"

I can confirm this is accurate, one proprietary jar file is inside the apk. I am adding a flag to disable DroidGuard installation.

**Comment by nift4** [comment]
Fixed in 2.3.0-0.
