### ISSUE TITLE
Please add the new MicroG version v0.2.23.214816

### ISSUE THREAD

**Issue by MartinX3** [nift4/microg_installer_revived#35]
https://github.com/microg/GmsCore/releases/tag/v0.2.23.214816

**Comment by nift4** [comment]
Test build: https://github.com/nift4/microg_installer_revived/releases/tag/v2.4.0-test

**Comment by RobertoWa** [comment]
working well.

**Comment by MartinX3** [comment]
Thank you

**Comment by nift4** [comment]
awesome, released: https://github.com/nift4/microg_installer_revived/releases/tag/v2.4.0-0

**Comment by nift4** [comment]
p.s.: the zip is 100% the same so no need to redownload
