### ISSUE TITLE
Add magisk updater url

### ISSUE THREAD

**Issue by MartinX3** [nift4/microg_installer_revived#36]
Since magisk v24 the modules need to include an update URL, because the repo got removed.
(Like the GitHub release artifacts, I think)

**Comment by nift4** [comment]
yep I was planning to do that but I was lazy enough to not update to Magisk v24 yet lol, i'll do it when I have free time

**Comment by MartinX3** [comment]
And I'm still not on v24.1 (only the app), because I have no time to fix my phone if it bootloops xD
But the plugin store is in the void anyway as far as I know.

**Comment by soracqt** [comment]
https://github.com/nift4/microg_installer_revived/pull/37
I created pr for magisk 24.x update.json

**Comment by nift4** [comment]
merged, now someone just has to test

**Comment by soracqt** [comment]
![Screenshot_20220131-150822_Magisk](https://user-images.githubusercontent.com/72482919/151746821-e12023b7-84ce-4924-9831-48d8e1fdfe58.png)
Update button is working.
I don't know if a new version will be released and upgraded.

**Comment by MartinX3** [comment]
And you should add a GitHub action updating the JSON file on each release.
(You can also auto generate releases, if you git tag a version via github-actions)

**Comment by nift4** [comment]
> And you should add a GitHub action updating the JSON file on each release. (You can also auto generate releases, if you git tag a version via github-actions)

I'm modifying module.prop manually as well, so I decided I'm to lazy :P
If anyone prs that I'll happily merge tho

**Comment by nift4** [comment]
https://github.com/nift4/microg_installer_revived/releases/tag/v2.4.0-test2

It should offer an update to 2.4.0-1

**Comment by MartinX3** [comment]
It does

![Screenshot_20220131-183843_Magisk.png](https://user-images.githubusercontent.com/4518092/151844482-b1c97bf8-c9c7-47df-8a17-89b452ee6b6a.png)

**Comment by nift4** [comment]
The changelog looks wrong lol, I'll push a fix

**Comment by nift4** [comment]
Pushed 2.4.0-2 as OTA, does it work now?

**Comment by MartinX3** [comment]
![Screenshot_20220131-185903_Magisk.png](https://user-images.githubusercontent.com/4518092/151847621-7dd339b2-09f3-40b7-87d8-b1f68f7d8461.png)

**Comment by nift4** [comment]
awesome, released
