### ISSUE TITLE
Can't give SMS permission.

### ISSUE THREAD

**Issue by pc00per** [nift4/microg_installer_revived#38]
SMS permission has issue. Installing microg manually & systemizing GMSCore has no problem at all. Can you look into this issue?

**Comment by nift4** [comment]
did you install in recovery or magisk manager? what magisk version, device, module version? can you share installer logs?
I fixed the issue a while ago already and it's strange that it is back - atleast I know the cause already

**Comment by pc00per** [comment]
> did you install in recovery or magisk manager? what magisk version, device, module version? can you share installer logs? I fixed the issue a while ago already and it's strange that it is back - atleast I know the cause already

Sorry that was older version sat on my sdcard. It's fixed now.
