### ISSUE TITLE
Installing real play store

### ISSUE THREAD

**Issue by mahdi921** [nift4/microg_installer_revived#39]
Hi
I want to install real play store with update or reflashing. But the installer couldn't find the phonesky.apk in data/adb. 
Am I doing it wrong? Should I do a clean install for microg with real ps?
Also, I replaced real ps in the zip file, but there was an error saying that the previously installed app signature doesn't match this one.

**Comment by nift4** [comment]
> But the installer couldn't find the phonesky.apk in data/adb.

make sure the P is capital and remember to put it into /data/adb - not data/adb on your sdcard.

**Comment by mahdi921** [comment]
> make sure the P is capital and remember to put it into /data/adb - not data/adb on your sdcard.

You mean /storage/emulated/0/data/adb/ ?
The P is capital and the apk is in the mentioned path.

**Comment by nift4** [comment]
No I mean directly /data/adb/Phonesky.apk - accessible with a root file manager of your choice

**Comment by mahdi921** [comment]
I see. I'll try it right away.

**Comment by mahdi921** [comment]
That resolved the issue. Some minor problems occurred with magisk because I had to rename an adb file in order to make an adb folder.
Anyway, thank you.

**Comment by mahdi921** [comment]
I checked /data folder now, the adb folder is now replaced by adb file
