### ISSUE TITLE
Real playstore breaks microg's detection

### ISSUE THREAD

**Issue by A7pr8** [nift4/microg_installer_revived#40]
I got this problem in los 18.1 based rom(version with sigspoof) and in los 19(also sigspoof) too
Both the same device bcz I just updated to los 19

The problem when I put Phonesky.apk in adb and it gets installed and I reboot
Microg says that everything is working fine but app stops detecting microg plus safetynet check would say(you need google play service v13 or higher)
I found a way to get it working
I flash microg_installer revived without playstore then I replace /data/adb/modules/microg_installer/system/priv-app/Phonesky/Phonesky.apk with nanolox one
Then reboot somehow this fixed the problem and even safetynet worked
But in los 19 I am getting a bootloop whenever I do that
Hopefully this is fixable 
Thx for reading

**Comment by nift4** [comment]
> app stops detecting microg plus safetynet check would say(you need google play service v13 or higher)

Means signature spoofing did not

> But in los 19 I am getting a bootloop whenever I do that

I don't have any android 12 device, can you give me logs from /data/system/dropbox/?

**Comment by A7pr8** [comment]
Fakestore working on Los 18 and 19
As I said what I did fixed the problem on Los 18 and bootooped the device on Los 19

This is the file
https://drive.google.com/file/d/1UZqAFjj-bBqEAo_jQMvAI2kelmjYOyjm/view?usp=sharing

I can also do logcat/matlog/syslog,etc if u want too
The for replying

**Comment by nift4** [comment]
"access denied" on your link

**Comment by A7pr8** [comment]
I am sorry so much
https://mega.nz/file/7kcywLoQ#xOSuGCsR6-MKNChnYm_VqvKiMf5mCqZ1h80jW6e9Qng
This should work

**Comment by nift4** [comment]
```android.util.Log$TerribleFailure: App com.android.vending became active but still in NEVER bucket``` this sounds like your problem, imo no idea what this means

**Comment by A7pr8** [comment]
I did this after puuting phonesky In adb and installing it normally
So I dunnow
It happend with Los 18 too

**Comment by nift4** [comment]
isn't that an rom bug then?

**Comment by A7pr8** [comment]
I dunnow replacing it manually did make it work on Los 18 so I thought it might have a fix

**Comment by A7pr8** [comment]
I can talk with the rom devloper to know if it was a rom issue
But what should I tell him
Plus can"t be bcz patched playstore is old
It does show coorect mark on playstore in self-check

**Comment by A7pr8** [comment]
I am sorry for interruption again
But are you ignoring me?
(I can send any logs you want)

**Comment by nift4** [comment]
i'm not ignoring you, i'm just quite unsure what you are even doing and why don't you use the proper way to install playstore
if the proper way to install playstore causes any issues, you can use `pm grant com.android.vending android.permission.FAKE_PACKAGE_SIGNATURE`

**Comment by A7pr8** [comment]
Still not working
Apps are not detecting microg once play store is installed

**Comment by nift4** [comment]
can you please screenshot microg self test

**Comment by A7pr8** [comment]
It shows correct mark on everything
![Uploading Screenshot_20220305-153941_microG Services Core.png…]()

**Comment by nift4** [comment]
can you try to reinstall your app

**Comment by A7pr8** [comment]
What app
If u mean microg or playstore
I tried but still not working

**Comment by nift4** [comment]
No, the app that doesnt detect google

**Comment by A7pr8** [comment]
Hmm even playstore doesn't recongize the signed in account

**Comment by nift4** [comment]
For that, you need to enable "show account to apps" in the settings of the account

**Comment by A7pr8** [comment]
Still not working 
It still says " I need google play services which are not supported on this device"
Even the safetynet check can't find it

**Comment by nift4** [comment]
how did you set up signature spoofing

**Comment by A7pr8** [comment]
It is already in the rom
Even if I use non sig spoof rom and used fakegapps with lsposed I will still get the same issue once playstore is installed(the way u explained "copy Phonesky.apk to /data/adb"

**Comment by nift4** [comment]
if you install play store all marks in self test are still checked?

**Comment by A7pr8** [comment]
Yeah 
But honestly when I try to install by other ways like app systemizer I can't give playstore sigspoof permission manually (plus it doesn't get when using fakegapps and lsposed)
Even though I can give sigspoof persmission for fake store

**Comment by nift4** [comment]
Dude, I give up. This is an "you" problem and I have no idea what causes it.

**Comment by A7pr8** [comment]
![Screenshot_20220307-150318_Opera](https://user-images.githubusercontent.com/77297171/157039774-24910ae6-8fba-4df6-b453-2147fce6da6a.png)


Sorry for wasting ur time and getting on ur nerves 
It appears patched playstore won't work on los 18 or 19
I just want to say this a not a "me" problem

**Comment by MartinX3** [comment]
It worked for me on 18.1, but I heard about problems with 19.0.

(I switched back to aurora, because the modified playstore made trouble at my side about insta crashing sometimes)

**Comment by A7pr8** [comment]
I said I found a solution for it in los 18.1 in the first comment but it just bootloop in los 19

**Comment by nift4** [comment]
https://github.com/nift4/microg_installer_revived/releases/download/v2.6.1-0/microG_Installer_Revived.zip

**Comment by A7pr8** [comment]
Thank u so much man
It is working fine now
Sorry if I wasted your time and thanks so much
