### ISSUE TITLE
unzip error while trying to install

### ISSUE THREAD

**Issue by guillaumedc** [nift4/microg_installer_revived#41]
When I'm trying to install release 2.6.0-3 using Magisk 24.3, I end up on an unzip error.

Does anyone else facing this issue?

Or do you know what could be my problem?

Thanks!

**Comment by nift4** [comment]
Where did you get the zip exactly?

**Comment by guillaumedc** [comment]
https://github.com/nift4/microg_installer_revived/releases/download/v2.6.0-3/microG_Installer_Revived.zip

**Comment by nift4** [comment]
Can you try to download it from Androidacy's repo?
https://www.androidacy.com/magisk-modules-repository/
It's possible that my upload is corrupt.

**Comment by guillaumedc** [comment]
Same error with the zip downloaded from androidacy

**Comment by guillaumedc** [comment]
I tried with 2.5.0, 2.4.0-2, 2.4.0-1, 2.4.0-0 builds from GitHub and I end up with the same error.

Maybe it's build related, but it could be device related too of course.
But I do not have more log than `! Unzip error`, sorry.

**Comment by nift4** [comment]
> I tried with 2.5.0, 2.4.0-2, 2.4.0-1, 2.4.0-0 builds from GitHub and I end up with the same error.

Okay that's strange, I'm sure those older releases do work. Can you flash other modules?

**Comment by guillaumedc** [comment]
I tried other modules and it did not work either.
I finally found the problem. Issue was caused by file browser I used to select which zip to flash (with system one it just works).

Sorry for the not project related issue, and thanks for your quick and kindly support!
