### ISSUE TITLE
broken google apps

### ISSUE THREAD

**Issue by andreinit** [nift4/microg_installer_revived#44]
Hello.
I just installed it using Magisk Manager and all google apps got broken, as well as trying to enter in Settings or trying to use APKMirror installer (they crash after half a second).
Phone: Xiaomi REDMI note 9 pro
Magisk: 24.3

Can somebody help?

**Comment by nift4** [comment]
did you install it on accident or what?

**Comment by nift4** [comment]
Long story short, to fix it, you have to uninstall the module, factory reset your phone and do proper research next time - this module can't be installed on devices that have google apps already installed.
