### ISSUE TITLE
removing module after install breaks youtube

### ISSUE THREAD

**Issue by ImALoooserOk** [nift4/microg_installer_revived#45]
I use ArrowOS vanilla, and remembered this when I wanted to install microG. I rooted my phone, used this module, and it went great! then I uninstalled magisk along with the module, and then youtube says that google play services is not supported by my device. is this because I uninstalled magisk, or because of a microG problem?

**Comment by nift4** [comment]
what do you except? you did remove google play services and it tells you that.. in fact if i remember correctly youtube needs play services or microg installed to work

**Comment by ImALoooserOk** [comment]
So uninstalling magisk uninstalls microG? The thing is microG is still here. I'm guessing it broke?

**Comment by nift4** [comment]
microG is not a system app anymore, this is why it does not count.

**Comment by ImALoooserOk** [comment]
Would reinstalling magisk and the module fix this?

**Comment by nift4** [comment]
Probably, yes. If you are unlucky, you need to reinstall the youtube app.

In this state you wont be able to get SafetyNet anyways... SafetyNet with Magisk isn't hard either way, you can check XDA for a guide.

**Comment by ImALoooserOk** [comment]
I see thanks for the help, i'll try that later
