### ISSUE TITLE
Module name & donate link

### ISSUE THREAD

**Issue by hieu-van** [nift4/microg_installer_revived#46]
Hey ;) As NanoDroid stopped working on Android 10+ on my phone, I've decided to turn back to this module. Many thanks for keeping it alive!

I have two suggestions, first is you should add a way to donate. Second is, it can be said that this module is the only prominent and actively maintained microG module, so I think it makes sense to remove "revived" from the name

**Comment by nift4** [comment]
> Second is, it can be said that this module is the only prominent and actively maintained microG module

you forgot about minMicroG and micro5k

> first is you should add a way to donate

I currently cant accept digital money sadly, but id be happy if you donate it to mar-v-in/the microG project.
Cheers
