### ISSUE TITLE
UnifiedNlp not installed?

### ISSUE THREAD

**Issue by xslvrxslwt** [nift4/microg_installer_revived#47]
Just installed this module, UnifiedNlp seems not to be installed?
--
![Screenshot_20220629-004719_microG Services Core](https://user-images.githubusercontent.com/105242066/176317054-e3fc83b0-695c-47a3-9749-59fe79d7bf90.png)
![Screenshot_20220629-004729_microG Services Core~2](https://user-images.githubusercontent.com/105242066/176317055-5973051e-e3e0-4fed-9ef3-7725157a23e8.png)
![Screenshot_20220629-004743_microG Services Core~2](https://user-images.githubusercontent.com/105242066/176317056-c208482f-b639-4f4e-a1a5-69221780c9ea.png)

**Comment by nift4** [comment]
UnifiedNlp no longed needs to be installed. All location modules can be installed from https://microg.org/fdroid.html

**Comment by xslvrxslwt** [comment]
> UnifiedNlp no longed needs to be installed. All location modules can be installed from https://microg.org/fdroid.html

Thanks, issue resolved
