### ISSUE TITLE
Can't find module in magisk 

### ISSUE THREAD

**Issue by Yannik** [nift4/microg_installer_revived#5]
Hi,
I cannot find your module in the magisk manager app module downloads section. Is this on purpose?

**Comment by nift4** [comment]
![Screenshot_20200416-211947_Manager_______](https://user-images.githubusercontent.com/36458596/79497570-2ff73a00-8028-11ea-8b76-ddebef293929.png)
Strange

**Comment by nift4** [comment]
Hallo :)

**Comment by Yannik** [comment]
![Screenshot_20200416-212928_Magisk_Manager](https://user-images.githubusercontent.com/801996/79498361-726d4680-8029-11ea-94c5-c7a555cf7c87.png)

**Comment by Yannik** [comment]
![Screenshot_20200416-213024_Magisk_Manager](https://user-images.githubusercontent.com/801996/79498396-84e78000-8029-11ea-9817-fcf1191dcd7e.png)

**Comment by nift4** [comment]
seems to be an magisk (manager/repo) bug

**Comment by nift4** [comment]
seems to be an magisk (manager/repo) bug

**Comment by nift4** [comment]
by accident closed

**Comment by nift4** [comment]
I have the exact same versions of Magisk and MM

**Comment by Yannik** [comment]
i'm on lineageos 17.1 (android 10). WBU?

**Comment by nift4** [comment]
same

**Comment by nift4** [comment]
use the direct zip for now: https://github.com/nift4/microg_installer_revived/releases/tag/1.2.0

**Comment by Yannik** [comment]
@nift4 Interestingly enough, now it's showing up in the downloads section in magisk manager.

**Comment by Yannik** [comment]
Unfortunately installing the module leads to mass crashes of various applications. I've opened a new issue #6 for this.
