### ISSUE TITLE
Is it possible to get "spoofing" on Hisense Vision ROM?

### ISSUE THREAD

**Issue by axel9546** [nift4/microg_installer_revived#53]
Hi there! 
Is it possible to get this module to work 100% on Hisense A5, Vision ROM, Android 9, with root access, and magisk ofc?

At the moment, I cant find a way to get spoofing

**Comment by nift4** [comment]
Try https://github.com/whew-inc/FakeGApps with LSPosed or Nanodroid Patcher... However I cannot really support signature spoofing solutions as those are made by someone else, please keep that in mind.

**Comment by axel9546** [comment]
Thanks so much for reply! I am gonna try it!

How do I remove this module? I have disabled it, uninstalled it from magisk, but microG app persist installed

**Comment by nift4** [comment]
Uninstall microG app

**Comment by axel9546** [comment]
> Uninstall microG app

- Then
- Installed microG Revived
- Installed NanoDroid Patcher
- Spoofing and all checkmarks done
-  I tried google assistant but it won't work

Should I install FakeGapps too, at this point? What will be the change?

**Comment by nift4** [comment]
You have successfully installed this module. Google Assistant is not supported by microG, but to request support, use their bugtracker.
