### ISSUE TITLE
MicroG and Fakestore not removed after removing module

### ISSUE THREAD

**Issue by Luciogi** [nift4/microg_installer_revived#55]
In magisk, when I remove/delete module , microg and fakestore still exist on system (even after reboot). I have to manually delete them
Can you add this in scripts?

**Comment by nift4** [comment]
"on /system partition" or just as installed application which can be uninstalled in settings?

**Comment by Luciogi** [comment]
As User installed app

**Comment by nift4** [comment]
I will address this later.
