### ISSUE TITLE
MicroG crashing while trying to login

### ISSUE THREAD

**Issue by Felix-Kyun** [nift4/microg_installer_revived#58]
I had MicroG working just fine until I tried out the latest v3.0 today, now when i try to login, just after clicking next after typing the mail it crashes,

https://we.tl/t-LA5KmgHiY6

Btw it works just fine on the version 2.6.3-0

**Comment by nift4** [comment]
Please get a log using apps like Scoop or MatLog

**Comment by Felix-Kyun** [comment]
I don't have much knowledge in these things but is adb logs also fine ? Or do i need to use matlog/scoop ?

**Comment by nift4** [comment]
adb logcat is fine too

**Comment by Felix-Kyun** [comment]
[logcat.log](https://github.com/nift4/microg_installer_revived/files/9994138/logcat.log)

**Comment by nift4** [comment]
This is an already-fixed upstream microG bug. Either wait for the next release or enable SafetyNet.

**Comment by Felix-Kyun** [comment]
Thank you.
