### ISSUE TITLE
booting loop after uninstalling version 3.0.0-0

### ISSUE THREAD

**Issue by Aniark** [nift4/microg_installer_revived#59]
device: Redmi 7 Android 9

**Comment by nift4** [comment]
is google apps currently installed? What ROM?

**Comment by nift4** [comment]
/data/adb/dropbox/

**Comment by Aniark** [comment]
just re-flash ROM after booting loop, nothing left now, any other way could be helpful?

**Comment by nift4** [comment]
it's okay, thank you for the report
