### ISSUE TITLE
GMS/GFS updates in nanodroid's playstore

### ISSUE THREAD

**Issue by Joduai** [nift4/microg_installer_revived#60]
Howdy
To be honest I didn't know where should I even ask this question, but surely those who use nanodroid's playstore version have the same "issue".

After switching fakestore to nand's phonesky, google play wants to update some of its GFS/GMS components.
From brief infos I've found over the web every advice ends with disabling updates for those core apps.
But I can't find any switch to hide the apps or disable updates for them so they won't appear on the list.

Or should I go the opposite way, and update them?

One useful guide I found out is for updating the playstore apk. But it needs patching with keys, and tbh it looks like too much hassle: https://gitlab.com/Nanolx/microg-phonesky-iap-support

got installed latest microg 3.0 with nanodroid's Phonesky_132

----

Maybe It's a silly question, but what's the basic usage with microg revived package with fakestore when it goes to installing apps from google play? It is meant to get aurora store and then apps from playstore?

![Screenshot_20221123-135111_Sklep Google Play](https://user-images.githubusercontent.com/4009106/203554969-2baf7f71-78fd-423c-9355-984dc72958b0.png)

**Comment by nift4** [comment]
> But I can't find any switch to hide the apps or disable updates for them so they won't appear on the list.

It's not possible to disable updates. Just ignore them.

> Or should I go the opposite way, and update them?

That won't work and makes no sense, as you would install official GMS (if it would work, but it doesn't).

> It is meant to get aurora store and then apps from playstore?

Yes
