### ISSUE TITLE
how do i remove playstore?

### ISSUE THREAD

**Issue by Quiel245** [nift4/microg_installer_revived#63]
I installed microg with the real playstore and it is all working nicely but i recently discovered that aurora store can pretty much fulfill the needs i have with play store, so i wanted to remove it, but i dont know how, i tried deleting the apk from adb folder and reboot, but nothing changed, there is anyone there that can help me?

**Comment by fahimscirex** [comment]
By removing it from adb folder it becomes a user app so you have uninstall manually.

**Comment by Quiel245** [comment]
> By removing it from adb folder it becomes a user app so you have to uninstall manually.

It does? But a uninstall button still not here, only "deactivate" i should use the uninstall updates one?

**Comment by Quiel245** [comment]
> > By removing it from adb folder it becomes a user app so you have to uninstall manually.
> 
> It does? But the uninstall button still not here, only "deactivate" i should use the uninstall updates one?

ok, i uninstalled playstore updates and now it became fakestore like it should do but, it's normal for it to crash and send that message when i boot up my device?
