### ISSUE TITLE
Play store app not showing

### ISSUE THREAD

**Issue by skzidan** [nift4/microg_installer_revived#64]
Hi, i installed correctly but there is no play store app in the launcher nor in settings/apps but Fakestore is there. I rebooted my phone also but play store app isnt showing. Yes i did correctly rename the file Phonesky.apk put is root data/adb folder by xplorer app and reflash through magisk 25.2 (zygisk enabled)

**Comment by nift4** [comment]
Did it say "Installing real Play Store"?

**Comment by skzidan** [comment]
Yes it showed , fixed the issue by uninstalling fakestore manually by Sd maid app . BTW how do i confirm the location is working or not because i opened google map and it cant detect my location location module is enabled.

**Comment by nift4** [comment]
SatStat app can help you inspect location issues. Remember that you need to be outside for GPS to start working the first time you use it

**Comment by skzidan** [comment]
It just blank and yep i am at outside runnin while checking 
![Screenshot_20221222-134520_SatStat](https://user-images.githubusercontent.com/37244053/209083649-46b82656-2161-4ae0-8dd1-1ea1cd1f5782.png) do I have to flash microg maps API (mapsv1)  ?

**Comment by nift4** [comment]
Check in the first tab, I had issues with tje map before

**Comment by nift4** [comment]
If you have GPS issues, microG has nothing to do with it.
If you experience other issues, please open another issue.
