### ISSUE TITLE
Could not login on Google account on work profile

### ISSUE THREAD

**Issue by Jaajounay** [nift4/microg_installer_revived#65]
I've got [this](https://media.discordapp.net/attachments/903002196013101056/1056381731562856529/Screenshot_20221225-022201_microG_Services_Core.png) error when I try to logging on my Google account with MicroG Settings on work profile

**Comment by nift4** [comment]
Make sure to allow network access (it's disabled by default in some ROMs due to an ROM bug) in App-Info (of work profile) > Mobile Data and Wi-Fi > Allow network usage

**Comment by nift4** [comment]
Closed due to no response
