### ISSUE TITLE
Installing microG GmsCore fails (A12, Stock, Rooted, de-bloated?)

### ISSUE THREAD

**Issue by Radoom** [nift4/microg_installer_revived#67]
Not sure what I'm doing wrong.
- Samsung S10+, A12, Magisk-Rooted, LSposed (Zygisk) running; 
- de-bloated using UAD, can't see what other google-stuff I'd need to remove;
- Installed whew-inc/FakeGApps 4.2; 
> - Though: the instructions on that repo state that having microG is a [PRErequisite](https://github.com/whew-inc/FakeGApps#prerequisites) for his module. "PRE" meaning microG (using microg_installer_revived) would have to be installed FIRST?
> - Whereas: microg_installer_revived [Installation](https://github.com/nift4/microg_installer_revived#installation) section says that *his* module (or rather any other sig spoofing solution) needs to be in place first.... hen-and-egg / dog-chasing-tail!? 
> => what's the right sequence please?

- rebooted; FakeGApps is active in LSposed
- try to install microg_installer_revived_3.1.0-0.zip from inside MagiskManager
- Fails with only this (after the usual header stuff):
````
- Installing microG GmsCore
Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result]
- Real Play Store not found, installing Fake Store
Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result]
- Done
````
Hints please, what step am I missing?

**Comment by nift4** [comment]
> what's the right sequence please?

Actually doesn't matter xD, but spoof before microG may save you some trouble with system apps using Google

> INSTALL_FAILED_VERSION_DOWNGRADE

This means Android still knows about Play Services (maybe the debloater is just disabling(/uninstalling for one user only) apps? The actual APK files need to be gone for proper operation of any microG installer

**Comment by Radoom** [comment]
Thanks for the immediate response! Oh, and happy new year !! ;-)
Seems you were right about that de-bloater. It offers "disable" and "uninstall", used the latter, but apparently that doesn't fully "hard-delete" stuff (even though rooted). Most using it seem to be fine with shutting stuff of, not exactly for full-de-googlifying like me. Will have to read up on that later...

So, got the Noisy Cricket out of me pocket and fired this at the beast:
````
adb shell
su
mount -o remount,rw /
pm clear com.google.android.gms
pm uninstall com.google.android.gms
pm uninstall --user 0 com.google.android.gms
rm /system/priv-app/GmsCore/m/independent/*
rm /system/priv-app/GmsCore/*
pm clear com.google.android.gsf
pm uninstall com.google.android.gsf
pm uninstall --user 0 com.google.android.gsf
rm /system/priv-app/GoogleServicesFramework/*
pm clear com.android.vending
pm uninstall --user 0 com.android.vending
rm /system/priv-app/Phonesky/*
````
Some of those line complained (like "not installed for 0" or "Failure [DELETE_FAILED_INTERNAL_ERROR]" - maybe because I poked around in those folder manually.

Then rebooted into TWRP and wiped cache + dalvik cache (may have been unneccessary...)

Then re-installed microg_installer_revived_3.1.0-0.zip from inside MagiskManager - and... tadaa! "Success". 

Rebooted.

"seems" okay, though SignatureSpoofingChecker still shows "Disabled" (yet, microG settings app under self-test is happy...) - nevermind, for what I need, it should be fine.

**Comment by nift4** [comment]
It's normal for SignatureSpoofingChecker to show disabled as FakeGapps only allows microG to spoof signature.
Glad that it works now, and a (late) happy new year!
