### ISSUE TITLE
Droidguard not working

### ISSUE THREAD

**Issue by bellegarde-c** [nift4/microg_installer_revived#7]
Please provide last preview for droidguard:
https://microg.org/download.html

To prevent this issue:
https://github.com/microg/android_packages_apps_RemoteDroidGuard/issues/10

**Comment by bellegarde-c** [comment]
Stupid question but how to update ?

**Comment by nift4** [comment]
Via magisk repo (if it's not available, wait, Magisk repo isn't ultra fast)

**Comment by bellegarde-c** [comment]
ok, thanks.
