### ISSUE TITLE
Error on upgrade to v3.2.0-0

### ISSUE THREAD

**Issue by diamant711** [nift4/microg_installer_revived#71]
Hi!
I'm receiving this error when trying to update the module:
```
-  Installing microG GmsCore
Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 223616050 is older than current 223616052]
```
 Thanks for the amazing work!

**Comment by nift4** [comment]
you downloaded (or flashed) 3.0.0 instead of 3.2.0

**Comment by nift4** [comment]
Okay I'll take that back, I uploaded the wrong ZIP, thanks for reporting
