### ISSUE TITLE
Unable to activate Network-based Geolocation modules

### ISSUE THREAD

**Issue by breversa** [nift4/microg_installer_revived#73]
Hi!

I've installed microg_installer_revived 3.2.0 on an old Samsung Galaxy Tab A6 (2016) running LineageOS 14.1/Android 7.1.2 (patched with https://downloads.nanolx.org/NanoDroid/Stable/ for signature spoofing), but I'm unable to activate any NLP module (except Nominatim).

The toggle is there, but greyed out, although all auto-checks are correct.

Am I missing anything?

**Comment by nift4** [comment]
Greyed out? Can you provide logcat & screenshot?

**Comment by breversa** [comment]
Here you can see the difference between "greyed out" (geolocation modules) and "inactive" (Nominatim) toggles:
![Screenshot_20230316-221508](https://user-images.githubusercontent.com/2071276/225754871-3818fa9e-d9bf-40d1-b54a-aed5adf7fb02.png)

And here's with an "active" toggle (Nominatim):
![Screenshot_20230316-221456](https://user-images.githubusercontent.com/2071276/225755023-463bf7d3-9e04-4388-8d6c-08ffab728091.png)

Here's the logcat (after trying to toggle all modules on):
[nlp.txt](https://github.com/nift4/microg_installer_revived/files/10995946/nlp.txt)

**Comment by nift4** [comment]
All permissions granted?

**Comment by breversa** [comment]
Of course. As I said, all the MicroG auto-checks are clear.

I'll try and de/reactivate them manually to see if it changes anything.

**Comment by nift4** [comment]
MicroG checks don't check for backend permissions

**Comment by breversa** [comment]
I've double-checked and granted all permissions to MicroG and the NLP modules, but no change. 🤔

**Comment by nift4** [comment]
Your old logcat had shown signs that the NLP modules did not have all permissions. I checked microG source code and it tries to connect to backends, and if that fails, it grays the toggle. Please ensure all backends are whitelisted from battery optimization, ensure your device has enough free memory, and if it still fails, please get a new logcat.

**Comment by nift4** [comment]
any update?

**Comment by breversa** [comment]
I've run into some Magisk issues while trying to do some more testing. Once solved, I'll will report back here. Thanks for the follow-up!

**Comment by nift4** [comment]
Let's reopen this if you still have issues
