### ISSUE TITLE
microG crashes on start

### ISSUE THREAD

**Issue by chromium122** [nift4/microg_installer_revived#74]
When I boot my device it instantly shows "microG Services Core keeps stopping" on my screen. My phone is a OnePlus Nord running Lineage 20.0 based on Android 13.

**Comment by nift4** [comment]
logs?

**Comment by chromium122** [comment]
can I use android's built-in bug report feature?

**Comment by nift4** [comment]
yes

**Comment by chromium122** [comment]
installing that fixed the issue completely
