### ISSUE TITLE
Real Play Store not Found

### ISSUE THREAD

**Issue by Chewie610** [nift4/microg_installer_revived#76]
I've put the Phonesky.apk file in the /data/adb directory. However, when I install/reflash the Magisk module, it tells me "Real Play Store not found, installing Fake Store."

Am I doing something wrong? Here's a picture of the apk in the directory. The blue is marking where the Device name is.

![image](https://user-images.githubusercontent.com/105380641/234153821-73de7b68-a9f1-4335-b831-d7d033cbe572.png)

**Comment by Chewie610** [comment]
Using MicroG Installer Revived 3.3.0 with whew-inc's FakeGApps fork. Also using the recommended patched Playstore by Nanolx.

**Comment by Chewie610** [comment]
Nevermind, sorry for wasting your time! Realized I wasn't actually doing it in root directory lol, forgot I had to do that from a Root Explorer on my phone.

**Comment by Chewie610** [comment]
Did not realize the issue was not solved, so reopening the issue. The module did realize that the "Real Play Store" was there but after rebooting, the Play Store is not there. I tried to manually uninstall the fakestore app using SDMaid Cleaner (much like #64) and reflash the module, but that did not suffice in bringing the Play Store back up.

**Comment by Chewie610** [comment]
After deleting the module and com.android.vending package manually (giving me a clean slate), I flashed the module. It detected the Real Play Store apk file but after restarting, it looks like com.android.vending was installed as version 0.1.0 (at least according to SD Maid) which I'm guessing would be the latest FakeStore version. Looks like there might be a bug with the module?

**Comment by nift4** [comment]
Use "Uninstall updates" button for FakeStore in App Info

**Comment by Chewie610** [comment]
I don't see a FakeStore app in my app list in settings (even after turning on settings). The package that shows up when I look up com.android.vending is called "res/animator-v21/design_appbar_state_list_animator.xml."
Using Android 8.1.0, don't know if that affects anything.

**Comment by Chewie610** [comment]
Sorry I didn't mention this in the last comment, but there is no updates to uninstall for the app.

**Comment by nift4** [comment]
Install playstore apk, clear data, reboot and try to open it

**Comment by Chewie610** [comment]
When I try to install using the Phonesky APK, it says failed to install. Using adb, I can see the error code of signatures not matching.

**Comment by Chewie610** [comment]
Perfect, that worked! I must not have cleaned it all up enough before reflashing the module. Looks like the fakestore corrupted install would've caused this to not work. Thanks for the help!

**Comment by AdroitAdorKhan** [comment]
> interesting, can you try to
> 
>     1. Remove module, reboot
> 
>     2. Observe microg and play store/fakestore/com.android.vending gone (if not uninstall them)
> 
>     3. Reflash module and it should say "Installing real Play Store" at first flash

@nift4 facing the same issue. Tried what you have said above. However, the PS is installing but, I can't download or check my apps. PS crashes whenever I am trying to access My Apps.

Besides, if I just flash the module > reboot > place the Phonesky apk in /data/adb > flash the module again, I get "res/animator-v21/design_appbar_state_list_animator.xml." named FakeStore app version 0.1.0.

**Comment by nift4** [comment]
can you please try
1. Clean flash ROM
2. Put phonesky apk in /data/adb
3. Flash module for the first time

**Comment by AdroitAdorKhan** [comment]
@nift4 Thanks. It worked.
