### ISSUE TITLE
Fakestore 0.2.0

### ISSUE THREAD

**Issue by j0110** [nift4/microg_installer_revived#80]
As MicroG provided Fakestore 0.2.0, would it be possible to get an updated version of the installer ?
Thanks a lot for your great work on this project.

[https://github.com/microg/FakeStore/releases/tag/v0.2.0](https://github.com/microg/FakeStore/releases/tag/v0.2.0)

**Comment by nift4** [comment]
https://github.com/nift4/microg_installer_revived/releases/tag/v3.3.2-0
