### ISSUE TITLE
problem with google recorder 

### ISSUE THREAD

**Issue by ziadhussain007** [nift4/microg_installer_revived#81]
cannot sign into google recorder to restore backups , also contacts and calender sync adapters are missing ,plus location services integrations like de ja vu, apple or mozilla

**Comment by nift4** [comment]
1. Make sure to enable both toggles in microG account settings (Android Settings app > Accounts > Google/your gmail > any of the 3 categories > turn ON both toggles)
2. Contact and Calendar sync adapters are not open source, you can use davx5
3. download them from fdroid

**Comment by ziadhussain007** [comment]
Tried but the problem still exist + the contacts and calendar have been fixed
![Screenshot_20230520-022445](https://github.com/nift4/microg_installer_revived/assets/109599249/ce271a23-55de-41d4-9e7e-bb1c883e7efd)

**Comment by nift4** [comment]
if the problem still exists, you have to ask microg for support. this is not an installer issue anymore.
