### ISSUE TITLE
Location modules disappeared with latest version

### ISSUE THREAD

**Issue by pedrom34** [nift4/microg_installer_revived#83]
Hey!
Thanks for your work. 
I updated to latest version by installing the zip file from the releases. With magisk it was crashing, so I installed it from mrepo app. Install was OK and everything was working.
Today I have an issue of wrong location in my GPS, so I wanted to check the location modules in microg settings and... There's nothing:

![Screenshot_20230605-065729_microG Services Core](https://github.com/nift4/microg_installer_revived/assets/21216829/0585f1c3-eacb-45d4-bdc3-6905c1b919e8)

NLP apps are still installed, GPS is kinda working, but no NLP modules in settings... I don't really know what to do... I can provide information, just tell me what you need.

**Comment by RobertoWa** [comment]
just read the changelog of microg

**Comment by pedrom34** [comment]
I'm a dumbass. Sorry.
