### ISSUE TITLE
FakeStore still version 0.1.0

### ISSUE THREAD

**Issue by Lemmiwinks** [nift4/microg_installer_revived#84]
I installed the latest version of microg installer revived, 3.3.2-0, but in app information for FakeStore it still shows the version number 0.1.0 . I had the microg f-droid repo installed long time ago, but I don't think there is anything left from it.

**Comment by nift4** [comment]
Is there some sort of "Uninstall updates" button in App Info? (Maybe hidden behind the three dots)

**Comment by Lemmiwinks** [comment]
Yes there is! What exactly does it do? Should I try that?

**Comment by nift4** [comment]
Click it

**Comment by Lemmiwinks** [comment]
First that solved it, after a restart FakeStore is not listed anymore. Is that how it's supposed to be?

**Comment by nift4** [comment]
Does microG still show it as installed? Are you sure you didn't accidentally install Play Store or something?

**Comment by nift4** [comment]
Then it is UI bug
