### ISSUE TITLE
MicroG as system application

### ISSUE THREAD

**Issue by captainepoch** [nift4/microg_installer_revived#85]
Hello!

As of the 0.2.28 version of MicroG core, it says about privilege permissions required in order to get MicroG working fully, although they're not mandatory.

Is there any way to install MicroG as a system application with your installer that survives flashing rom updates? Or, at least, installing it as a system application, I can always flash the latest installer after a rom update.

Thank you for making this!

Cheers!

**Comment by nift4** [comment]
this installer always installs microg as system app with privilegied permissions
