### ISSUE TITLE
Option to install microg 0.2.27

### ISSUE THREAD

**Issue by DaniAndTheWeb** [nift4/microg_installer_revived#87]
The latest version of microg removed support for the location providers and this causes a less than optimal gps performance. Until microg adresses this problem including new providers other than mozilla is it possible to add an option to install 0.2.27 instead of the latest version?

**Comment by nift4** [comment]
can't you just use old zip?

**Comment by DaniAndTheWeb** [comment]
I tried installing the old zip multiple times but I always end up bootlooping with it.

**Comment by RobertoWa** [comment]
i am using latest microg and location service is still working as it should.

**Comment by DaniAndTheWeb** [comment]
When I use it the location reported is about 1 km off.

**Comment by nift4** [comment]
> I tried installing the old zip multiple times but I always end up in a bootloop with it.

can you get logs from /data/system/dropbox and/or try older real playstore if u use it

**Comment by DaniAndTheWeb** [comment]
I don't use the real play store. Which log do I have to get from the dropbox system folder? I can't see any log related to magisk or gms in there.

**Comment by nift4** [comment]
system_app_crash or system_server_crash or similar, or just whole folder

**Comment by DaniAndTheWeb** [comment]
Here are the logs: 
[dropbox.zip](https://github.com/nift4/microg_installer_revived/files/11872496/dropbox.zip)

**Comment by nift4** [comment]
logs are corrupted, please try again

**Comment by DaniAndTheWeb** [comment]
I tried it again but system_server_crash logs keep being corrupted.

**Comment by DaniAndTheWeb** [comment]
If I wanted to rebuild the package myself with 0.2.27 but your latest changes would it be enough to switch GmsCore and rebuild?

**Comment by DaniAndTheWeb** [comment]
If I rebuild the module changing the 0.2.28 version with the 0.2.27 and reinstall it the system keeps reporting that I've installed version 0.2.28 and the app doesn't work.

**Comment by nift4** [comment]
did you uninstall microg in between

**Comment by DaniAndTheWeb** [comment]
Yes

**Comment by DaniAndTheWeb** [comment]
Seems like I managed to fix everything. I removed any magisk module I had, then I installed the old version of microg and this time it worked, I then reinstalled every other magisk module. It seems like some module was interfering with the downgrade process. I guess this information could be added to the readme as it could help anyone else who wants to downgrade.

**Comment by DaniAndTheWeb** [comment]
I'm closing the issue as just swapping GmsCore with an older version just works in order to downgrade (only if other modules don't interfere).
