### ISSUE TITLE
I cant change location module

### ISSUE THREAD

**Issue by WestSemih123** [nift4/microg_installer_revived#89]
![Screenshot_20230627-145650_microG_Services_Core](https://github.com/nift4/microg_installer_revived/assets/110404534/4e8c2a3e-7187-4c0b-a354-5aa6a24937e5)
It has automaticly check with mozilla services settings and ı cant add or change location modules can anyone please help me?Mozilla services gives wrong information for me.

**Comment by RobertoWa** [comment]
read the changelog of microg

**Comment by WestSemih123** [comment]
Can you please give the link

**Comment by nift4** [comment]
microg removed location module support, please install old version or contact microg project
