### ISSUE TITLE
GSF Proxy doesn't install properly on Android 13 (MIUI 14)

### ISSUE THREAD

**Issue by sam-kzn** [nift4/microg_installer_revived#91]
Hello!
I've some problem with a correctly installing "GSF Proxy".
In a "Self-check" menu of "MicroG settings" it's shown as not installed, but it  presents in "/system/priv-app/".
After manually installing "GSF Proxy" as app by *.apk  in a "Self-check" menu "GSF Proxy" shows as a installed... but only before phone restart.

MicroG installer v. 3.3.2-0
OS: Android 13 (MIUI 14.0.21.0 China)

**Comment by nift4** [comment]
please provide logcat

**Comment by sam-kzn** [comment]
Is it enough?
`---- Jul 8, 2023 9:27:45 PM ----

11-06 01:42:39.319   728   742 I Magisk  : denylist add: [com.google.android.gsf/com.google.android.gsf]

11-06 01:42:43.874  1035  1035 I PKMSImpl: Skip scanning package: com.google.android.gsf, path=/system/priv-app/GsfProxy, reason: boot scanning

07-08 21:23:48.881  1035  1035 I PKMSImpl: Skip scanning package: com.google.android.gsf, path=/data/app/~~L4bCsMREB3fnirvkQlMe_A==/com.google.android.gsf-SXOarAH8FE1W4Tf74TMzmQ==, reason: boot scanning

07-08 21:23:55.967  1035  1035 E ActivityManager: Unable to find com.google.android.gsf/u0

07-08 21:24:21.471  4373  4373 I PackageUtil: not find packageName :com.google.android.gsf

07-08 21:24:34.376  4373  5497 W System.err: android.content.pm.PackageManager$NameNotFoundException: com.google.android.gsf

07-08 21:25:55.096  1035  1410 W ziparchive: Unable to open '/data/app/~~-5F6u5ymO-x5OBPO-B8rUA==/com.google.android.gsf-N8fcf52SGdxSDqu0JhFK7g==/base.dm': No such file or directory

07-08 21:25:55.097  1035  1410 I PackageDexOptimizer: Running dexopt (dexoptNeeded=1) on: /data/app/~~-5F6u5ymO-x5OBPO-B8rUA==/com.google.android.gsf-N8fcf52SGdxSDqu0JhFK7g==/base.apk pkg=com.google.android.gsf isa=arm64 dexoptFlags=boot_complete,profile_guided,public,enable_hidden_api_checks targetFilter=speed-profile oatDir=/data/app/~~-5F6u5ymO-x5OBPO-B8rUA==/com.google.android.gsf-N8fcf52SGdxSDqu0JhFK7g==/oat classLoaderContext=PCL[]{PCL[/system/framework/android.test.base.jar]#PCL[/system/framework/org.apache.http.legacy.jar]}

07-08 21:25:55.190  7536  7536 W dex2oat64: /apex/com.android.art/bin/dex2oat64 --zip-fd=7 --zip-location=base.apk --oat-fd=8 --oat-location=/data/app/~~-5F6u5ymO-x5OBPO-B8rUA==/com.google.android.gsf-N8fcf52SGdxSDqu0JhFK7g==/oat/arm64/base.odex --input-vdex-fd=-1 --output-vdex-fd=9 --swap-fd=10 --classpath-dir=/data/app/~~-5F6u5ymO-x5OBPO-B8rUA==/com.google.android.gsf-N8fcf52SGdxSDqu0JhFK7g== --class-loader-context=PCL[]{PCL[/system/framework/android.test.base.jar]#PCL[/system/framework/org.apache.http.legacy.jar]} --compact-dex-level=none --instruction-set=arm64 --instruction-set-features=default --instruction-set-variant=generic --compiler-filter=speed-profile --compilation-reason=install --cpu-set=0,1,2,3,4,5,6,7 --max-image-block-size=524288 --resolve-startup-const-strings=true --generate-mini-debug-info --runtime-arg -Xtarget-sdk-version:23 --runtime-arg -Xhidden-api-policy:enabled -j6 --runtime-arg -Xms64m --runtime-arg -Xmx512m --inline-max-code-units=0

07-08 21:25:55.191  7536  7536 I dex2oat64: /apex/com.android.art/bin/dex2oat64 --input-vdex-fd=-1 --output-vdex-fd=9 --classpath-dir=/data/app/~~-5F6u5ymO-x5OBPO-B8rUA==/com.google.android.gsf-N8fcf52SGdxSDqu0JhFK7g== --class-loader-context=PCL[]{PCL[/system/framework/android.test.base.jar]#PCL[/system/framework/org.apache.http.legacy.jar]} --compact-dex-level=none --compiler-filter=speed-profile --compilation-reason=install --cpu-set=0,1,2,3,4,5,6,7 --max-image-block-size=524288 --resolve-startup-const-strings=true --generate-mini-debug-info -j6 --inline-max-code-units=0

07-08 21:25:55.344  1035  1410 W PackageFreezer: Freeze package com.google.android.gsf about 0.462 seconds for reason: installPackageLI

07-08 21:25:55.346  1035  1410 I BackupManagerService: [UserID:0] restoreAtInstall pkg=com.google.android.gsf token=1 restoreSet=0

07-08 21:25:55.347  1035  1410 I InstallationTiming: com.google.android.gsf|null|592|21|31|1|37|258

07-08 21:25:55.350  1035  1410 I AppsFilter: interaction: PackageSetting{db2b510 com.fido.asm/10136} -> PackageSetting{2a22809 com.google.android.gsf/10295} BLOCKED

07-08 21:25:55.400  4293  4293 I MediaProvider: Invalidating LocalCallingIdentity cache for package com.google.android.gsf. Reason: package android.intent.action.PACKAGE_ADDED

07-08 21:25:55.431  1035  1367 I MiuiCompatModePackages: package com.google.android.gsf updated, removing config

07-08 21:25:55.433  1035  2810 E AppScanObserverService: Try to add a invalid package: com.google.android.gsf | 10295 | 0

07-08 21:25:55.477  4458  4458 I PackageInstallReceiver: action = android.intent.action.PACKAGE_ADDED packageName = com.google.android.gsf

07-08 21:25:55.478  4458  4458 I SingleShortcutPackageChangeListener: onAppChanged packageName: com.google.android.gsf action: android.intent.action.PACKAGE_ADDED xspace: false

07-08 21:25:55.494  4516  4516 I WakePathManager: PackageMonitor. onPackageAdded: packageName =com.google.android.gsf

07-08 21:25:55.499  4373  5499 I MiuiVpnManageService: PackageMonitor. onPackageAdded: packageName =com.google.android.gsf

07-08 21:25:55.515  4373  4373 I InstalledAppMonitor: com.google.android.gsfonReceive add pkg=com.google.android.gsf

07-08 21:25:55.519  4189  4189 E SLM-SRV-SLAAppLib: initBroadcastReceivercom.google.android.gsf

07-08 21:25:55.519  4189  4189 I SLM-SRV-SLAAppLib: ACTION_PACKAGE_ADDED uid = 10295com.google.android.gsf

07-08 21:25:55.522  4373  5483 I GameBoosterNewApp: com.google.android.gsf isGameFromJson false

07-08 21:25:55.528  4373  5483 I GameBoosterNewApp: com.google.android.gsf isGameFromLocal false

07-08 21:25:55.538  5224  7558 I Finsky  : [124] aw.a(5): Asset module storage cleared for package com.google.android.gsf.

07-08 21:25:55.538  5224  5224 I Finsky  : [2] jft.f(1): AIM: AppInfoCacheUpdater -> invalidating apps: [com.google.android.gsf]

07-08 21:25:55.591  5224  5418 I Finsky  : [59] jhq.a(5): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.google.android.gsf]

07-08 21:25:55.745  4373  5185 I LocalNotificationMgr: pkg: com.google.android.gsf mode:0

07-08 21:25:55.777  4172  6944 E SQLiteDatabase: Error inserting totalWeight=0.0 count=0.0 initWeight=0.0 packagename=com.google.android.gsf

07-08 21:25:55.792  4172  6944 W SQLiteLog: (28) double-quoted string literal: "com.google.android.gsf"

07-08 21:25:55.859  1035  1035 I AppsFilter: interaction: PackageSetting{db2b510 com.fido.asm/10136} -> PackageSetting{9b98869 com.google.android.gsf/10295} BLOCKED

07-08 21:25:55.905  4721  4721 I FindDeviceGNReceiver: isReplace: false, packageName: package:com.google.android.gsf. 

07-08 21:25:55.923  4458  4458 I PackageInstallReceiver: action = android.intent.action.PACKAGE_CHANGED packageName = com.google.android.gsf

07-08 21:25:55.924  4458  4458 I AppWidgetDelegate: updateAppWidgets for com.google.android.gsf

07-08 21:25:55.924  4458  4458 I SingleShortcutPackageChangeListener: onAppChanged packageName: com.google.android.gsf action: android.intent.action.PACKAGE_CHANGED xspace: false

07-08 21:25:55.956  1035  4031 W BackupTransportManager: Package com.google.android.gsf enabled setting: 0

07-08 21:25:56.028  5224  5224 I Finsky  : [2] jft.f(1): AIM: AppInfoCacheUpdater -> invalidating apps: [com.google.android.gsf]

07-08 21:25:56.067  5224  5419 I Finsky  : [60] jhq.a(5): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.google.android.gsf]

07-08 21:25:56.229  4650  4650 I VSC-AppInstallReceiver: action: android.intent.action.PACKAGE_CHANGED, packageName: com.google.android.gsf

---- Jul 8, 2023 9:27:45 PM ----
`

**Comment by nift4** [comment]
can you try to remove gsf from denylist/magisk hide?

**Comment by sam-kzn** [comment]
Yes, I,'ve removed it from deny list.
Bit it dpesn't help. As You can see after reboot the GSF gone away until I install it manually.

`---- Jul 8, 2023 23:28:52 ----

11-06 03:34:42.827  1041  1041 I PKMSImpl: Skip scanning package: com.google.android.gsf, path=/system/priv-app/GsfProxy, reason: boot scanning

07-08 23:15:48.368  1041  1041 I PKMSImpl: Skip scanning package: com.google.android.gsf, path=/data/app/~~-5F6u5ymO-x5OBPO-B8rUA==/com.google.android.gsf-N8fcf52SGdxSDqu0JhFK7g==, reason: boot scanning

07-08 23:15:52.897  1041  1041 E ActivityManager: Unable to find com.google.android.gsf/u0

07-08 23:16:37.986  4443  5311 W System.err: android.content.pm.PackageManager$NameNotFoundException: com.google.android.gsf

07-08 23:18:06.393  7968  7989 I PackageUtil: not find packageName :com.google.android.gsf

07-08 23:20:31.570  1041  1410 W ziparchive: Unable to open '/data/app/~~LZpvzwAsVIKG5V3QZ69Etg==/com.google.android.gsf-r0ZiQLV01EGvow_UUSg9gg==/base.dm': No such file or directory

07-08 23:20:31.572  1041  1410 I PackageDexOptimizer: Running dexopt (dexoptNeeded=1) on: /data/app/~~LZpvzwAsVIKG5V3QZ69Etg==/com.google.android.gsf-r0ZiQLV01EGvow_UUSg9gg==/base.apk pkg=com.google.android.gsf isa=arm64 dexoptFlags=boot_complete,profile_guided,public,enable_hidden_api_checks targetFilter=speed-profile oatDir=/data/app/~~LZpvzwAsVIKG5V3QZ69Etg==/com.google.android.gsf-r0ZiQLV01EGvow_UUSg9gg==/oat classLoaderContext=PCL[]{PCL[/system/framework/android.test.base.jar]#PCL[/system/framework/org.apache.http.legacy.jar]}

07-08 23:20:31.641  9104  9104 W dex2oat64: /apex/com.android.art/bin/dex2oat64 --zip-fd=7 --zip-location=base.apk --oat-fd=8 --oat-location=/data/app/~~LZpvzwAsVIKG5V3QZ69Etg==/com.google.android.gsf-r0ZiQLV01EGvow_UUSg9gg==/oat/arm64/base.odex --input-vdex-fd=-1 --output-vdex-fd=9 --swap-fd=10 --classpath-dir=/data/app/~~LZpvzwAsVIKG5V3QZ69Etg==/com.google.android.gsf-r0ZiQLV01EGvow_UUSg9gg== --class-loader-context=PCL[]{PCL[/system/framework/android.test.base.jar]#PCL[/system/framework/org.apache.http.legacy.jar]} --compact-dex-level=none --instruction-set=arm64 --instruction-set-features=default --instruction-set-variant=generic --compiler-filter=speed-profile --compilation-reason=install --cpu-set=0,1,2,3,4,5,6,7 --max-image-block-size=524288 --resolve-startup-const-strings=true --generate-mini-debug-info --runtime-arg -Xtarget-sdk-version:23 --runtime-arg -Xhidden-api-policy:enabled -j6 --runtime-arg -Xms64m --runtime-arg -Xmx512m --inline-max-code-units=0

07-08 23:20:31.641  9104  9104 I dex2oat64: /apex/com.android.art/bin/dex2oat64 --input-vdex-fd=-1 --output-vdex-fd=9 --classpath-dir=/data/app/~~LZpvzwAsVIKG5V3QZ69Etg==/com.google.android.gsf-r0ZiQLV01EGvow_UUSg9gg== --class-loader-context=PCL[]{PCL[/system/framework/android.test.base.jar]#PCL[/system/framework/org.apache.http.legacy.jar]} --compact-dex-level=none --compiler-filter=speed-profile --compilation-reason=install --cpu-set=0,1,2,3,4,5,6,7 --max-image-block-size=524288 --resolve-startup-const-strings=true --generate-mini-debug-info -j6 --inline-max-code-units=0

07-08 23:20:31.754  1041  1410 W PackageFreezer: Freeze package com.google.android.gsf about 0.389 seconds for reason: installPackageLI

07-08 23:20:31.757  1041  1410 I BackupManagerService: [UserID:0] restoreAtInstall pkg=com.google.android.gsf token=1 restoreSet=0

07-08 23:20:31.759  1041  1410 I InstallationTiming: com.google.android.gsf|null|526|20|32|4|38|173

07-08 23:20:31.761  1041  1410 I AppsFilter: interaction: PackageSetting{bbe1adc com.fido.asm/10136} -> PackageSetting{420e66 com.google.android.gsf/10298} BLOCKED

07-08 23:20:31.802  4262  4262 I MediaProvider: Invalidating LocalCallingIdentity cache for package com.google.android.gsf. Reason: package android.intent.action.PACKAGE_ADDED

07-08 23:20:31.825  1041  1376 I MiuiCompatModePackages: package com.google.android.gsf updated, removing config

07-08 23:20:31.827  1041  2778 E AppScanObserverService: Try to add a invalid package: com.google.android.gsf | 10298 | 0

07-08 23:20:31.854  4443  5300 I MiuiVpnManageService: PackageMonitor. onPackageAdded: packageName =com.google.android.gsf

07-08 23:20:31.858  4163  4163 E SLM-SRV-SLAAppLib: initBroadcastReceivercom.google.android.gsf

07-08 23:20:31.858  4163  4163 I SLM-SRV-SLAAppLib: ACTION_PACKAGE_ADDED uid = 10298com.google.android.gsf

07-08 23:20:31.870  4723  4723 I WakePathManager: PackageMonitor. onPackageAdded: packageName =com.google.android.gsf

07-08 23:20:31.871  4443  4443 I InstalledAppMonitor: com.google.android.gsfonReceive add pkg=com.google.android.gsf

07-08 23:20:31.885  4443  5286 I GameBoosterNewApp: com.google.android.gsf isGameFromJson false

07-08 23:20:31.893  4443  5286 I GameBoosterNewApp: com.google.android.gsf isGameFromLocal false

07-08 23:20:31.901  4302  4302 I PackageInstallReceiver: action = android.intent.action.PACKAGE_ADDED packageName = com.google.android.gsf

07-08 23:20:31.902  4302  4302 I SingleShortcutPackageChangeListener: onAppChanged packageName: com.google.android.gsf action: android.intent.action.PACKAGE_ADDED xspace: false

07-08 23:20:31.969  1041  1041 I AppsFilter: interaction: PackageSetting{bbe1adc com.fido.asm/10136} -> PackageSetting{3778090 com.google.android.gsf/10298} BLOCKED

07-08 23:20:31.983  4443  5172 I LocalNotificationMgr: pkg: com.google.android.gsf mode:0

07-08 23:20:31.985  4663  4663 I FindDeviceGNReceiver: isReplace: false, packageName: package:com.google.android.gsf. 

07-08 23:20:31.993  4302  4302 I PackageInstallReceiver: action = android.intent.action.PACKAGE_CHANGED packageName = com.google.android.gsf

07-08 23:20:31.998  4134  7126 E SQLiteDatabase: Error inserting totalWeight=0.0 count=0.0 initWeight=0.0 packagename=com.google.android.gsf

07-08 23:20:31.999  5185  5185 I Finsky  : [2] jft.f(1): AIM: AppInfoCacheUpdater -> invalidating apps: [com.google.android.gsf]

07-08 23:20:32.000  4134  7126 W SQLiteLog: (28) double-quoted string literal: "com.google.android.gsf"

07-08 23:20:32.000  4302  4302 I AppWidgetDelegate: updateAppWidgets for com.google.android.gsf

07-08 23:20:32.001  4302  4302 I SingleShortcutPackageChangeListener: onAppChanged packageName: com.google.android.gsf action: android.intent.action.PACKAGE_CHANGED xspace: false

07-08 23:20:32.016  1041  3999 W BackupTransportManager: Package com.google.android.gsf enabled setting: 0

07-08 23:20:32.072  5185  5507 I Finsky  : [59] jhq.a(5): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.google.android.gsf]

07-08 23:20:32.098  5185  9151 I Finsky  : [135] aw.a(5): Asset module storage cleared for package com.google.android.gsf.

07-08 23:20:32.109  5185  5185 I Finsky  : [2] jft.f(1): AIM: AppInfoCacheUpdater -> invalidating apps: [com.google.android.gsf]

07-08 23:20:32.112  5185  5399 I Finsky  : [44] jhq.a(5): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.google.android.gsf]

07-08 23:20:32.136  4845  4845 I VSC-AppInstallReceiver: action: android.intent.action.PACKAGE_CHANGED, packageName: com.google.android.gsf

---- Jul 8, 2023 23:28:52 ----
`

**Comment by nift4** [comment]
no idea then

**Comment by nift4** [comment]
stale
