### ISSUE TITLE
GmsCore v0.2.28.231657 faulty (fixed in core-nightly.apk)

### ISSUE THREAD

**Issue by moonshine-cc** [nift4/microg_installer_revived#92]
You may want to consider an intermediate release with the current nightly build of GmsCore because the last release has a nasty bug that makes certain apps crash. Link and and info [here](https://github.com/microg/GmsCore/issues/1962).

**Comment by nift4** [comment]
it's my policy to only ship official microg  releases, however, you should be able to apk upgrade
