### ISSUE TITLE
MicroG 0.2.29 and Fakestore 0.2.1

### ISSUE THREAD

**Issue by Wojtaz0w** [nift4/microg_installer_revived#96]
Updated today 🙂

**Comment by africabloe** [comment]
I installed the new version for [GmsCore](https://github.com/microg/GmsCore/releases) [v0.2.29.233013](https://github.com/microg/GmsCore/releases/tag/v0.2.29.233013) via F-Droid updates and everything works without any error on my Redmi Note 4X crDroid 9.8 Android 13 device. 
I didn't tried the [Fakestore](https://github.com/microg/FakeStore/releases) [v0.2.1](https://github.com/microg/FakeStore/releases/tag/v0.2.1)
![photo_2_2023-09-18_00-01-56](https://github.com/nift4/microg_installer_revived/assets/67532153/9d876a3b-cdf8-420b-bc0f-e0746aeb8d60)
![photo_3_2023-09-18_00-01-56](https://github.com/nift4/microg_installer_revived/assets/67532153/47ec8c79-a1ed-47aa-936a-68975794ab48)
![photo_4_2023-09-18_00-01-56](https://github.com/nift4/microg_installer_revived/assets/67532153/c6379f69-568c-4192-bf0f-0a8da560393f)
![photo_5_2023-09-18_00-01-56](https://github.com/nift4/microg_installer_revived/assets/67532153/eab5dcfc-956f-41b8-b679-d190632fdf2c)
![photo_6_2023-09-18_00-01-56](https://github.com/nift4/microg_installer_revived/assets/67532153/f9f79f91-c2c6-4c90-a626-75328dd54ee7)

**Comment by catfluoride** [comment]
> I installed the new version for [GmsCore](https://github.com/microg/GmsCore/releases) [v0.2.29.233013](https://github.com/microg/GmsCore/releases/tag/v0.2.29.233013) via F-Droid updates and everything works without any error on my Redmi Note 4X crDroid 9.8 Android 13 device. I didn't try to install the [Fakestore](https://github.com/microg/FakeStore/releases) [v0.2.1](https://github.com/microg/FakeStore/releases/tag/v0.2.1) ![photo_2_2023-09-18_00-01-56](https://user-images.githubusercontent.com/67532153/268528236-9d876a3b-cdf8-420b-bc0f-e0746aeb8d60.jpg) ![photo_3_2023-09-18_00-01-56](https://user-images.githubusercontent.com/67532153/268528238-47ec8c79-a1ed-47aa-936a-68975794ab48.jpg) ![photo_4_2023-09-18_00-01-56](https://user-images.githubusercontent.com/67532153/268528239-c6379f69-568c-4192-bf0f-0a8da560393f.jpg) ![photo_5_2023-09-18_00-01-56](https://user-images.githubusercontent.com/67532153/268528244-eab5dcfc-956f-41b8-b679-d190632fdf2c.jpg) ![photo_6_2023-09-18_00-01-56](https://user-images.githubusercontent.com/67532153/268528245-f9f79f91-c2c6-4c90-a626-75328dd54ee7.jpg)

Hi!

So it is actually possible to upgrade microg install revived using f-drois microg releases on top? Or did you just install it from scratch from f-droid?

Just asking, before making a mess 😄

**Comment by catfluoride** [comment]
> yes, user can upgrade all apps from official download without functionality impact, it's supported usecase

Seems like fdroid version is signed with a different certificate, this can't update uG Revived...

![Uploading Screenshot_20230918-162628_Droid-ify.png…]()

**Comment by nift4** [comment]
does https://microg.org/download.html work? i take apks from there

**Comment by africabloe** [comment]
@catfluoride I did it exactly as @nift4 said. I have microG Installer Revived on my mobile's Magisk as a module and when I opened F-Droid it showed me that there was an update for microG Companion and microG Services. I installed them and everything works as it should. This is not the first time I update microG Installer Revived via F-Droid.

**Comment by africabloe** [comment]
And I don't know why but GMaps is working even better than before with the latest GmsCore. Faster and more precisely.

**Comment by catfluoride** [comment]
> does https://microg.org/download.html work? i take apks from there

Actually,these worked. Very odd.

**Comment by glemco** [comment]
That fdroid client is neostore right? I'm having the same problem. Didn't have time to try other stores, but it seems that downloading from the link (from neostore share it to the browser) and installing manually works just fine. I'm not sure where was that signature mismatch coming from

**Comment by catfluoride** [comment]
Hi, @glemco. It was actually Droidi-fy. Maybe something with unofficial fdroid clients? I'll look further into if/what possible.

**Comment by glemco** [comment]
Yeah neodroid is a fork of that, could be the problem

**Comment by glemco** [comment]
Mmh makes sense, thanks 👍
