### ISSUE TITLE
INSTALL_FAILED_DUPLICATE_PREMISSION when updating

### ISSUE THREAD

**Issue by mio-19** [nift4/microg_installer_revived#97]
log:

[magisk_install_log_2023-10-06T01.50.09.log](https://github.com/nift4/microg_installer_revived/files/12821617/magisk_install_log_2023-10-06T01.50.09.log)

**Comment by mio-19** [comment]
Some Android Emulator rooted with [rootAVD](https://github.com/newbit1/rootAVD/blob/master/rootAVD.bat) Magisk 26.3 Android 12

**Comment by mio-19** [comment]
The emulator is from Huawei, who added androidhwext things I suppose

**Comment by nift4** [comment]
i'm sorry but i won't / can't add much workaround for this, you can try to use module anyway, but huawei and their gms support chaos is not something i can fix
