### ISSUE TITLE
F-Droid Signature incompatible

### ISSUE THREAD

**Issue by foxjaw** [nift4/microg_installer_revived#99]
Can you please use the builds which are f-droid certified ? I need to update apps directly through f-droid.  

![Screenshot_20231108](https://github.com/nift4/microg_installer_revived/assets/150133625/2c6424c8-1f12-4e6f-bdc3-1584c19d9375)

**Comment by nift4** [comment]
please try official f-droid client first

**Comment by foxjaw** [comment]
Same. Although, f-droid client is not an issue, since the micro-g repository is same in both.  
I downloaded latest preview apk from microg.org & it updated fine. Which means that you're using microg.org source, instead of f-droid. Why not just use f-droid source, so that we can update it directly from f-droid ?

**Comment by nift4** [comment]
well where do i get the microg fdroid apks as file?

**Comment by uvww** [comment]
I agree that we should be able to update microg through f-droid repository so we can update it easily if you stop releasing new versions of module.

**Comment by foxjaw** [comment]
@uvww There's a new prerelease v0.30 something, which @nift4 has yet to release though. This is a great chance to shift the build variants to f-droid (both gms-core & fakestore).

**Comment by nift4** [comment]
...well, last time someone opened an issue about this, it ended up with him saying he can update via fdroid now. I will acquire the fdroid variant and compare certificates, but I always thought they were the same.

**Comment by foxjaw** [comment]
Seems like f-droid is building the app with it's own server & shipping, which is a thing f-droid does since it's existence. Yes please. Check the certificates once. I believe they're different, which is why I wasn't able to update, when I had your magisk module.

**Comment by nift4** [comment]
your screenshot says microg fdroid repo, which is unrelated to however fdroid builds their apks

**Comment by foxjaw** [comment]
That app is Drodify btw. Although, the repo address is the same as what microg provided in it's download page.

**Comment by uvww** [comment]
> @uvww There's a new prerelease v0.30 something, which @nift4 has yet to release though. This is a great chance to shift the build variants to f-droid (both gms-core & fakestore).

How can i change build variants? F-droid doesn't allow me to update microg and updating it through microg website probably won't change variants or am i wrong?

**Comment by foxjaw** [comment]
@uvww For now, download it directly from microg download page (bottom links). They're hosted by microg themselves.

**Comment by LuccoJ** [comment]
> Seems like f-droid is building the app with it's own server & shipping, which is a thing f-droid does since it's existence. Yes please. Check the certificates once. I believe they're different, which is why I wasn't able to update, when I had your magisk module.

No  because F-Droid doesn't ship microG at all. Marvin does, through *his own* F-Droid repo, where of course it's not built with F-Droid's server and signature, but with Marvin. @nift4 you can also get the APKs from https://microg.org/download.html (at the bottom of the page) to avoid this whole confusion about F-Droid... But, anyway, if you get it from the F-Droid repo on that same page, they'll have the same signature: Marvin's, not F-Droid's. F-Droid's own repos do NOT distribute microG, though they used to distribute the standalone UnifiedNLP (now it's archived).

**Comment by nift4** [comment]
that is quite literally what i am doing

**Comment by LuccoJ** [comment]
Okay. I don't think I can help then, but I wanted to clarify this apparent confusion about F-Droid being involved with their signed official repository. :shrug:

**Comment by nift4** [comment]
I am thankful for the clarification either way, yet it adds to the confusion because there appears to be no reason for the incompatible signature.

**Comment by nift4** [comment]
i successfully updated to 0.3.0 via microg fdroid repo on my daily driver, which proves the signatures have to be the same (why would the apks be different based on who downloads them) - as i use the same apks, any further issues should be directed at f-droid or microg
